### ISSUE TITLE
Mage quest level 10

### ISSUE THREAD

**Issue by Plantfusion** [chromiecraft/chromiecraft#1010]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Mage quest is suppose to start at level 10. But it seem to start at level 11 (Quest mark is grey at level 10). 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Quest should start at level 10 : https://wowgaming.altervista.org/aowow/?quest=1861

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Windows 10

##### SERVER:

ChromieCraft

**Comment by Efymer** [comment]
Cannot reproduce it. I tested it on my local AzerothCore server and:

- You need to get and return https://wowgaming.altervista.org/aowow/?quest=1860 in order to be able to pick up https://wowgaming.altervista.org/aowow/?quest=1861.
- The level requierement works fine, with a level 10 character I can start the quest.

**Comment by eTzmNcbkrng** [comment]
Investigated this player's character, he had completed 1860 but was unable to pick up 1861.
Used GM commands to grant him the quest.
