### ISSUE TITLE
bug(NPC): Pridewing Wyvern

### ISSUE THREAD

**Issue by claudiodfc** [chromiecraft/chromiecraft#1095]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Might not be a bug since I'm using Warlords of Draenor models.

Currently they aren't doing their flying animation but walking on the ground. Also when they die this is what happens:
![image](https://user-images.githubusercontent.com/54484196/124402345-99479380-dd27-11eb-8511-60d0c64da280.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Check min 2:23 from this video
https://youtu.be/xKO-1U2d05o?t=143

##### SOURCE:

https://youtu.be/xKO-1U2d05o?t=143

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find the Pridewing Wyverns and kill them.

##### EXTRA NOTES:

As I stated above, I'm using the new models.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
I think is related to the texture mod yes, since in the normal client doesn't happen:

![WoWScrnShot_070521_083410](https://user-images.githubusercontent.com/82579073/124422429-ed746700-dd6b-11eb-9fd2-0d8114c0fcdd.jpg)
![WoWScrnShot_070521_083420](https://user-images.githubusercontent.com/82579073/124422470-ffeea080-dd6b-11eb-8e4e-f9348587592f.jpg)

**Comment by syssneck** [comment]
I also don't have the problem here:

![Screenshot 2021-07-05 10 30 00](https://user-images.githubusercontent.com/68868567/124441517-0be25e80-dd7c-11eb-8010-9a7703997fb3.png)
![Screenshot 2021-07-05 10 30 26](https://user-images.githubusercontent.com/68868567/124441524-0dac2200-dd7c-11eb-8711-ad47f681d5a1.png)

**Comment by temperrr** [comment]
It's a bug with the WoD models
