### ISSUE TITLE
Lament of the Highborne book includes html text

### ISSUE THREAD

**Issue by Eistorm** [chromiecraft/chromiecraft#110]
##### ISSUE: FACTION SIDE:

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

 NPC: [Ambassador Sunsorrow](https://wowgaming.altervista.org/aowow/?npc=16287#abilities)
Spell: [Serverside - Lament of the Highborne: Songbook](https://wowgaming.altervista.org/aowow/?spell=37084)
 Item: [Lament of the Highborne](https://wowgaming.altervista.org/aowow/?item=30632)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When read, the book Lament of the Highborne contains the lyrics to the song of the same name.

##### CURRENT BEHAVIOUR:

The text in the book includes html text.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Teleport to Ambassador Sunsorrow
Step 2: Have the NPC create the item in question via the skill Serverside - Lament of the Highborne: Songbook
Step 3: Right-click to open the book
![Capture](https://user-images.githubusercontent.com/79746568/109403849-e228af00-7925-11eb-9e9f-af5859d6d312.JPG)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7ec204943a3080071e0f1d7b7d18e10cbc4d1918

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
lol

**Comment by illfated** [comment]
Hmm, well, that is odd. I use TrinityCore 3.3.5 and item 30632 looks correct to me there, even if the `page_text` content is HTML in the DB. I wonder if there are some codes in the `item_template` to make sure the text is correctly viewed in the game client, or if the important part is how the HTML is stored in the `page_text` pages .

<details>
<summary>Full screen (1920x1200) screenshot with details and image from page 1 of "Lament of the Highborne" ◄◄</summary>


![WoWScrnShot_022821_102841](https://user-images.githubusercontent.com/38162891/109414355-c28b9800-79b2-11eb-8632-f9c4b8cc9708.jpg)


</details>

***
I have not yet started using chromiecraft or AzerothCore source & DB, so I don't know the DB table layout here, but this is how I checked the contents in TDB 335.21021:

```sql
SELECT * FROM `item_template` WHERE `entry`= 30632;
--
SELECT * FROM `page_text` WHERE `ID` IN (2990, 2991, 2992);
```

**Comment by Stifler82** [comment]
> Hmm, well, that is odd. I use TrinityCore 3.3.5 and item 30632 looks correct to me there, even if the `page_text` content is HTML in the DB. I wonder if there are some codes in the `item_template` to make sure the text is correctly viewed in the game client, or if the important part is how the HTML is stored in the `page_text` pages .
> 
> Full screen (1920x1200) screenshot with details and image from page 1 of "Lament of the Highborne" ◄◄
> I have not yet started using chromiecraft or AzerothCore source & DB, so I don't know the DB table layout here, but this is how I checked the contents in TDB 335.21021:
> 
> ```sql
> SELECT * FROM `item_template` WHERE `entry`= 30632;
> --
> SELECT * FROM `page_text` WHERE `ID` IN (2990, 2991, 2992);
> ```

So, (mine is just a guess, I'm not saying that's the way I'm guessing).

I don't know which Client is using this Player, (MA), if it is using an enGB Client, since the enGB Client uses (MPQ) different from those of the enUS Client, it could be that the enGB Client "misreads" the information and translates like this, I have the enUS Client and I haven't tested this bug yet.

However! it could be!
what do you think about @illfated?

**Comment by illfated** [comment]
I don't know, because I have always used the enGB client, because that is the one I bought back in 2006 and updated to 3.3.5a and have used ever since.

<details>
<summary>Screenshot of the \Data\enGB folder</summary>

![image](https://user-images.githubusercontent.com/38162891/109417042-2c5f6e00-79c2-11eb-8331-f82a10954899.png)


</details>

<details>
<summary>Screenshot of the enGB TOS/TOU</summary>

![image](https://user-images.githubusercontent.com/38162891/109417211-ece55180-79c2-11eb-9aea-ae39ccbc38ad.png)

</details>

<details>
<summary>Screenshot of the 3.3.5a 12340 game client</summary>

![image](https://user-images.githubusercontent.com/38162891/109417308-59f8e700-79c3-11eb-8f7a-8d695b7f206d.png)

</details>

I remember having some game client gameobject issues from incomplete dbc/maps files back in 2014 when I started using TC, but I have managed to correct the issues when I found the source. I guess I would have to test the AC/chromiecraft source to replicate the issue, unless someone else can confirm it.

For some odd reason, the TC AoWoW page for the item "Lament of the Highborne" (http://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=30632/lament-of-the-highborne) states "**This item is not available to players.**", which is not the case for https://www.wowhead.com/item=30632/lament-of-the-highborne .

**Comment by Stifler82** [comment]
trust me, switch to the enUS version you will see that you will find better, the enGB version of wow was a failing version..

**Comment by illfated** [comment]
Maybe you are right, sounds like you have done the necessary research to be able to say it with confidence. I guess I should swallow my pride of having the original files from 2010, even with the file dates intact. (Windows messed with the file dates and shows 2012 after my last restore from 5 years back, so it does not look as impressive anymore.) I have sort of learnt to live with any quirks as not being a server bug, but the game client bugs seem to be decreasing compared to 2014, so maybe some files without the "enGB" part in the name are replaced with enUS ones.

**Comment by Stifler82** [comment]
> Maybe you are right, sounds like you have done the necessary research to be able to say it with confidence. I guess I should swallow my pride of having the original files from 2010, even with the file dates intact. (Windows messed with the file dates and shows 2012 after my last restore from 5 years back, so it does not look as impressive anymore.) I have sort of learnt to live with any quirks as not being a server bug, but the game client bugs seem to be decreasing compared to 2014, so maybe some files without the "enGB" part in the name are replaced with enUS ones.
> 
> edit: Just to make sure I get my point across, the issue on this page does not happen in my client, but I am using TC source & DB.


I am not saying that the problem must necessarily be related to the client, maybe it is a problem of our DB, we just need to investigate for a moment, to understand where the problem is.
(but in any case, I renew the notion that the enGB client is bad).

Let's put it this way, when a Bug appears (and you are using the enUS client), at 99% it is a server-side problem, if instead (you are using an enGB client), you will always have the doubt that the problem may be on the client side, so ( in my opinion) it is best to always use an enUS client to drastically drop the amount of doubt about the origin of the bug.

**Comment by illfated** [comment]
> Let's put it this way, when a Bug appears (and you are using the enUS client), at 99% it is a server-side problem, if instead (you are using an enGB client), you will always have the doubt that the problem may be on the client side, so ( in my opinion) it is best to always use an enUS client to drastically drop the amount of doubt about the origin of the bug.

Fair point. I can see that being a useful work philosophy.

**Comment by Helias** [comment]
@Eistorm what game client are you using? I can't reproduce this

**Comment by Eistorm** [comment]
enUS. Directly downloaded from ChromieCraft website. No mods.

**Comment by Helias** [comment]
I cannot reproduce in ChromieCraft too, I have an enUS client.

Try to delete Cache and rename your WTF directory into WTF_2 to reset the configuration and try again.

Anyways, thank you for the report

**Comment by Stifler82** [comment]
**Non-existent bug, I close..**
<details>
<summary>ScreenShots</summary>

![WoWScrnShot_030421_092306](https://user-images.githubusercontent.com/1884642/109941707-54edad80-7ccb-11eb-9b2f-ea68c26a1371.jpg)
![WoWScrnShot_030421_092310](https://user-images.githubusercontent.com/1884642/109941709-561eda80-7ccb-11eb-9183-81a39c7bc9be.jpg)
![WoWScrnShot_030421_092313](https://user-images.githubusercontent.com/1884642/109941710-561eda80-7ccb-11eb-9919-dbacd2e828e5.jpg)

</details>
