### ISSUE TITLE
Stun abilities on bosses

### ISSUE THREAD

**Issue by santosho81** [chromiecraft/chromiecraft#1216]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Most if not all dungeon bosses are stunable and should not be.
For exemple casting Hammer of Justice on Verdan the Everliving should not be possible.
Exemple links:
https://wowgaming.altervista.org/aowow/?spell=853
https://wowgaming.altervista.org/aowow/?npc=5775

### Expected Blizzlike Behaviour

You are not supposed to stun bosses.
https://us.forums.blizzard.com/en/wow/t/do-stun-effects-work-on-bosses-in-dungeons-or-raids/138905/11

### Source

https://wowpedia.fandom.com/wiki/Stun "All raid bosses, most or all dungeon bosses and many elite mobs are permanently immune to stuns."

### Steps to reproduce the problem

1. Get inside any dungeon  
2. Use any stun ability on a boss

### Extra Notes

sorry if i'm missing something this is my first time doing a report.

**Comment by Shineslippers** [comment]
This is debatable if we're talking about low lvl dungeons. There is no strong evidence in my opinion.

**Comment by pop-pig** [comment]
I agree with @Shineslippers , some low level bosses or "small bosses" (for instance the six troll mini bosses in ST) can be stunned, but most "real bosses" are immune.
Thanks for the report anyway! :D

**Comment by necropola** [comment]
That's a weird one ... Wowpedia does not seem to be consistent about whether or not or rather which bosses may be immune to CC.

### Current Wowpedia
... suggests that only Raid bosses are definitely immune to CC while some normal bosses may not:
- https://wowpedia.fandom.com/wiki/Boss
> A common characteristic for all bosses is that they have a unique name and appear only once in the game. Bosses are harder to kill than the "normal" elite mob of the same level, and almost all bosses are immune to Crowd Control, though some may be susceptible in accordance with their intended mechanics (such as Roar in Karazhan for example).
- https://wowpedia.fandom.com/wiki/Crowd_control
> All raid bosses are immune to all forms of crowd control. Elite mobs may or may not have high resistance to, or be immune to, specific CC that would normally work on their non-elite counterparts.

### Historic Wowpedia (around Summer 2010 during WotLK)
... suggests that all bosses are immune to CC:
- https://wowpedia.fandom.com/wiki/Boss?oldid=2341203
> A common characteristic for all bosses is that they have a unique name and appear only once in the game. Bosses are harder to kill than the "normal" elite mob of the same level, and all bosses are immune to Crowd Control.
- https://wowpedia.fandom.com/wiki/Crowd_control?oldid=2319336
> All instance bosses are immune to crowd control. Assuming a target is not completely immune, Elite mobs may or may not have high resistance to specific CC that would normally work quite well on their non-elite counterparts.

### Verdan the Everling (current as well as historic around Summer 2010 during WotLK)
... suggests that this boss is **not immune to CC**.
- https://wowpedia.fandom.com/wiki/Verdan_the_Everliving
- https://wowpedia.fandom.com/wiki/Verdan_the_Everliving?oldid=2297669
> The most common tactic used is having someone kite him. Shamans are good for kiting Verdan using  [Frost Shock] to keep aggro and run around while keeping an  [Earthbind Totem] down.

Anyway, I'm going to close this as invalid. Mainly because this report is not specific enough.
But if you have (historic) evidence that the current implementation of a particular boss in AC is incorrect, feel free to open a new report.
