### ISSUE TITLE
Troll's raptor mount doesn't leave footprints

### ISSUE THREAD

**Issue by lovelord83** [chromiecraft/chromiecraft#1240]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Troll's raptor mount doesn't leave footprints on any substrate (sand, ice, etc...)

### Expected Blizzlike Behaviour

Should leave footprints while running/walking, like other mounts

### Steps to reproduce the problem

As Troll, use your main mount (raptor) to walk on substrates that should leave footprints (sand, ice, etc...)
As you can see no footprints will be left at all
No problem with other mounts.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I tried reproducing this with 7 raptor mounts (3 apprentice, 3 journeyman, and the PVP raptor) on both sand and snow on two characters (one a troll, one not) and footprints worked every time. 

![WoWScrnShot_072021_000332](https://user-images.githubusercontent.com/81782124/126182170-5a20af51-07f2-4fb7-916f-a24767cbffac.jpg)
![WoWScrnShot_072021_003048](https://user-images.githubusercontent.com/81782124/126182182-5ce84876-b469-4105-aa8a-8d17c9fbf51e.jpg)

In any case, I'm not sure footprints are even handled by the AC server rather than the client, as they look like they could be a graphical option related to ground clutter or something (although that's just a guess.) So if there is an error with troll mount footprints, it might be in a local client file, and thus unfixable by the AC project.

I think to get further with this, we'd want exact details on which raptor mount you were using and where (map and coordinates) you tried it.

**Comment by Ziedge** [comment]
If that can help, I'm not having the issue (and I'm using HD models and textures packs + frFR patch on a client I found and used on warmane back in a few month before Chromie)

https://user-images.githubusercontent.com/82708448/126196232-8e86d52a-e0df-4fda-a1aa-6b1001c3b1ae.mp4

**Comment by lovelord83** [comment]
I'm using customized client HD Patches ([https://stygianthebest.github.io/projects/server-stygiancoreclient/](url)) but this problem was present even before using them. Tried to disable all patches and addons, but problem still persist, but not when I'm on my feet. This is a sample video recording from my UI, even if problem is not server related (sorry, didn't know that) any advice will be appreciated before closing ticket:

https://youtu.be/wsA58r4fxgM

**Comment by lovelord83** [comment]
Just noticed that even pet do the same...

**Comment by lovelord83** [comment]
Ok autosolved clearing cache and disabling this patch from the link above. It seems that the layer is shared, so this strange behaviour happens, but only using the Raptor... weird. In any case pet doesn't show footprints, don't know if it does it before or not, cannot remember. Details are maxed up, even terrain clutter and all the staff on video settings.

Incriminated patch:

PATCH-J.MPQ - HD Druids + Stag Travel Form By Leeviathan
