### ISSUE TITLE
Mage freeze effects can cause enemies to stop moving indefinitely.

### ISSUE THREAD

**Issue by CameronWoof** [chromiecraft/chromiecraft#125]
##### SMALL DESCRIPTION:

Enemies frozen by Frost Nova or the Frostbite talent become unresponsive in certain situations.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once the freeze effect wears off, the enemy should continue moving towards the player to attack them.

##### CURRENT BEHAVIOUR:

Under the right (easily repeatable) circumstances, the enemies instead stand still long after the freeze effect is removed, allowing you to kill them without them ever attempting to close the distance again. If they are an enemy type that flees at low health, they will do so as normal when reduced to the proper threshold. 

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Stand still. Do not rotate your character or move from your starting position. 
Step 2: Get into combat with an enemy. They *must* be running towards you--beginning combat by freezing them will not work.
Step 3: Freeze the enemy before they close into melee range with you.

If you've done the above correctly, they should remain motionless even after the freeze effect ends or is removed. You can cast spells, attack with your wand, or do pretty much anything *as long as you do not move or rotate your character*. I'm able to reproduce this consistently, and it seems to apply to all mobs--animals, humanoids, constructs, you name it. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
Cannot reproduce. Neither on ChromieCraft nor Current AC.

**Comment by CameronWoof** [comment]
It should be a 100% reproduction case, it's very reliable. Stand completely still (do not move or rotate your character), engage with Frostbolt (any rank), and freeze the incoming enemy with either the Frostbite Talent or Frost Nova (possibly Rank 1-specific?) before they get close enough to hit you in melee. 

My uninformed *guess* is that this works as long as you don't do anything between the time you freeze them and the time the freeze effect wears off that requires the enemy to recalculate its pathing. Don't alter your facing or position, and this should work legitimately every single time. Even against multiple enemies.

**Comment by necropola** [comment]
**Correction**. I can reproduce it, but some important detail was missing. The **Frost Nova** **must be broken by doing damage to it** while not moving since it was applied. (Which rarely happens in normal game paly as a Frost Mage, I'd say).

If the Frost Nova wears off without doing damage to it or after doing damge to it, it does not trigger, i. e. the **damage needs to break the Frost Nova it and you must not move since teh Frost Nova was applied.**
   
Anyway, I could reproduce it on current AC using [Frost Nova (Rank 1)](https://wotlkdb.com/?spell=122) as a Mage at level 18 and at level 12 (just to make sure, it does not depend on the level).

**Comment by Stifler82** [comment]
@necropola
Good work Necropola, well explained and detailed.

even if I think you got confused with the "Camera" story, I suppose you were referring to **"don't turn the camera with the right mouse button"** because that button also **affects the movement of the character as well as the camera**, while if you turn **ONLY the camera**, with the left mouse button, that action shouldn't affect anything..

Anyway, great job, keep it up..

**Comment by Hemingway1970** [comment]
This will also occasionally happen with Hunter Freezing traps.
