### ISSUE TITLE
Floating Giant Clam in Ghostlands

### ISSUE THREAD

**Issue by Cosmic-Cocoa** [chromiecraft/chromiecraft#129]
##### ISSUE: FACTION SIDE:

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

GameObject: [Giant Clam](https://wowgaming.altervista.org/aowow/?object=19017)
Zone: [Ghostlands](https://wowgaming.altervista.org/aowow/?zone=3433)

Found a Giant Clam floating in the middle of the water.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Clams should appear on the ocean floor.

##### CURRENT BEHAVIOUR:

The giant clam located at 52.68, 24.84 (coords from TomTom) is in the middle of the water rather than on the ocean floor. I swam under it for the screenshot.
![Floating Giant Clam_Ghostlands](https://user-images.githubusercontent.com/78349628/110089917-4d2a1980-7d5c-11eb-8b3b-bb66ec7277e7.png)

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1. Teleport to Windrunner Spire. 
Step 2. Jump into the water and swim south.
Step 3. See if the Giant Clam spawned there is floating above the ocean floor. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment]
Funny idea: if the game had been advanced enough, the clam could have mimicked real life by fleeing from players and possible NPC creatures trying to harm it (take its contents). 😄

**Comment by Stifler82** [comment]
@Cosmic-Cocoa @illfated 

You know I've been thinking about this bug, and I had an intuition that **(however it is not necessarily the way I guessed)**, but it might not be a bug, but an intentional thing. As it could be that **(to give a sense of reality)** the shell of the Clam could be hermetically sealed and contain air inside it **that allows it to float**, (a bit like the concept of ships, which are tons of metal floating in water).

Then, maybe it's a bug and my example has nothing to do with it, but I would propose to leave it as it is.

If you want I can fix it and place it on the seabed, but I like the idea of the air bubble inside it, in my opinion it makes it more authentic, what do you think?

**Comment by illfated** [comment]
Thank you for following up on the idea and suggesting that it could be intentional. However, I am fairly certain that Blizzard did not go that far, and it is more likely that the clam spawn location is supposed to be on the sea floor.

I vote for a Z height correction, as long as the X + Y coordinates are correct.

**Comment by Stifler82** [comment]
Fixed!
-
![WoWScrnShot_030821_140747](https://user-images.githubusercontent.com/1884642/110332018-b9847180-8017-11eb-857c-2345a767199c.jpg)

**Comment by illfated** [comment]
(ref. https://github.com/azerothcore/azerothcore-wotlk/pull/4761)
