### ISSUE TITLE
Option to get a new hearthstone not available after deleting

### ISSUE THREAD

**Issue by jeskej** [chromiecraft/chromiecraft#1299]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

After deleting hearthstone, the innkeeper does not offer the option to get a new one.

### Expected Blizzlike Behaviour

Any innkeeper should provide an option to give you a new hearthstone

### Source

https://us.battle.net/support/en/article/8384

### Steps to reproduce the problem

1.  Delete hearthstone
2.  Talk to innkeeper, there is no dialog option to get a new hearthstone

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Just checked this, and innkeepers will give you a new hearthstone if you select the dialog option "Make this inn your home."

![WoWScrnShot_072821_221558](https://user-images.githubusercontent.com/81782124/127324525-2c569429-d5e4-4d27-bee9-07b4ad4463a8.jpg)

Checking contemporary sources shows this is expected behaviour. For example, Wowpedia, in the last Wrath-era entry on Hearthstones, says "You can destroy the Hearthstone if you so desire. To get a new one, speak with any innkeeper and set the Bind point"  (https://wowpedia.fandom.com/wiki/Hearthstone?oldid=2372834) - which of course is what you're doing when you make the inn your home. So the AC innkeeper behaviour is correct. Closing this issue accordingly.
