### ISSUE TITLE
Chillwind Ravager incorrect ability set

### ISSUE THREAD

**Issue by Shineslippers** [chromiecraft/chromiecraft#1338]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

[Chillwind Ravager](https://wowgaming.altervista.org/aowow/?npc=7449) have ability [Chill](https://wowgaming.altervista.org/aowow/?spell=28547).

### Expected Blizzlike Behaviour

Chillwind Ravager should have only one ability Enrage.

### Source

Regardless of everything. Common NPC(57-59 levels) have unique ability what can oneshot even 60 level player.

1) [Youtube1](https://youtu.be/BZ29SxutQVA?t=144), [Youtube2](https://youtu.be/ZnWtI-okG3c?t=44)
2) [Wowhead](https://tbc.wowhead.com/npc=7449/chillwind-ravager)

### Steps to reproduce the problem

Fight with Chillwind Ravager to check out spells set.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
Hello, and thanks for the report. You're actually have some conflicting information. Using the links you provided, and in the you tube videos. I believe the chillwind ravager does indeed use a chill spell. But you claim it shouldn't, it should only have enrage.
https://wowgaming.altervista.org/aowow/?npc=7449#abilities
https://wowgaming.altervista.org/aowow/?spell=28547#used-by-npc
[Youtube1 3:23](https://youtu.be/BZ29SxutQVA?t=202) he gets a 5 second chill effect 
![image](https://user-images.githubusercontent.com/68164076/128110366-139ff8bf-22a5-4018-927b-fa6c53e2d170.png)
[Youtube2 :46](https://youtu.be/ZnWtI-okG3c?t=46) seconds he gets a 5 second chill effect
Additional sources showing Chill as part of the Chillwind Ravager's abilities [Classic wowhead](https://classic.wowhead.com/npc=7449/chillwind-ravager#abilities) [ClassicDB](https://classicdb.ch/?npc=7449#abilities) [Wow-freakz](https://www.wow-freakz.com/npc_finder.php?npc=7449&name=chillwind-ravager) really the only one that doesn't list it as it having that ability is TBC wowhead, which is odd.

Going into the game and attacking them, I believe they are just using the wrong chill spell. What they do use is something along the lines of blizzard. However, it did no damage to me, but did give me the chilled effect- slowing movement for about 8 seconds if I stood in it. If anything this is better for the player, as according to the videos it's a hard 5 seconds of slowed movement with no ecsaping it.  This way you can run out after 2 seconds.
![image](https://user-images.githubusercontent.com/68164076/128114045-5792dd9f-d99d-4514-adcd-322b908fa622.png)


Personally, I believe all of the links above are incorrect. As you have stated, using [Chill](https://wowgaming.altervista.org/aowow/?npc=7449) would one shot a level 60. I think it might have been a typo, or somebody forgot what the spell was called, that was why [Classic wowhead](https://classic.wowhead.com/npc=7449/chillwind-ravager#abilities) put down every chilled effect known in the game for this mob's ability. Maybe someone wanted to correct it, but wasn't exactly sure which one it was.

I believe instead of Chill, they should be the spell [CHILLED](https://classic.wowhead.com/spell=15850/chilled) (Spell ID 15850). It matches the tooltip, and debuff icon in the videos, causes no damage, and chills for 5 seconds. 
![image](https://user-images.githubusercontent.com/68164076/128114517-8a454b75-00d4-487a-adc7-71e849af6234.png)

**Comment by Shineslippers** [comment]
Yes, you right. They just using wrong chill spell. Will doI was incorrect when said there is shouldn't be chill. 
I beleive to tbc wowhead. But my point the same. This ability is actually a blizzard and it's oneshot players.
![WoWScrnShot_080421_091202](https://user-images.githubusercontent.com/85256266/128131556-aa57c534-e904-46f3-bfd5-2ba31cb1cc51.jpg)
