### ISSUE TITLE
Willix the Importer

### ISSUE THREAD

**Issue by Narixel** [chromiecraft/chromiecraft#135]
ISSUE: FACTION SIDE:
Alliance
CONTENT PHASE:
Level 22
SMALL DESCRIPTION:
After escorting Willix the Importer,he leaves before I get the chance to turn in the quest. https://classic.wowhead.com/npc=4508/willix-the-importer
EXPECTED BLIZZLIKE BEHAVIOUR:
He should wait there for you to turn in the quest and not leave.
CURRENT BEHAVIOUR:Willix the Importer leaves after a few second escort finished making you unable to turn in the quest.
STEPS TO REPRODUCE THE PROBLEM:

Step 1 Take Willix the Importer quest from Razorfen Kraul https://classic.wowhead.com/quest=1144/willix-the-importer
Step 2 Escort him until exit
Step 3 He leaves after a few seconds at the exit.
AC HASH/COMMIT:

chromiecraft/azerothcore-wotlk@c2f274e
OPERATING SYSTEM:

Ubuntu 20.04
MODULES:

    mod-cfbg
    mod-duel-reset
    mod-desertion-warnings
    mod-ah-bot

OTHER CUSTOMIZATIONS:

None.
SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@Narixel 

Kindly fill the form correctly next time, we have designed this type of form to have an easy reading of the Report, this time I will not close your report, but since I have just informed you on how to do it next time, if you repeat same error, I will immediately close the report as "Invalid".

**Comment by Stifler82** [comment]
@Narixel
I just checked this "Bug", and there is no Bug.
In addition, I don't think "A few seconds" have passed as you said..
So, i will close it..

Obviously, everything is relative, because if for you 1 minute equals "a few seconds", then yes, a few seconds have passed..

**Video Test:** [Willix the Importer](https://youtu.be/70CFGxMfppw)

**Comment by TronusGames** [comment]
Hello, the bug still persist when Willix is completely escorted at the entrance of the dungeon. Then if anyone finish the quest with him, the person will get the quest completed, but Willix will move fastly inside walls to i do not know where, so the others cannot complete the quest. This does not happen always, in 2 escort runs it happened 1 time.

**Comment by Stifler82** [comment]
> Hello, the bug still persist when Willix is completely escorted at the entrance of the dungeon. Then if anyone finish the quest with him, the person will get the quest completed, but Willix will move fastly inside walls to i do not know where, so the others cannot complete the quest. This does not happen always, in 2 escort runs it happened 1 time.

@TronusGames 
Ok, I'll take a look at it..
