### ISSUE TITLE
[Azuremyst Isle] Gurf's Dignity can't be accepted until turning in a previous quest

### ISSUE THREAD

**Issue by Gadixsp** [chromiecraft/chromiecraft#1396]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The quest item [Gurf's Dignity](https://wowgaming.altervista.org/aowow/?item=23850) drops as expected, but the [associated quest](https://wowgaming.altervista.org/aowow/?quest=9564) cannot be accepted until completing [Murlocs... Why here? Why now?](https://wowgaming.altervista.org/aowow/?quest=9562).

### Expected Blizzlike Behaviour

It's required that you have the quest [Murlocs... Why here? Why now?](https://wowgaming.altervista.org/aowow/?quest=9562) for the quest item to drop from [Murgurgula](https://wowgaming.altervista.org/aowow/?npc=17475), but you need not complete the previous quest to start the quest from the item.

### Source

[YouTube video of the quest from TBC Classic](https://www.youtube.com/watch?v=z4xgMvrQ-lo).

The Murlocs... quest is visible in the tracker and not yet completed. The player loots the quest item and immediately accepts the quest.

### Steps to reproduce the problem

1. Complete the prerequisites and pick up the quest [Murlocs... Why here? Why now?](https://wowgaming.altervista.org/aowow/?quest=9562) with an Alliance character level 7 or above -- the quest chain starts with [Learning the Language](https://wowgaming.altervista.org/aowow/?quest=9538)
2. Kill [Murgurgula](https://wowgaming.altervista.org/aowow/?npc=17475) along the northwest coast
3. Attempt to accept the quest before turning in [Murlocs... Why here? Why now?](https://wowgaming.altervista.org/aowow/?quest=9562)

### Extra Notes

I realize this was posted before but closed for lack of evidence. I wasn't sure of the proper procedure in this case so I made a new report, but I would be happy to close it and append this evidence in a comment to the closed report if that's better.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
I can't say why it was closed. After looking myself for something from 3.3.5 or earlier I found this https://tbc.wowhead.com/quest=9564/gurfs-dignity#comments 
Top comment by Darter on 2008/01/30 Patch 2.3.3 `I have done this on my NE priest so yes non-Draenei can do this quest. You need to do the Firbolg quest chains first to learn the language`
Which is the exact same link that person posted. That looks pretty good to me. 

I believe the bug is that the item will drop if you haven't completed the totem quest line. Killing him with a night elf who did zero quests, I was able to see it drop and I should not. Source is the comments in the link above. A night elf tried killing multiple times with no drop, once the murlock quest was accepted, it dropped immediately 

In any case, I can confirm this. It should only drop if you have the murloc quest, not before, and you should be able to accept it as soon as you loot it. 

I'll toss a link to the other issue as well https://github.com/chromiecraft/chromiecraft/issues/397
