### ISSUE TITLE
Underwater NPCs can be made to not defend themselves

### ISSUE THREAD

**Issue by eTzmNcbkrng** [chromiecraft/chromiecraft#154]
##### ISSUE: 
FACTION SIDE:

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

NPCs do not attack in water under specific circumstances

I found this bug while doing a particular quest to get a few items from killing particular NPCs, but I don't think it is unique to these NPCs or this quest.

Quest: [A Solvent Spirit](https://wotlkdb.com/?quest=818)
NPC1: [Makrura Clacker](https://wotlkdb.com/?npc=3103)
NPC2: [Makrura Elder](https://wotlkdb.com/?npc=3141)
NPC3: [Makrura Shellhide](https://wotlkdb.com/?npc=3104)
NPC4: [Makrura Snapclaw](https://wotlkdb.com/?npc=3105)
NPC5: [Surf Crawler](https://wotlkdb.com/?npc=3107)
NPC6: [Pygmy Surf Crawler](https://wotlkdb.com/?npc=3106)

If you engage combat with these NPCs in a specific way, they will not attack you.

Edit: I was able to continue to reproduce this bug off the coast of Echo Isles but strangely not as consistently and I couldn't figure out what was different.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Attacking the NPC should cause it to move towards you and deal damage to you

##### CURRENT BEHAVIOUR:

NPCs engaged in a specific way will swim to the ocean floor directly below the player and not attack him/her

##### STEPS TO REPRODUCE THE PROBLEM:

This was performed on a L8 Orc Warlock

Step 1 Find an NPC under water
Step 2 Swim to the surface (so that your breath bar is NOT going down)
Step 3 Engage the NPC with a ranged attack 
Step 4 NPC will swim to the ocean floor directly below the player and will not swim up into melee range to defend itself.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Cosmic-Cocoa** [comment]
I also encountered this while doing quests in Durotar and have had it on the backburner to test elsewhere before making a report. I took a couple screenshots while the NPCs were chilling on the ocean floor as I pelted them with throwing knives.

![Mob Pathing When Swimming_Makrura_in_Durotar](https://user-images.githubusercontent.com/78349628/110222275-9f6f5580-7e96-11eb-823e-2aad9cd2c3c4.png)

![Mob Pathing When Swimming_Pygmy Surf Crawler_in_Durotar](https://user-images.githubusercontent.com/78349628/110222276-a39b7300-7e96-11eb-962d-be435c33c48c.png)

In addition to the notes for reproduction above, I would also mention that when I was testing this I noticed it worked best in *deep* water. Where the water was relatively shallow, the mobs would come to melee and attack me. Also, when they are at the bottom of the ocean floor they will attack the player if the player breaks the surface of the water (enough to have a breath bar).

**Comment by Stifler82** [comment]
@eTzmNcbkrng @Cosmic-Cocoa 

I just tell you that I got a headache just reading what you wrote, because after 100 thousand kilometers of text, and screenshots that should prove something, all I have grabbed is that according to you there is an interaction problem between the NPCs in the water and the character attacking them, but I still don't understand what the problem is, so if you can explain how the people of this planet do it would be great, thank you.

**Comment by Cosmic-Cocoa** [comment]
@Stifler82 So, I would explain it this way...

When you swim at the top of the water (no breath bar) and attack a mob that is in deep water with a ranged attack... That mob will swim to directly below you at the bottom of the ocean floor. It then just sits there, out of range to attack you, and you can burn it from range without being damaged at all.

**Comment by Cosmic-Cocoa** [comment]
@Stifler82 Also, if you'd like, I can swim out to where I experienced this and grab a screenshot with coordinates for you (I took the originals before I downloaded TomTom for that other bugged mob).

**Comment by Stifler82** [comment]
So..
I initially confirmed it as a Bug because I didn't really realize the entity of the problem.
But it's not a bug, actually I would call it a Fix too **"picky"**

Basically it all depends on the type of "aquatic" NPC you meet, because there are those who have an "InhabitType" (Water).
Then there are those that have "InhabitType" (Ground and Water).
Those with the double "InhabitType" are able to attack in both Water and Ground, while those with the "InhabitType" Water can only attack if you are (Totally) submerged underwater.

So when the Character is with "his head" out of the water the NPC with the double "InhabitType" goes into conflict and does not know how to behave because the Fix demands that you are totally underwater or totally out of the water. .
Actually this Fix should be slightly improved, but for the moment I suggest you attack the NPCs with double "InhabitType" or only out of the water or only in the water, this is a Fix that we will improve later, for the moment I close and I will consider the Report as invalid.

**In this video I show how the dynamics of the Fix works**
**Video Test:** [Underwater NPCs](https://youtu.be/Jg8CRE_t_Do)

**Comment by illfated** [comment]
Also, please remember that this issue is a lot easier to replicate as a female troll player character, because that character type is quite tall and therefore has its body center slightly higher up than most other genders & races (maybe Tauren & Draenei male characters also share that type of issue).

**Comment by Stifler82** [comment]
Do not worry, this "problem" will not end up in oblivion, but in short... it is not a **"serious" bug** because the problem does not really arise, **just kill NPCs underwater** or **from the beach**, and you can play the same..
So it's not a very serious thing..
As high as a Character can be, I mean.. the sea is deep enough even for a Troll or a Tauren.. 😅

**Comment by eTzmNcbkrng** [comment]
Why is this invalid?
Is it working as intended?
No.
So it’s a bug - cause is irrelevant.

**Comment by illfated** [comment]
@eTzmNcbkrng : One of the bigger issues behind that specific problem is when to make creatures Evade. If you lower the boundary for Evade to happen, you will also get a lot more invalid situation where creatures Evade too easy/too early, and reset their HP so you need to start the fight all over again. Not sure if you prefer that situation over the one you have got now.
