### ISSUE TITLE
[Westfall] Unreachable Tin Vein node

### ISSUE THREAD

**Issue by Hihilist** [chromiecraft/chromiecraft#1564]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

In Westfall, on coords 30 46, there is Tin Vein node that cannot be reached.
![IMG 1](https://user-images.githubusercontent.com/71841180/131201325-499a4752-7ac1-4273-a241-4e66788f6eea.jpg)
![IMG 2](https://user-images.githubusercontent.com/71841180/131201329-1c825212-e12f-4fd9-a2c6-54ba03093ab3.jpg)

### Expected Blizzlike Behaviour

Mining nodes should not spawn in the areas unreachable for the players like inside walls, trees, in the air or below the ground level.

### Steps to reproduce the problem

1. For better results have a character with learnt Minning profession, 'Find Minerals' spell and set the tracking to 'Find Minerals'
2. Fly to Westfall and go to coords 30 46
3. Try to locate the Tin Vein node that should be on the same level of ground you are standing

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. I went and had a look at this area, and there's a large cave system right under the ground where you were standing, which is where all the tin and copper nodes on your map are spawned. As far as I could tell, they were all accessible once you headed south to the cave entrance. 

Now there is an error here, in that there are far too many ore nodes active in the cave right now, but that's due to the current lack of node pooling in Westfall, so everything is spawning at once. However, this is a known issue that someone is working on.

**Comment by Hihilist** [comment]
(Not sure if it is allowed to comment on closed bugs in case of disagreement so please let me know for the future cases).
Hello,
I think you are missing one detail - if the reported node was in the cave, it would be slightly greyed out like the surrounding ones, but it is bright like the one on the right, which means it is on the ground level where the player is standing.
To be extra sure I haven't missed it, I went there again, got a screenshot before digging and then another screenshot after I dug all the near nodes and still reported node couldn't be found. Please refer to the attachments:
![IMG 1](https://user-images.githubusercontent.com/71841180/131233206-1a088749-52d3-4dd8-a502-cfefd4a1c033.jpg)
![IMG 2](https://user-images.githubusercontent.com/71841180/131233207-19d7ce67-f3e8-42d0-8a10-d009a610d522.jpg)

**Comment by Azcobu** [comment]
Heh, you're perfectly welcome to comment on a closed issue, especially if you believe something has been overlooked and have some evidence to show it.

I went back into the cave and cleared out all the nodes, but when I went back up outside, there weren't any untouched nodes showing on my radar. So this mystery tin node apparently wasn't spawned for me. So I tried another approach, which is to use the `.gobject near` command, which you have access to as well. `.gobject near` by itself will find all game objects (like ore nodes) within 10 yards, and you can put a number X after it to search for all nodes in X yards. I tried `.gobject near 200` and made a list of all tin nodes in the area, and then went and teleported to all of them.

- 63489 - in cave - 30.7, 46.6
- 63486 - in cave, higher up cave wall - 30.0, 46.5
- 5504 - spawned, cave floor - 29.2, 46.0
- 42667 - cave floor - 29.2, 45.6
- 30999 - spawned, in cave, 30.3, 45.2
- 31032 - spawned, cave entrance, 31.6, 45.1
- 30983 - rear cave floor - 29.8, 50.6
- 150143 - odd position, but coords too far out - 28.8, 50.9

The first two seem most likely to be the culprits based on coords, but both are still within the cave system. If I had to guess, 63486 was quite high up the cave wall, so perhaps it was showing as on your level because of that. However, as nothing was spawned there when I checked it, couldn't say for sure. Here's what it looked like when I ported to it and where it was inside the cave:

![WoWScrnShot_082921_111237](https://user-images.githubusercontent.com/81782124/131240649-3bb81329-7172-40f6-b9a9-c651153f625e.jpg)
![WoWScrnShot_082921_154251](https://user-images.githubusercontent.com/81782124/131240651-3de6470c-b5ec-4a52-82c1-85e8f938e1c6.jpg)

Anyway, as you have access to the `.gobject near` command yourself, feel free to see if you can identify the node ID for the node if you spot it again.

**Comment by Hihilist** [comment]
Managed to run my own server, and you were right it is a 63486 node but when it is spawned, it cannot be reached due to being in a solid wall. Standing on the ground where it should be and using `.gobject move 63486` places it correctly on the ground level.
Please refer to screenshots:
![IMG1](https://user-images.githubusercontent.com/71841180/131266670-828ff97f-7b47-4dc4-bdb7-a4a5a4f0d436.jpg)
![IMG2](https://user-images.githubusercontent.com/71841180/131266672-6e80b33c-f490-4e63-8637-4fd26b46f168.jpg)

**Comment by Azcobu** [comment]
Grats on setting up your own server. Node 63486 is still not spawning on my server, but if you say it can't be reached through the cave wall, then I'd be happy to nudge it. I disagree about moving it straight up though - the node is right on the cave wall, so shifting it a little bit sideways so it's visible from inside the cave seems more Blizz-like to me. This also preserves consistency - there are lots of other nodes in the cave, but many fewer ore nodes just sitting in the middle of grassy plains.

To fix this, we will need to write a database query to change the spawn coordinates for the node - unfortunately, the `.gobject move` command is purely local to your AC server and won't fix this node for anyone else. Also, the command will move anything to anywhere you put it (you could probably move chunks of Orgrimmar to Westfall with some patience) so doesn't show anything about where an object should be.

Incidentally, now you have your own AC server, you'd be welcome to comment on or test other issues listed in the issue tracker as well.
