### ISSUE TITLE
Quest: Beer Basted Boar Ribs has an incorrect prerequisite

### ISSUE THREAD

**Issue by CameronWoof** [chromiecraft/chromiecraft#158]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Quest: [Beer Basted Boar Ribs](https://wotlkdb.com/?quest=384)
NPC_Start: [Ragnar Thunderbrew](https://wotlkdb.com/?npc=1267)
NPC_End: [Ragnar Thunderbrew](https://wotlkdb.com/?npc=1267)

EDIT: According to a below comment, the issue is that the quest incorrectly requires the Cooking skill to receive; it should not.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should offer the quest when you arrive in Kharanos.

##### CURRENT BEHAVIOUR:

He does not.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Reach Kharanos at or around level 6.
Step 2: Go to Ragnar, who does not offer the quest.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by illfated** [comment]
It is very likely that you have forgotten to learn the Cooking skill, which is a requirement for the quest.

Beer Basted Boar Ribs: https://wotlkdb.com/?quest=384/beer-basted-boar-ribs


**Quick Facts**

- Level: 7
- Requires Level 5
- Side: Alliance
- Races: Alliance
- Profession:  **Cooking (1)**
- Start: Ragnar Thunderbrew
- End: Ragnar Thunderbrew
- Sharable
- Difficulty: **5**  10  12

This has sometimes been reported in other cores with the same incorrect assumption; the quest should _always_ be available (and the reporting user forgetting that it is a _Cooking_ quest).

**Comment by CameronWoof** [comment]
Then the issue is that the quest incorrectly requires you to learn Cooking. The original quest never did; like similar quests in other low-level zones, the quest is an advertisement for the Cooking skill. You need not learn the Cooking skill to accept it.

**Comment by illfated** [comment]
Please provide some kind of proof that the quest did not require cooking before on retail.
Links to wowhead comments, or Wowpedia and WowWiki pages should be just fine. 

I do not remember ever seeing the quest available without the cooking skill.
Then again, back when I played on retail in 2005-2010, I did not play as much on the Alliance side as the Horde side.

**Comment by CameronWoof** [comment]
The linked WoWhead page from Classic has no comments explaining that it requires the cooking skill. [The Gamepedia page](https://wow.gamepedia.com/Beer_Basted_Boar_Ribs_(quest)) mentions specifically in the Notes section that the Cooking skill isn't required.

**Comment by illfated** [comment]
Well, at least you do seem to have a point. I have noticed a discrepancy while trying to research this myself.

Compare the following:
- https://www.wowhead.com/quest=384/beer-basted-boar-ribs
- https://classic.wowhead.com/quest=384/beer-basted-boar-ribs

The Wowhead Classic page shows that cooking is required.
The Live page does not require cooking (retail live).
The Classic page says that this quest does not count for Loremaster.
The Wowhead Live page says that the quest is a Loremaster quest.

Your reference to WowWiki/WowPedia saying that Cooking is not required:
- https://wowwiki-archive.fandom.com/wiki/Quest:Beer_Basted_Boar_Ribs#Notes
- https://wow.gamepedia.com/Beer_Basted_Boar_Ribs_(quest)#Notes

Wayback Machine (web.archive.org):
- http://web.archive.org/web/20100408220928/https://www.wowhead.com/quest=384 (Quick Facts missing)
- http://web.archive.org/web/20101008023519/http://www.wowhead.com:80/quest=384 (Quick Facts present)
(both pages above stem from before Cataclysm/patch 4.0.3a)

**Quick Facts**

Level: 7
Requires level 5
Side: Alliance
Start: Ragnar Thunderbrew
End: Ragnar Thunderbrew
Sharable
Difficulty: 5  10  13
Added in patch 1.11.1

Could be questionable information, though, seeing that the quest description says, among other things, the following:
"This quest starts and ends in Dun Morogh **and has objectives in Stormwind City, Desolace, Wetlands and Duskwood**."

After Cataclysm (March 07, 2011):
- http://web.archive.org/web/20110307093408/http://www.wowhead.com:80/quest=384
(The number of required [Tender Boar Ribs] has been reduced from 6 to 4, but still no cooking requirement.)

Then again, there is this old TrinityCore quest change from 2012, https://github.com/TrinityCore/TrinityCore/issues/5198

> Core: https://github.com/TrinityCore/TrinityCore/commit/19f8cc26b9cae894469263125fdb5342fe7a264d +
> Database: TDB 45 + updates
> Addons: Auctionhouse Bot
> Tested Query: Yes
> 
> Hi all,
> 
> quest_template.id 384 - Beer Basted Boar Ribs has an unnecessary requirement skill 185 (Cooking). As of 3.3.5a cooking wasn't required to get this quest, as can be seen by leveling guides using the quest as standard quest (without needing cooking profession).
> 
> Suggested Fix:
> 
> ```sql
> -- Remove obsolete requirement 'cooking profession' from quest 'Beer Basted Boar Ribs'
> UPDATE `quest_template` SET `RequiredSkillId`=0, `RequiredSkillPoints`=0, `ZoneOrSort`=1 WHERE `Id`=384;
> ```
> 
> Edited to also update ZoneOrSort and RequiredSkillPoints for completeness.
> Edited to conform to [http://www.trinitycore.org/f/topic/2588-sql-guidelines](http://www.trinitycore.org/f/topic/2588-sql-guidelines/)
> 
> tifkat

( See also the discussion in https://github.com/TrinityCore/TrinityCore/commit/62b1d4b8e13f35688fae7cc212699a86033f4887. )

So yes, I agree with you on the point that Cooking should not be required, because there is no cooking involved in the quest itself, only if you want to be able to use the Recipe item. Normally, without cooking, you would be able to sell it in the Auction House (AH) or send it to one of your alt characters.

Using the Wayback Machine (web.archive.org), I have tried to locate the date where the Cooking requirement was introduced and added to the Quick Facts section on Wowhead, but it has not shown up in my page views up to and including http://web.archive.org/web/20150328020404/http://www.wowhead.com:80/quest=384 (2015-03-28). This may just be an academic detail, but it would be nice to know when the requirement was introduced (and removed?) on retail.

**Comment by CameronWoof** [comment]
This is a very, very detailed breakdown. Before I say anything else, I want to make absolutely sure that you know: this is very impressive, and I appreciate the effort you went through to collate all of this information.

To my memory, this quest and others like it, such as [Recipe of the Kaldorei](https://classic.wowhead.com/quest=4161/recipe-of-the-kaldorei#comments) never required Cooking to accept them (I started playing, I believe, during the Wrath pre-patch), but even in the comments of the Recipe of the Kaldorei quest on Classic Wowhead, we see:

> By Ilgaten (1,894 – 9·10) on 2019/09/01 (Classic)  
Unlike other lowbie quests in Westfall and Dun Morogh that offer cooking recipes as a reward, this one DOES REQUIRE you to train for cooking. It appears as soon as you spend your one silver to train, so no need to level cooking. (I wanted this recipe for an alt.)

So I'm less confident now. I think that both of these quests are very good for their respective zones' flow, and they are very similar in structure to later quests that definitely do not require cooking (Redridge Goulash, Westfall Stew, etc.) Hiding them behind training cooking seems an odd choice to me, and apparently Blizzard agreed at some point.

**Comment by illfated** [comment]
Fair enough, I don't feel confident enough what the correct state of all the recipe quests right after leaving the starter area should be.

On one hand, checking WoW Classic now could indicate how quests should work, but on the other hand, some of the details have been corrected in modern Classic, compared to their original Vanilla counterparts.

**Comment by Helias** [comment]
Thank you both guys to investigate deeply this.
Really thank you @illfated.

I think that this quest requires Cooking, if we have proof of the opposite we could re-open this issue.
@CameronWoof  feel free to comment here or reopen the issue if you know for sure that this quest should not require Cooking, we want to make this right, but we need to be sure :wink: .
