### ISSUE TITLE
Life Tap incorrect tooltip

### ISSUE THREAD

**Issue by ghost** [chromiecraft/chromiecraft#1587]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Life Tap's tooltip shows incorrect numbers. However, the spell is behaving as intended

### Expected Blizzlike Behaviour

Should show proper life to mana conversion in the tooltip

### Steps to reproduce the problem

Look at Life Tap Rank 1 Tooltip

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Arch Linux on linux-zen kernel

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
https://wotlkdb.com/?spell=1454

What is written here, number is correct

27 + 175 = 202 * 1.5 = 303

![Screenshot_20210831_094507](https://user-images.githubusercontent.com/14080516/131446171-35358766-292b-4f0e-bcf2-97bc61806fab.png)

**Comment by jamadaha** [comment]
I think the issue is more in terms of actual health cost / mana gain. Casting rank 1 life tap, seen below, should take over 200 health. But casting it, I lose something like 20/30 health. While gaining 27 mana, as opposed to the claimed 40 mana.
![image](https://user-images.githubusercontent.com/53914190/132093327-dc1f39f9-086f-4fd1-95a9-431a22b6315b.png)
![image](https://user-images.githubusercontent.com/53914190/132093422-57f41b0e-f29a-4ae5-8cfe-51ad33d302e0.png)
![image](https://user-images.githubusercontent.com/53914190/132093429-586f6d1d-fa1d-462f-8669-3ad582012ef0.png)

**Comment by lineagedr** [comment]
@IntelligentQuantum ?

Patch 3.3.3 (2010-03-23): This spell no longer scales with spirit, and instead scales with spell power.
https://wowwiki-archive.fandom.com/wiki/Life_Tap

**Comment by Gultask** [comment]
I'm going to take another look at the spell values if I have the time. But tooltips are client-side and can't be fixed.

**Comment by The-GhostRider** [comment]
https://github.com/azerothcore/azerothcore-wotlk/files/5936262/patch-5.zip
This Patch fixes the tooltip, it's part of a Fix I made some time ago.
So I would say this solves the problem..
I close the post.



https://youtu.be/6uQlv-Li_eM
Here, there is an explanatory illustration of what I did in my Fix, if you have will and time to watch you can go and give alook.
P.S.
it's logical that if you skip parts of the video because you want to hurry and then you don't understand anything, it's not my fault 😁
I recommend viewing it at 1.5x

**Comment by The-GhostRider** [comment]
https://github.com/azerothcore/azerothcore-wotlk/discussions/4462
