### ISSUE TITLE
Item 2243 does not drop

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1646]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

it is not in any of the loot tables

### Expected Blizzlike Behaviour

it drops from at least 97 mobs (according to tbc database)

### Source

https://tbc.wowhead.com/item=2243/hand-of-edward-the-odd

### Steps to reproduce the problem

run the following query:
select creature_template.name, creature_loot_template.entry, creature_loot_template.chance from creature_loot_template join creature_template on creature_loot_template.Entry=creature_template.lootid where creature_loot_template.item="2243";
![image](https://user-images.githubusercontent.com/84640316/132250454-b16c4998-67db-4674-b25c-8a0b7c0ce0e4.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, if you check this item [here](https://wowgaming.altervista.org/aowow/?item=2243) you will find it drops from 162 NPCs. The reason why your SQL query isn't finding the item is because many items in AC are not dropped directly from the creature via the `creature_loot_template`, but are instead contained in `reference_loot_template` tables. These are pools of common loot shared across creatures of similar level range, and they contain many, if not most item drops in the game. Item 2243 is contained in reference_loot_template 24090, which is used by 162 NPCs. If you're interested, some queries to examine this part of the DB can be found [here](https://www.azerothcore.org/wiki/useful-sql#find-which-rlts-an-item-is-in).
