### ISSUE TITLE
Mudsprocket Flight Point doesn't show up

### ISSUE THREAD

**Issue by Orixim** [chromiecraft/chromiecraft#1676]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I was at Mudsprocket Fligth Point and I can fly away from there. When I click on it, it opens the map to select the target location, but Mudsprocket's location doesn't show up, only the lines representing the path away from it.
The big problem comes, when I'm in another Flight Point, since the Mudsprocket icon also doesn't show up, and since I can't hover it, I can't fly there.

### Expected Blizzlike Behaviour

It should work as any other Flight Point.

### Source

Experience

### Steps to reproduce the problem

1. Go to Mudsprocket's Flight Point;
2. Check that the map to select the target location does not contain the Mudsprocket's location icon;
3. Fly to another location;
4. On arrival, open that Flight Point and check that Mudsprocket's location icon does not show up and you can't target it (can't fly back).

### Extra Notes

This picture shows the Tanaris Flight Point when I arrived from Mudsprocket:

[Bug](https://ibb.co/Cw3sgQD)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by jamadaha** [comment]
I could not reproduce the bug.
This could be because of a couple of reasons, but the likely candidates are that you were using an addon — as can be seen in your attached picture — or that it's a client bug. 
The easy way to test this, would be for you to first delete your cache, then if that does not fix it, try disabling your addons.
If neither of those fix it, please write back, as it could then be a server-side bug.
![image](https://user-images.githubusercontent.com/53914190/132705948-8e059a18-4293-4986-a660-da9fd2090549.png)
![image](https://user-images.githubusercontent.com/53914190/132706104-8716214f-b174-4dc5-9ae1-714c01dd1bfa.png)
![image](https://user-images.githubusercontent.com/53914190/132706287-c82e9283-8712-43f0-b138-89a80591f2ff.png)

**Comment by VFaleiro** [comment]
Have this same problem every once in a while. A few notes:
- Only happened (to me) with goblin flight paths (mostly Ratchet and Mudsprocket), most of the time it happened I was trying to fly from Orgrimmar to Ratchet.
- Happened in another private server I played (unclear which Core they were running), but I played in quite a few other private servers (3 of them running Trinity) and none of them had that issue (I guess this hints it's a server-side issue).
- Can be solved with `/reload` or just relogging (I guess this hints it's a client-side issue).

**Comment by Orixim** [comment]
Well I did end up deleting cache folder and restarting the application a couple of times before I checked this again. It is showing correctly now. So, I don't know. Regardless, does not seem to be that important.

**Comment by temperrr** [comment]
Cannot reproduce indeed. If a /reload fixes it, I assume its a client side issue / addon.

**Comment by The-GhostRider** [comment]
> Cannot reproduce indeed. If a /reload fixes it, I assume its a client side issue / addon.

If a "/reload" fix it, it's because the problem has nothing to do with the server, it's a Client issue that sometimes bugs, I always recommend using the enUS Client version, and always deleting the "Cache" before entering the game.

For this reason "The bug" is rare and cannot be reproduced on command, because it is only a defect of the Client.
either way, as my video demonstrates the bug is not reproducible.
https://youtu.be/hoYvyDQLSKs
