### ISSUE TITLE
77 creatures drop icecap

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1741]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

77 creatures drop icecap

### Expected Blizzlike Behaviour

No creatures should drop them.

### Source

https://tbc.wowhead.com/item=13467/icecap#dropped-by

### Steps to reproduce the problem

query the following:

select creature_template.name, creature_loot_template.entry, creature_loot_template.chance from creature_loot_template join creature_template on creature_loot_template.Entry=creature_template.lootid where creature_loot_template.item="13468";

### Extra Notes

A reasonable question may be that elementals can drop this herb but even with that condition added, it still appears in 77 loot tables.

relevant query:

select creature_template.name, creature_loot_template.entry, creature_loot_template.chance from creature_loot_template join creature_template on creature_loot_template.Entry=creature_template.lootid where creature_loot_template.item="13467" and creature_template.faction!="91";

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
WotLK game client: https://wotlk-twinhead.twinstar.cz/?item=13467 Icecap drops from mobs
Vanila game client; https://classic.wowhead.com/item=13467/icecap Icecap doesn't drop from mobs

It got changed after TBC, linking TBC database is incorrect as we're on wotlk game version.

**Comment by baranzadeoglu** [comment]
> WotLK game client: https://wotlk-twinhead.twinstar.cz/?item=13467 Icecap drops from mobs
> Vanila game client; https://classic.wowhead.com/item=13467/icecap Icecap doesn't drop from mobs
> 
> It got changed after TBC, linking TBC database is incorrect as we're on wotlk game version.

I am just putting a general reply to 4 comments you posted on my posts. The wotlk databases you use are not official. They are private server data more or less. Private server data that this partially based on. Doesn't make it true. Also, is a very bad game design to put 0.02% chance for wide range of drops. There are multiple bugs already confirmed and accepted that mobs from an item they are not supposed to with 0.02% chance. By best guess is someone in the past shoot the core with a shut gun. 

Also it is quite reasonable to assume if a herb doesn't drop from a mob at
Vanilla
Tbc
live current retail

Then the idea that it is chanced just after tbc just to be chanced again on retail is fringe at best

**Comment by Azcobu** [comment]
> linking TBC database is incorrect as we're on wotlk game version.

This is actually a perfectly reasonable point, but as we don't have any reliable Wrath databases, we are forced to fall back on TBC for semi-reliable data instead, and to use other sources whenever we can.

As for the various other Wrath DBs on the web, including Twinstar and WotlkDB.com, you can always check their validity with what I call the Skeletal Executioner test. All of these DBs will tell you that a lvl 55 Skeletal Executioner is found in the NE of Silverpine Forest. (As in [here](https://wotlk-twinhead.twinstar.cz/?npc=1787)) This is of course completely wrong, it's just some error that got into the ancestor database that all these other Wrath databases are derived from. But the common Executioner glitch shows they're all related to each other, and they're all somewhat untrustworthy.

@baranzadeoglu , Incidentally, as a side-note, if you want to check for elementals then your best option is to use the `type` field in `creature_template`, rather than `faction`. Faction 91 is the Gelkis Clan centaurs, so maybe not very useful here. You want type != 4 to exclude elementals.
