### ISSUE TITLE
Down With The Dark Iron

### ISSUE THREAD

**Issue by Md-Knox** [chromiecraft/chromiecraft#1795]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

The event starts but after finishing no quest item spawns/starts.

### Expected Blizzlike Behaviour

https://www.wowhead.com/achievement=1186/down-with-the-dark-iron#comments

You fight off the event by throwing beer glasses at them and at the end u get to hand in a quest.

### Source

https://www.wowhead.com/achievement=1186/down-with-the-dark-iron#comments

### Steps to reproduce the problem

Wait till half past the hour fight off the event and wait nothing happens.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
To have the cog appear you need to successfuly defend the kegs

**Comment by Stump876** [comment]
Correct. In order to collect the gear you need to successfully fend off the attack. Right from the source provided:
https://www.wowhead.com/achievement=1186/down-with-the-dark-iron#comments

"Here is what I summarize from above:
- This event cannot be soloed, so you need many people (from same faction) to do it.
- This event occurs every 30 minutes and **you need to survive for 5 minutes.**
- Losing even one Keg will make it impossible to win because the rest of Iron dwarfs will swarm the remaining Kegs (although it won't make you loose as long as you still have one).
- After surviving the event a wheel will drop on ground that will offer you the turn in quest for the achivement."
