### ISSUE TITLE
Mobs being able to parry when disarmed

### ISSUE THREAD

**Issue by VFaleiro** [chromiecraft/chromiecraft#1809]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Mobs are currently being able to parry attacks when disarmed.

![WoWScrnShot_092121_003659](https://user-images.githubusercontent.com/19631518/134108651-4959b3f3-46da-4ce1-8ec4-1c399d244207.jpg)

### Expected Blizzlike Behaviour

Parrying always requires a melee weapon.

### Source

To be honest, I couldn't find any source confirming or contradicting this report. I'm not sure how to proceed.

### Steps to reproduce the problem

1. [Disarm](https://wowgaming.altervista.org/aowow/?spell=676) any hostile NPC that has a weapon;
2. Auto-attack or use melee (physical) special abilities;
3. Once in a while the NPC will parry you before the Disarm wears off.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Did some checking and can confirm that disarmed mobs can parry on AC. However, I've found a couple of sources that seem to say this may be correct, although admittedly they're poor-quality sources. There's a discussion on vanilla mechanics [here](https://forum.twinstar.cz/threads/npc-parry-dodge-block-mechanics.94746/) where someone asks "Can NPC's that are not wielding a weapon parry an attack?" and are told "Yes, some NPCs can parry attack even without a weapon, but not every NPC." They also cite the [patch notes from 1.3](https://wowwiki-archive.fandom.com/wiki/Patch_1.3.0) where it says 'Parry: All creatures will now report a Parry on attacks from the front instead of translating them into a "Miss."' 

There's also a few comments on Wowhead [here](https://www.wowhead.com/spell=3127/parry#comments) for patch 3.0.3 where one person says "you cannot parry an attack if you are disarmed" which sounds nice and definitive, and then someone goes and spoils it by saying "Most mobs can Parry, despite the lack of presense of an actual melee weapon. For mobs, it's just something "that is"." ([source](https://www.wowhead.com/spell=3127/parry#comments:id=364683:reply=57396))

Now these aren't great sources, but they do suggest that this may be Blizz-like, despite what common sense would indicate. If you or anyone else can find clearer sources on this though, would be happy to see them.

**Comment by Salehyn** [comment]
Several mobs can parry and even block attacks without carrying weaponry or a shield. About 90% of owlkins for example. Also 90% of raid bosses.
The weapon requirement to parry is only for players.
