### ISSUE TITLE
Searing Totem atacks targets that are already dead

### ISSUE THREAD

**Issue by costik36** [chromiecraft/chromiecraft#1872]
Hello,

When Searing totem starts casting at a target that was alive when the cast starts, it will finish its cast even if the target is dead instead of stoping the cast.

The result is wasted time to finish the cast on a invalid target instead of atacking the next one.

I noticed this issue starting with the first rank of Searing totem.

Thank you.

**Comment by VFaleiro** [comment]
Hi.

Thanks for reporting this but I believe the triagers will close this issue because you did not fill the form for reporting bugs.

Please, try reporting this again by clicking on the "New issue" green button, then "Get started".
Or, alternatively, using [this link](https://github.com/chromiecraft/chromiecraft/issues/new?assignees=&labels=&template=bug_report.yml).
