### ISSUE TITLE
Arcane Concentration / Clearcasting procs incorrectly

### ISSUE THREAD

**Issue by waiora** [chromiecraft/chromiecraft#1879]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [X] 20-29
- [X] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Clear casting is procing of any spellcast, including non damage spells like Mage Armor, Conjure Water, etc.

### Expected Blizzlike Behaviour

Should only have a chance to proc on hits from damage spells

### Source

NA - Its on talent description 

### Steps to reproduce the problem

Learn Arcane Concentration 5/5

Cast Mage Armour
Cast Conjure water

or any other non damage spells

### Extra Notes

None

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
My 2 cents here:
Rank 1: https://wotlkdb.com/?spell=11213
Rank 2: https://wotlkdb.com/?spell=12574
Rank 3: https://wotlkdb.com/?spell=12575
Rank 4: https://wotlkdb.com/?spell=12576
Rank 5: https://wotlkdb.com/?spell=12577

https://wowwiki-archive.fandom.com/wiki/Arcane_Concentration

> chance to enter a Clearcasting state after any damage spell hits a target
Unlike "on spell hit" effects, Arcane Concentration cannot proc off each hit of an Arcane Missiles' bolt, but only off the initial hit of AM itself.

**Comment by waiora** [comment]
> My 2 cents here: Rank 1: https://wotlkdb.com/?spell=11213 Rank 2: https://wotlkdb.com/?spell=12574 Rank 3: https://wotlkdb.com/?spell=12575 Rank 4: https://wotlkdb.com/?spell=12576 Rank 5: https://wotlkdb.com/?spell=12577
> 
> https://wowwiki-archive.fandom.com/wiki/Arcane_Concentration
> 
> > chance to enter a Clearcasting state after any damage spell hits a target
> > Unlike "on spell hit" effects, Arcane Concentration cannot proc off each hit of an Arcane Missiles' bolt, but only off the initial hit of AM itself.

that interesting because with blizzard it procs all the time, i wonder if the chill effects cause it to proc even more often. Either way this talent needs an entire overhaul its so bugged and broken. Cant believe the only reports is with missile so far.

**Comment by cachocarne** [comment]
Blizzard is a channeled spell with different "TICS". There are 4 chances to proc (during its 8 seconds duration) but also can hit a lot of times if there are many mobs. Arcane Missiles doesn't count exactly as channeled, although it is. The spell is activated once, but it has different shots. So the only chance to proc Clearcasting is at the beginning, when the first missile lands (otherwise would be insanely broken, with constant free Arcane Blasts.

In Vanilla and TBC, Arcane Missiles could proc Clearcasting a total of 5 times, but was later modified.

Patch 1.9:
Arcane Concentration
Gives you a 10% chance of entering a Clearcasting state after any damage spell hits a target.
Arcane Missiles - Will now be able to trigger procs based on dealing damage. (10% x5)

Patch 3.0.8:
Mages
Arcane Missiles: This spell now only has one chance to trigger Arcane Concentration.

**Comment by waiora** [comment]
> Blizzard is a channeled spell with different "TICS". There are 4 chances to proc (during its 8 seconds duration) but also can hit a lot of times if there are many mobs. Arcane Missiles doesn't count exactly as channeled, although it is. The spell is activated once, but it has different shots. So the only chance to proc Clearcasting is at the beginning, when the first missile lands (otherwise would be insanely broken, with constant free Arcane Blasts.
> 
> In Vanilla and TBC, Arcane Missiles could proc Clearcasting a total of 5 times, but was later modified.
> 
> Patch 1.9: Arcane Concentration Gives you a 10% chance of entering a Clearcasting state after any damage spell hits a target. Arcane Missiles - Will now be able to trigger procs based on dealing damage. (10% x5)
> 
> Patch 3.0.8: Mages Arcane Missiles: This spell now only has one chance to trigger Arcane Concentration.

The 10% feels wrong on blizzard too, Its  procing more than 10% when you blizzard on a single target. Maybe both the damage and TICS cause it to proc. Either way, this talent needs a complete rework. Its broken and incredibly powerful as it is now. You can run an entire RDF and never drop below 80% mana. This is going to be exploited to the max with AOE mage farming since the only resource you care about is mana.

**Comment by Azcobu** [comment]
We had another report about Arcane Concentration and Blizzard in https://github.com/chromiecraft/chromiecraft/issues/1502, and that has been fixed and merged in this PR: https://github.com/azerothcore/azerothcore-wotlk/pull/7933. The fix hasn't made it across to Chromie just yet, although it shouldn't be too long. So that should sort out the problem with Blizzard and AC proccing far too much. However, just confirmed that this issue, where AC procs from non-damaging spells, is still occurring even after that change.

**Comment by bonfax4** [comment]
This is wrong btw regarding arcane missiles at least. Just dunno how much the reduced chance is but it should proc per missile hit.

Patch 3.3.0
"Mages
Arcane Concentration: The interaction of this talent with Arcane Missiles has been restructured. Instead of an Arcane Missiles cast triggering the talent, each missile has an independent (but reduced) chance to trigger this talent. In addition, the talent will no longer sometimes be triggered from misses by Arcane Missiles, Arcane Blast, and Blizzard."

**Comment by discorder0** [comment]
Why bother to report? Just roll a mage and enjoy.
