### ISSUE TITLE
Tarren Mill : "Dangerous!" Quest

### ISSUE THREAD

**Issue by Aluneth7** [chromiecraft/chromiecraft#188]
##### SMALL DESCRIPTION: "Dangerous!" Quest exclamation mark is phased inside the wall and not being visible, therefore making it easy to miss and people like me eventually dropping the efforts of finding the quest and skip.
![Screenshot_7](https://user-images.githubusercontent.com/80447934/110750086-a5748600-824a-11eb-8a90-7c287665e91e.png)

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/b6bcb0b2b01d9788cc19a0a726ea9019b4673a1b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Cosmic-Cocoa** [comment]
Filling out the missing fields:

> ##### ISSUE: FACTION SIDE: HORDE 
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

> ##### CONTENT PHASE:
20-29

> ##### SMALL DESCRIPTION: 
Quest: [Dangerous!](https://classic.wowhead.com/quest=567/dangerous)
NPC_Start: [Dangerous!](https://classic.wowhead.com/object=2008/dangerous)
NPC_End: [High Executor Darthalia](https://classic.wowhead.com/npc=2215/high-executor-darthalia)

"Dangerous!" Quest exclamation mark is phased inside the wall and not being visible, therefore making it easy to miss and people like me eventually dropping the efforts of finding the quest and skip.
> ![Screenshot_7](https://user-images.githubusercontent.com/80447934/110750086-a5748600-824a-11eb-8a90-7c287665e91e.png)
> 
> ##### EXPECTED BLIZZLIKE BEHAVIOUR:
The game object that offers the quest should be completely visible instead of clipping into the wall. I believe this would also make the exclamation denoting that it offers a quest visible.

> ##### CURRENT BEHAVIOUR:
The game object offering the quest clips into the wall it is affixed to and the exclamation is not visible.

> ##### STEPS TO REPRODUCE THE PROBLEM:
> Step 1. Teleport to Tarren Mill as a horde character.
> Step 2. Approach the inn and look at the game object (a poster) to the right of the door.

> 
> ##### AC HASH/COMMIT:
> [azerothcore/azerothcore-wotlk@b6bcb0b](https://github.com/azerothcore/azerothcore-wotlk/commit/b6bcb0b2b01d9788cc19a0a726ea9019b4673a1b)
> 
> ##### OPERATING SYSTEM:
> Ubuntu 20.04
> 
> ##### MODULES:
> * [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
> * [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
> * [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
> * [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
> * [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
> * [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
> 
> ##### OTHER CUSTOMIZATIONS:
> None.
> 
> ##### SERVER:
> ChromieCraft

**Comment by necropola** [comment]
I'm not sure whether the positioning (and resulting clipping issue) of the Wanted Note is 100% client-side or whether you can control this on the server.
The [Screenshot from Classic](https://classic.wowhead.com/quest=567/dangerous#screenshots:id=23415) does not have a clipping issue, but Classic has a different client.
I remember that I regularly overlooked this quest, because it was so hard to spot, but this memory is from playing on **private servers** over the past years and not from retail.

**Comment by illfated** [comment]
If the Wanted Note board is a gameobject and not a part of the building, it is possible that its rotation and positioning could be off and needs adjusting, the same way as some of the road signs on signposts have been affected in recent years in the TrinityCore DB (TDB). The quest marker, on the other hand, is more likely to be partially hidden and probably has been on retail since Vanilla days.

**Comment by Helias** [comment]
Fixed, thanks for the report.

As @illfated said, it's a gameobject so we can fix the position server-side.
![image](https://user-images.githubusercontent.com/519778/110868320-a9df8400-82c8-11eb-9c85-322621973185.png)

**Comment by Cosmic-Cocoa** [comment]
> The quest marker, on the other hand, is more likely to be partially hidden and probably has been on retail since Vanilla days.

Ha, that's funny. I just suspected it might not be showing because its positioning might be based on the object offering it, causing it to appear in the structure of the inn since this one was slanted.
