### ISSUE TITLE
Auctionhouse does not show every item on frontpage

### ISSUE THREAD

**Issue by Notrox1** [chromiecraft/chromiecraft#189]
##### ISSUE: FACTION SIDE: Horde

!-- ![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)--
!-- ![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)--

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

Auction House does not show every item on Front Page. When i do a search on the frontpage and sort by weapon - for example it only shows me one weapon for level 27. If i go on Weapons and do the same search again - it shows me multiple. 
Same goes for Armor, Mats and Consumables.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should show everything on frontpage which has the highest levels if you sort by level

##### CURRENT BEHAVIOUR:

Does only show a few items, you can only see all items if you use the Filters on the left side

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 
Open Auction House and click on search
Step 2 
Sort by Level and watch the first items
Step 3 
Do the same search with activating Weapon Filter on the left

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/b6bcb0b2b01d9788cc19a0a726ea9019b4673a1b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
At least until 3.3.5a the in-game Auction House response was organized in **pages**.
While the categories on the left are server-side filters (they reduce the number of pages transmitted to the client), the filtering and sorting on the right only applies to the current page and is executed on the client.

So, what you are describing looks perfectly normal to me (not a bug) and, although I agree that it is annoying to go through multiple pages in order to actually find the best deal, it's just the way it was.

**Tip:** Be as specific as you can in the server part of the query.

**Comment by Notrox1** [comment]
Hello, thanks for the Reply.
When i add an lvl 29 weapon to auctionhouse - it should appeor on the start page if I sort by Level, shouldnt it?
Thats why i opened this bug.I created an auction for a lvl29 gun and was not able to see it on the startpage

**Comment by Notrox1** [comment]
Thanks for the clarification :)
