### ISSUE TITLE
[Rare]Emogg the Crusher has a very low chance to drop a green

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1892]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Emogg the Crusher has a very low chance to drop a green
between 5-10% at best
![image](https://user-images.githubusercontent.com/84640316/135328295-a0b4472a-9836-4df5-b782-0b68b3c34fd1.png)

### Expected Blizzlike Behaviour

Rares usually almost always drop a green (at least)

Also Mo'grosh Crystal drop rate might need to be lower. Currently at 8%. Classic tbc wowhead suggests 0.4%

### Steps to reproduce the problem

query mysql or use keira3

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment]
> Classic tbc wowhead suggests 0.4%

Should keep in mind that Wowhead has what players report (through the Wowhead client), which includes a lot of people who killed him while not having [A Dark Threat Looms](https://wowgaming.altervista.org/aowow/?quest=278) in their quest log.

**Comment by acidmanifesto** [comment]
@baranzadeoglu Thank you for the issue report and I do apologize for a follow up on the matter. 
So just some back ground information, i am apart of the new established sniff team and I am actually the guy who wrote the sniffer guide standard for both tc and azerothcore. 
https://trinitycore.info/en/install/Sniffs
https://www.azerothcore.org/wiki/sniffing-and-parsing

So how we get hte % for loot is this:
Loot: Kill the npc and loot. We get most accurate loot results depending on how many sniffs we get or something like that is more accurate, such as data mining like how wowhead does it, since a single person will never kill a mob a thousand times.

So with wowhead, we have the issue with pservers and repacks diluting their reports. I mean.. we got strider meat showing on wow head from copper node mining. https://www.wowhead.com/item=5469/strider-meat#mined-from-object

So pretty much the standard of 1k cumlative kills based on many sniffs with in a particular expansion is then calculated and averaged out.  As of right now, our loot table matches that basis as it is matched up with TC and Mangos.

Now do not get me wrong, Wowhead is a great site for resource and infromation, but the dilution of loot % is a issue that can not be trusted in full, so we have to rely on past sniffs of particular expansions.

**Comment by baranzadeoglu** [comment]
> Now do not get me wrong, Wowhead is a great site for resource and infromation, but the dilution of loot % is a issue that can not be trusted in full, so we have to rely on past sniffs of particular expansions.
It is not a % issue. Rares (to my experience) always drop a green item, (maybe a gem).

**Comment by acidmanifesto** [comment]
> > Now do not get me wrong, Wowhead is a great site for resource and infromation, but the dilution of loot % is a issue that can not be trusted in full, so we have to rely on past sniffs of particular expansions.
> 
> It is not a % issue. Rares (to my experience) always drop a green item, (maybe a gem).

Bare with me, I am just now seeing you other report:
https://github.com/chromiecraft/chromiecraft/issues/1922
We have this addressed in another spot by a dev, so i sent them a message to link me to their pr they did. 

If you want i can reopen this, or handle this issue thru that other issue in general.

**Comment by baranzadeoglu** [comment]
> Bare with me, I am just now seeing you other report: #1922 We have this addressed in another spot by a dev, 

That report is about scholomance. This one is about a rare mob.

**Comment by baranzadeoglu** [comment]
@acidmanifesto still tagged "closed" and "won't fix"

**Comment by baranzadeoglu** [comment]
@acidmanifesto this is still tagged closed.
