### ISSUE TITLE
[Scholo]Lord Alexei Barov has wrong loot table

### ISSUE THREAD

**Issue by baranzadeoglu** [chromiecraft/chromiecraft#1897]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

drops an item at 60% chance. The chances are same all but lightforged bracers.

![image](https://user-images.githubusercontent.com/84640316/135468574-316fc56f-f1e1-45a5-b6f9-950d8319ae65.png)

### Expected Blizzlike Behaviour

Chances should vary.

Most likely it drops an item every time as well.

Probably there should be at least 2 or 3 reference loot tables here to vary different rates. Set pieces for Cadaverous and Necropile boots should be in a seperate rlt with much smaller trigger rate I think.

Also, small singular items are missing from the overall loot such as major healing pots thorium lockbox etc.

### Source

https://tbc.wowhead.com/npc=10504/lord-alexei-barov

### Steps to reproduce the problem

keira 3 or mysql

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
Currently Loot table Matches up with UDB (Universale Database) that is established for loot based on verified sniffs and not wowhead or website database scrapes.
In our table we have the following hits on the creature_loot_template:
![image](https://user-images.githubusercontent.com/16887899/148100846-d35af063-c61f-4edf-86e8-3cbd02ab169c.png)
With references to reference loot table:
35031 when it comes to groups.

Loot tables are concurrent and matching exactly to UDB.

Loot tables are not 100% drop on items with every kill regardless of rarity of creature type\boss type.
Reference Loot Tables were not 100% either on older wow expansions as well contrary to popular belief due to adjustments in much later expansions.
