### ISSUE TITLE
Sap breaks on (Warlock or Hunter) Master NPC when the Rogue attacks the pet

### ISSUE THREAD

**Issue by necropola** [chromiecraft/chromiecraft#191]
##### ISSUE: FACTION SIDE:
![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
When a Rogue applies [Sap](https://wotlkdb.com/?spell=6770) to a Hunter or Warlock **NPC** and then attacks (tries to kill) the pet, the master wakes up. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Only damage to the sapped target itself (and not its pet) should wake up the target.

##### CURRENT BEHAVIOUR:
See **Short Description**

##### STEPS TO REPRODUCE THE PROBLEM:
* Sap a Hunter or Warlock
* Attack its pet

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/b6bcb0b2b01d9788cc19a0a726ea9019b4673a1b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
I've checked my local AC and TC server:
* Bug exists in current AC, too
* Bug **does not exist** in current TC

**Comment by Zoidwaffle** [comment]
Dammit, for once something that gives a tiny advantage to warlocks vs. rogues and you want to get rid of it? :cry:

**Comment by FrancescoBorzi** [comment]
> I've checked my local AC and TC server:
> 
> * Bug exists in current AC, too
> * Bug **does not exist** in current TC

@necropola can you please link this issue to AC?

**Comment by Stifler82** [comment]
So, I seem to remember that I had already made you download the enUS Client, so I won't ask you what version you have.

Now, since I have not been able to replicate the "BUG", there is no BUG for me.

So, are you sure you haven't used abilities that hurt AOE? and then with that ability you hurt the Master too?

Because as you can see from my video (and I have the latest version of AC) what you claim is not replicable.

you clear cache before opening wow?

**Video Test:** [Sap breaks](https://youtu.be/4Oc2EofLjas)

**Comment by necropola** [comment]
Your Sap Target isn't an NPC and has no AI, right?

**Comment by Stifler82** [comment]
> Your Sap Target isn't an NPC and has no AI, right?

is it sarcasm or what? i don't understand your question..

**Comment by necropola** [comment]
I wasn't referring to player targets but NPC targets in game. I should have made that clear in the original issue. Sorry.
Try [Razormane Hunters](https://wotlkdb.com/?npc=3265) near Crrossroads and [Dalaran Conjurers](https://wotlkdb.com/?npc=1915) at Ambermill.

**Comment by Stifler82** [comment]
> I wasn't referring to player targets but NPC targets in game. I should have made that clear in the original issue. Sorry, I've edited the description and title.
> Try [Razormane Hunters](https://wotlkdb.com/?npc=3265) near Crrossroads and [Dalaran Conjurers](https://wotlkdb.com/?npc=1915) at Ambermill.

so are you referring to a fight against AI?

I honestly understood that this was a PvP issue
especially reading Zoidwaffle's comment

**Comment by necropola** [comment]
I noticed the bug while trying to do the [Tools of the Trade](https://wotlkdb.com/?quest=1999) quest and couldn't get (sneak) past the NPC Warlocks. And then I tried the Razormane Hunters to see whether NPC Hunters are also affected. When I made the report I really wan't thinking about whether this would affect PvP, too. But if it were, we probably would have had complaints from PvP players (Rogues) already.

**Comment by Zoidwaffle** [comment]
I have had a warlock in WoW ever since vanilla, so my hatred towards rogues in open world PvP could be used to power several bitcoin-mining facilities.

I thought it was a PvP issue, sorry for the confusion, I just wanted to leave a funny comment :cry:

**Comment by necropola** [comment]
I play Affliction Warlock as my main since WotLK, but I was never much into PvP (probably because I suck at it). Anyway, I'm kinda wearing PvE tinted goggles. Hence I forgot to mention that I encountered the bug in PvE not PvP. My bad.

**Comment by Stifler82** [comment]
> I have had a warlock in WoW ever since vanilla, so my hatred towards rogues in open world PvP could be used to power several bitcoin-mining facilities.
> 
> I thought it was a PvP issue, sorry for the confusion, I just wanted to leave a funny comment 😢



> I play Affliction Warlock as my main since WotLK, but I was never much into PvP (probably because I suck at it). Anyway, I'm kinda wearing PvE tinted goggles. Hence I forgot to mention that I encountered the bug in PvE not PvP. My bad.


My first Main was Warlock too I always played Warlock, I started playing WoW way back in 2007, so I started playing TBC, I had Warlock Destruction, and I was an absurd noob in both PvE and PvP, then I became the King of Arathi Basin and Warsong Gulch, but that's only because I was a shity Hacker! I used WoWEmuHacker program and I teleported time 0 from one base to another, then after a series of complaints from the players the GMs banned me at least 20 of accounts, but I kept exping characters and hacked more and more, I wasn't doing it for the fun of it, I was doing it because the GMs made my balls spin!
Because the server was full of BUGS, and I was a "Cloth" Class that had a lot of talent and spells shortfalls.
And then, a bit as a sign of protest, a bit because in a certain sense I compensated for the deficits of my character, I used hack programs (for example) WPE and I doubled the items and multiplied the Gold, I was Jesus! 🤣  and when a friend needed of riding for the mount, I gave him 5k - 10k gold "under the table".
And I paid for their silence (lol).
This is mafia!🤣🤣🤣
Anyway, kidding aside, I became a wow programmer and got hooked on Emulators just because GMs sucked!

and basically that's why I want to do things well, I knew I could do better than them, and I succeeded..
And when I told you that: "I have seen bugs that you humans cannot understand", trust me that it is..

I'll tell you a sensational one..

Once in Shattrath in the serer where I used to play, in lower city there is a vendor who sells a "Doll" for 100 gold, that same vendor also sells another thing, that is "the gift wrapping paper" to pack things.
In practice, the Bug was in the wrapping paper, because someone bought the doll at 100 gold, then bought the wrapping paper (which costs very little, now I don't remember), and in practice you were packing the doll, and up to here everything is ok, Nothing strange..

The trick was, or rather, the bug was that the wrapping paper could have up to 20 stacks, so when you wrap the doll 20 times, then you split the 20 stacks inside the bag, unwrap the packages, and you end up with 20 dolls. that you could sell for 100 gold and those 100 gold you consumed earlier to buy the first doll became 1900! and you bought the mount like this! (lol).

Anyway, then with the Warlock I changed specialization and I became Affly, and I use it in both PvP and PvE, some might say that in PvE Destruction is better, maybe yes, maybe not, it depends on which point of view you look at the thing..

Because if you do PvE with the guild, you have to think that the success of the Instance depends on the fact that the guild manages to kill all the Bosses in the instance, so having a Warlock Affly that doesn't weigh on the healer's mana is a good thing , a DPS that doesn't depend on casting but casts instant Spells that heal it and doesn't even need to recover mana.

Maybe on the Recount addon he won't be first on the list, but he sure is someone who does continuous damage (if you do the right spell sequence), and doesn't weigh on the healer's mana, mana he can use to heal the Tank and the rest of the party.

I know, I went totally off-topic, but it doesn't matter, today you know a little more about me.. (like wow stuffs btw)

**Comment by Hemingway1970** [comment]
Not sure if its related but the warlock npcs near Stonewatch in Redridge appeared to immediately break sap when other mobs around it were agroed.

**Comment by Stifler82** [comment]
The problem is only with the Warlocks and not the Hunters.
Because this isn't a "Pet" problem, it's Spell's problem, while the Hunters Summon their "Pets" via SAI, the Warlocks Summon the Void's Via Spell, the spell is likely to create some bond between the Demon and the Warlock and even if the Warlock doesn't take any damage, the stun's break effect activates on the Warlock as if he would be the one taking the damage.

**Video Test:** [Sap breaks](https://youtu.be/MZ1RSwRwroo)

**Comment by necropola** [comment]
Interesting. I tried the same Razormane Hunter and he woke up.

**Comment by Stifler82** [comment]
> Interesting. I tried the same Razormane Hunter and he woke up.

IDK what say..
have you watch my video?

**Comment by necropola** [comment]
I did, hence my reply. I'm wondering what the difference is/was between you sapping the hunter and killing his pet and me doing the *same* thing.

**Comment by Stifler82** [comment]
Ok, after careful consideration, I have reached the conclusion that this is not a Bug.

The reason is: The Warlock does not make a Summon through SAI, that is, that summons the Demon's ID, but summons the Demon through Spell, this means that the NPC (Summoner) shares their "Properties" with the Demon exactly as it happens between Warlock Character and Demon, so they share Stats like "Armor" etc..
So when the Demon takes damage, the Warlock is also affected by this damage, but! he takes no damage..
