### ISSUE TITLE
Paladin Seal bugs

### ISSUE THREAD

**Issue by Sasnicka** [chromiecraft/chromiecraft#1925]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Good afternoon,

https://wowgaming.altervista.org/aowow/?spell=20375
https://wowgaming.altervista.org/aowow/?spell=21084

Please find the description of seal of command and seal of righteousness. This is a serious issue that makes paladins overly powerfull and needs to be fixed (and I am a paladin main). 

Seal of command and seal of righteousness were tested and confirm to "trigger" when a player uses Judgement spell. 

Both seal of command does AOE damage and seal of righteousness does single target damage when judgement is used. 

### Expected Blizzlike Behaviour

Judgement is a SPELL, not an ability or a melee attack. https://wowgaming.altervista.org/aowow/?spell=20271

As you cannot see, seals should be triggered only by melee attacks and abilities such as auto attacks, crusader strike.

But not by AOE spells or RANGED spells such as divine storm or judgement. 

### Source

Judgement should not trigger seals. Nor should divine storm. Only melee attacks and abilities should trigger seals. 

### Steps to reproduce the problem

Works on all mobs, dummies, etc.
I don't know what is that...
I think so, yes. Combat log shows damage happening
To identify a bug, apply a seal and use judgement on a mob or a dummy from range. It will trigger the seal (command does AOE damage too). 

### Extra Notes

Feel free to contact me in game (Trosha/Sasnicka/Sassywarr/Sassybank) if need additional information. 

### AC rev. hash/commit

Don't know what this is. 

### Operating system

Windows 10 64x

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by phonkala** [comment]
Judgement is an ability that hits single target and should trigger the effect.
https://wowwiki-archive.fandom.com/wiki/Seal_of_Command_(old)

**Comment by Daedalus007** [comment]
**All Paladin Seals will always trigger when doing a Judgment**.  This is by Blizzard (re)design (with the 10 second cooldown, modified to 8 seconds with talents in Retribution tree) for the Paladin class in WotLK.

They made a big deal about improving Paladin DPS in WotLK so they wouldn't be so mana-starved.  Judgement effects were seperated from their seals and as a result the seal effects were changed/removed/modified and they will always trigger on Judgement instead of randomly via RNG.

You may be thinking of the OLD way that Seal of Command used to work in TBC (roughly 7 times a minute procs, higher chance of procs based on slow speed 2 handed weapon) but this was completely changed around for WotLK.  Now that they trigger roughly every 8 to 10 seconds, the effects/damage were adjusted to compensate and make Paladins "Less Bursty".

This is not a bug.  I'll link three different retail PvP WotLK videos from 2009 (late game around Ulduar/LK patch)
As typical of most videos of this era, please completely mute the audio as the music choices are quite dated:
https://www.youtube.com/watch?v=mNfQZvTC-E0
https://www.youtube.com/watch?v=8VhKPbY3uCI
https://www.youtube.com/watch?v=3cp1789VFmQ

In all three videos it clearly shows procs of the seals (often multiple times) whenever doing a judgement as well as with auto-attacks.  It isn't RNG-based anymore.  Seal of Command was completely overhauled between TBC and WotLK era.  As someone who played retail WotLK (Tichondrius server) back in 2009-ish era, I have firsthand experience as well about the drastic changes they did to how procs worked for seals and judgements.
