### ISSUE TITLE
[Paladin] Unable to use Lay On Hands on self while affected by Forbearance

### ISSUE THREAD

**Issue by Snufflenose** [chromiecraft/chromiecraft#1929]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

As a paladin it's not possible to use Lay On Hands on self while under the effect of Forbearance (caused by using - for example - Divine Protection).

### Expected Blizzlike Behaviour

I'm pretty sure that Lay On Hands should be usable on self regardless of being affected by Forbearance or not.

Here's what the tooltips say:

Lay On Hands
"Heals a friendly target for an amount equal to the Paladin's maximum health. If used on self, the Paladin cannot be targeted by Divine Shield, Divine Protection, Hand of Protection, or self-targeted Lay on Hands again for 2 min. Also cannot be used on self within 30 sec of using Avenging Wrath."

Divine Protection
"Reduces all damage taken by 50% for 12 sec. Once protected, the target cannot be targeted by Divine Shield, Divine Protection, or Hand of Protection again for 2 min. Cannot be used within 30 sec of using Avenging Wrath."

Forbearance
"Once protected, the target cannot be protected by Divine Shield, Divine Protection or Hand of Protection again for 2 min."

So, according to the tooltips you should be able to use Lay On Hands on self after using Divine Protection, but not the other way round.
Either that - or the tooltips are misleading.

### Steps to reproduce the problem

1. Use Divine Protection.
2. While still under the effect of Forbearance try to use Lay On Hands on self.
3. Die a horrible death, because you expected LoH to keep you alive while 3 mobs are hitting on you.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

macOS Catalina + Wine

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
Probably there's some issue with the tooltip. Or they didn't include LoH because it won't be affected if you use it on someone else.

https://wowwiki-archive.fandom.com/wiki/Forbearance

Forbearance: Cannot be protected by Divine Shield, Divine Protection, Hand of Protection or Lay on Hands.
Duration: 2 minutes

Forbearance is a two minute debuff on the receiver of the spells Divine Shield, Divine Protection, Hand of Protection, and Lay on Hands (if used on self). The receiver cannot be affected by those spells until Forbearance fades out.

Patch 3.3.0 (08-Dec-2009): This ability will place Forbearance on the paladin if used on his or herself. It will not place Forbearance on others.
Patch 3.3.3 (2010-03-23): Tooltip clarified to better explain this ability’s interactions with Divine Shield, Divine Protection, and Hand of Protection.

**Comment by Snufflenose** [comment]
Thanks for the info.

I'm used to play on Vanilla servers - so using LoH without restrictions is a given to me.

Strange that of all things this was changed with WotLK - an expansion which otherwise seems to have a tendency to (over)simplify things to make them as casual-friendly as possible...

**Comment by Daedalus007** [comment]
Hello, this is NOT a bug.  This is by design since Vanilla and into TBC and WotLK as well.
Lay on Hands triggers Forbearance and can NOT be used while under the effects of Forbearance.
Unfortunately, the tooltip for Lay on Hands was not updated until Cataclysm.  If the devs want to update the tooltip to the correct one even though it wasn't fixed officially until later, that is up to them.  I would advise doing so as it confuses people who don't know about it.

Patch Changes Source: https://wowpedia.fandom.com/wiki/Lay_on_Hands
TBC Source: https://tbc.wowhead.com/spell=633/lay-on-hands

> Wrath of the Lich King Patch 3.3.0 (2009-12-08): This ability will place Forbearance on the paladin if used on his or herself. It will not place Forbearance on others.
> Wrath of the Lich King Patch 3.0.2 (2008-10-14): Does not drain all of the player's mana anymore. Cooldown reduced to 20 minutes.

Reproduction Steps:
-Make a Paladin that has Lay on Hands
-Use Lay on Hands on yourself
-You will get 'Forbearance' debuff and cannot bubble or use other abilities that are affected by Forbearance.  This is the intended design but the tooltip was not updated until Cataclysm.

Recommendation:
The tooltip is incomplete/bugged and should be updated to the Cataclysm version that includes the Forbearance info.

> Heals a friendly target for an amount equal to your maximum health.
> Cannot be used on a target with Forbearance. Causes Forbearance for X secs.
