### ISSUE TITLE
Sungate Destroyed quest broken

### ISSUE THREAD

**Issue by AudriWrath** [chromiecraft/chromiecraft#2129]
Broken quest, after destroying crystals can not click portal to destroy it

**Comment by Stump876** [comment]
Hello @AudriWrath Thanks for the report. In the future, please do not delete the template. It asks for the information we need to verify and reproduce issues, as well as technical info about the core build. I believe this problem was covered int this report https://github.com/chromiecraft/chromiecraft/issues/2132 so I'm just going to close this.
