### ISSUE TITLE
Darkspear Strand NPC Issue in Water

### ISSUE THREAD

**Issue by BrodieSinn** [chromiecraft/chromiecraft#228]
##### CURRENT BEHAVIOUR:

When fighting Marura's outside the troll village in the Darkspear Strand sea there seems to be an issue with the NPCs bugging out. My imp would not come to me (stopped and stayed behind me) nor fight the makrura, and the makrura was shaking very rapidly but would not come in to attack me. They both kept doing this until the Makrura died. Then the imp resumed normal function.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The makrura should attack me like any other mob and the imp should attack the mob I tell it to.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Goto Darkspear Strand sea
2. Attack a Makrura
3. Watch it shake rapidly
4.

##### EXTRA NOTES:

I also see the Makrura doing this without me attacking them as I write this.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
So, I'm closing this issue because this "Bug" is not a real Bug.

In order for the Imp's attack to work, you must set the **"Fire Ball"** spell to automatic, and the spell on the pet bar must appear with the **bright "frame"**.

We don't call this a Bug because it was an old Fix that set it up like this.
**[Link Fix]:** https://github.com/azerothcore/azerothcore-wotlk/pull/2379

Honestly **we are not sure if this "Fix" is correct**, as the IMP being **a Warlock's "Familiar"**, it should only have a **ranged attack** and **not melee attack**, in fact IMP **doesn't attack melee currently**.
What I'm not sure about however, is the fact that the imp must have **(as I told you in the lines above) "The automatic Spell Fire Ball" to cast it**, I am of the opinion that it should cast it in any case, whether the spell is set to automatic or not.

In any case, we don't consider this as a Bug, for 2 reasons:
- This scenario is not a problem because the imp is indeed capable of attacking, just set the spell as automatic.
- Since we are not sure if this Fix is correct or not, we are waiting for more detailed information for when Blizzard will release more precise information on Wowhead including the WOTLK expansion (or at least the TBC).
