### ISSUE TITLE
Flash bomb recipe dependency

### ISSUE THREAD

**Issue by discorder0** [chromiecraft/chromiecraft#2320]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

One can complete quest “flash bomb recipe” (https://tbc.wowhead.com/quest=1559/flash-bomb-recipe) without prerequisite.

### Expected Blizzlike Behaviour

One needs to complete “pearl diving” and be an engineer to complete “flash bomb recipe”. This is not explicitly listed on any database website (e.g., on pages for pearl diving, it does not say this quest unlocks “flash bomb recipe”). But read the comments on the page for “flash bomb recipe”, one needs to complete “pearl diving” first. The quest text for “flash bomb recipe” also says that the recipe is an additional bonus for engineers who help the NPC get pearls.

### Steps to reproduce the problem

Use a char who has not completed “pearl diving” and who is with reasonably high lvl and eng skills; go to Rigglefuzz in Badlands; complete “flash bomb recipe”.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/9e3332dc208215f60d62b6eef3c9e804464708da

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
As I remember, it was required to do "Pearl Diving" first in order to access other quests, including the one with the Schematic – and only if you are Engineer.

From wowhead comments:
(Patch 1.6.1)
You have to talk to him again after you complete the quest to get it
(Patch 1.9.4)
"After you complete the quest, a new quest appears from Rigglefuz....flash bomb recipe.    I accepted the flash bomb quest, then immediately completed it, and got the recipe."
(Patch 2.0.10)
"If you are an engineer he will offer you the Schematic for the flash bomb aswell"
"Don't have the full information on this quest but it starts **after** you finish the Pearl Diving quest that he gives you. If you're an engineer he'll have a quest labeled "Flash Bomb Recipe"."

Also, according to Wowwiki, "Pearl Diving" is a quest PREVIOUS to "Flash Bomb Recipe"
![ 2021-11-14 at 15 20 48](https://user-images.githubusercontent.com/77953030/141680809-3beb40ca-ae85-4db8-b6ca-d057936227e9.png)
![ 2021-11-14 at 15 21 49](https://user-images.githubusercontent.com/77953030/141680836-4c147495-e049-47d2-910e-ae18cf545687.png)
![ 2021-11-14 at 15 22 06](https://user-images.githubusercontent.com/77953030/141680838-43da7665-8e10-4d4d-b757-e9fa5620f55e.png)
