### ISSUE TITLE
Goblin/Gnomish Engineering quest available after choosing specialization / Repeatable

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#2422]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

NPC [Springspindle Fizzlegear](https://classic.wowhead.com/npc=5174/springspindle-fizzlegear) in Ironforge is offering "[Goblin Engineering](https://classic.wowhead.com/quest=4181/goblin-engineering)" quest even AFTER we have done that one and all the consecutive quests required to become a Goblin Engineer.

As you can see on the images, my warlock ALREADY is a Goblin Engineer (I completed all quests including The Plegde of Secrecy and Show Your Work). However, I was able to take the quest again.
![ 2021-11-26 at 17 07 10](https://user-images.githubusercontent.com/77953030/143774067-eb761429-06f5-443c-b268-df7c0b871d1d.png)
![ 2021-11-26 at 17 07 13](https://user-images.githubusercontent.com/77953030/143774073-a08796d4-64ce-479f-899a-8aa15adabbaf.png)
 
I am not sure if this is happening with the other specialization or with other trainers in Horde side, some collaboration would be appreciated.

### Expected Blizzlike Behaviour

After completing the questline, we shouldn't be offered this quest again.

### Steps to reproduce the problem

Complete questline started with https://classic.wowhead.com/quest=4181/goblin-engineering to become a Goblin Engineer
Visit NPC in Ironforge again and see he offers you the start quest once again.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
That's interesting. One more issue regarding to `Specialization`. One more what i can't reproduce on local AC. I checked NPc after every quest and he doesn't offered to me anything.
![WoWScrnShot_112821_225852](https://user-images.githubusercontent.com/85256266/143784094-8f892f5b-9465-4597-8d56-981b8752b8d5.jpg)

**Comment by Azcobu** [comment]
Just tried this on Horde and Ally sides and couldn't reproduce it.

Learning Goblin engineering:
![WoWScrnShot_112921_221416](https://user-images.githubusercontent.com/81782124/143863305-d1c220eb-6bea-45a8-9ed3-7b2914800f71.jpg)

Back to Graham van Talen, no more quest available:
![WoWScrnShot_112921_221724](https://user-images.githubusercontent.com/81782124/143863338-ad6a713a-09d0-492a-a482-41ee187808cb.jpg)

Similar result blueside, where Fizzlegear just opened the training window rather than offering the quest again. I did wonder if you might have picked up the [alternate Goblin Engineering quest](https://tbc.wowhead.com/quest=3629/goblin-engineering) from Lilliam Sparkspindle in Stormwind, who offers another version of the same quest, or from Tinkerwiz in Ratchet who offers [another version](https://tbc.wowhead.com/quest=3633/goblin-engineering) to both sides, but neither of these offered me anything new either.

Checking the DB shows all 9 engineering specialization quests have a common ExclusiveGroup set to 3526:

```SQL
SELECT qt.id, qt.LogTitle
FROM `quest_template_addon` qta
JOIN `quest_template` qt ON qt.ID = qta.ID
WHERE qta.ExclusiveGroup = 3526
```

| id | LogTitle | 
| ---: | --- | 
| 3526 | Goblin Engineering | 
| 3629 | Goblin Engineering | 
| 3630 | Gnome Engineering | 
| 3632 | Gnome Engineering | 
| 3633 | Goblin Engineering | 
| 3634 | Gnome Engineering | 
| 3635 | Gnome Engineering | 
| 3637 | Gnome Engineering | 
| 4181 | Goblin Engineering | 

The ExclusiveGroup is supposed to mean if you take one of that group, all the others are excluded, so in theory at least, no other questgivers should offer it again. These 9 are the only engineering specialty quests. 

Specializations for a number of professions are known to have other issues though - see https://github.com/azerothcore/azerothcore-wotlk/issues/5390 and https://github.com/azerothcore/azerothcore-wotlk/issues/5399

**Comment by Shineslippers** [comment]
My bet this is again Rollback to 18/11 core on CC and next update will fix it.

**Comment by cachocarne** [comment]
Today I had this on my warlock. As you can see, I already have Goblin Engineering specialization. I took the first quest and went to Gadgetzan, signed the book, did "show your work"…
![ 2021-11-30 at 17 10 53](https://user-images.githubusercontent.com/77953030/144071488-f3d73776-5c8a-475d-ab31-d043872be47d.png)

And what do you know know, I can take "Goblin Engineering" again. I got the book and everything to complete it in Gadgetzan.
![ 2021-11-30 at 17 11 01](https://user-images.githubusercontent.com/77953030/144071828-04bc09d6-701d-41ac-91ef-79d0702ef4fa.png)

Is this only happening to me? I would say that's VERY weird.

**Comment by cachocarne** [comment]
@Azcobu : "Similar result blueside, where Fizzlegear just opened the training window rather than offering the quest again. I did wonder if you might have picked up the alternate Goblin Engineering quest from Lilliam Sparkspindle in Stormwind, who offers another version of the same quest, or from Tinkerwiz in Ratchet who offers another version to both sides, but neither of these offered me anything new either."

Hmmm… this might be it. I will have a look to see which of those I have completed and what is the _new_ one.

**Comment by cachocarne** [comment]
I just hit level 40 on my warlock (same character as the one used for the original post) and NPC in Ironforge **OFFERS ME AGAIN THE QUEST**. I don't know what's going on.
![ 2021-12-02 at 10 28 37](https://user-images.githubusercontent.com/77953030/144377349-b6fd1e03-dfa9-4a80-a60a-815c8ccf942e.png)
