### ISSUE TITLE
[Item] Felstriker working but aura not showing on screen

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2457]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Item does proc and gives 100% crit chance, tested by multiple people, BUT WE cannot see BUFF/AURA when it procs.
Players should get buff for 3 secons when it procs like when you use talent spell or w/e.
Problem is that you don't see when you have crit chance maxed which sucks, should be seen.

### Expected Blizzlike Behaviour

https://classic.wowhead.com/spell=16551/felstriker#comments
https://classic.wowhead.com/item=12590/felstriker#dropped-by

### Steps to reproduce the problem

1. Add dagger to yourself
2. Test on anywhere you will get sometimes 100% crits on attacks but you won't know when

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Elexias** [comment]
Effect #1 | Apply Aura: Mod Melee & Ranged Crit %Value: 100%
-- | --
Apply Aura: Mod Melee & Ranged Hit Chance %Value: 100%

**Comment by Shineslippers** [comment]
Issue is exist, but from report on wowhead it's blizzlike. We have to look to Wrath era confirmation for 1st. And there is this:
>[By 184542 on 2008/08/11 (Patch 2.4.3)](https://www.wowhead.com/spell=16551/felstriker#comments:id=350199)
For some reason, when the proc occurs this buff does not show for me, however, it tells me in my combat log when it fades only.

> [By 269558 on 2009/09/20 (Patch 3.2.0)](https://www.wowhead.com/spell=16551/felstriker#comments:id=844370)
Does not show a buff when it procs but will show a combat log entry when you gain/lose the buff.

I would say it's candidate to fix, but not sure.

**Comment by Azcobu** [comment]
There do seem to be quite a few weapons that have auras that behave this way - [Shiffar's Nexus-Horn](https://wowgaming.altervista.org/aowow/?item=28418), [Crest of Retribution](https://wowgaming.altervista.org/aowow/?item=13375), [Halberd of Smiting](https://wowgaming.altervista.org/aowow/?item=19874), [Dark Matter](https://wowgaming.altervista.org/aowow/?item=46038), [Horn of Argent Fury](https://wowgaming.altervista.org/aowow/?item=39889), etc etc. Without the spells.dbc file being searchable in SQL I can't say how many items have this behaviour, but it seems so many that my guess is this is design intent rather than a bug, just to stop buffs cluttering up the screen. However, in the other weapons I've seen, they will have a 'chance to proc' aura, which is hidden, but the proc itself isn't. (e.g. Horn of Argent Fury has the buff https://wowgaming.altervista.org/aowow/?spell=55747 which is hidden, but when it procs, the spell https://wowgaming.altervista.org/aowow/?spell=55748 is not hidden.) Felstriker seems unusual in that it's not set up that way, as the 'chance to proc' aura and the resulting proc seem to be listed as the same spell. So if the proc aura was visible, it would be visible all the time, not just for the 3 seconds. 

I should also note the proc animation seems to work fine, you shouldn't have too many problems seeing when it goes off:

https://user-images.githubusercontent.com/81782124/144709200-fd628abd-7605-47d5-9453-f43065582272.mp4

**Comment by Elexias** [comment]
Do you really think that in middle of fight I will search for combat log in order to check when I had proc? I played retail and had this weapon even in WoTLK/Cataclysm times, it was op proc and I'm pretty sure that buff was seen.

**Comment by Shineslippers** [comment]
If you will find some video we could look into it, but for now there is not enought evidance to change something. This video from TBC classic and there is no icon of buff https://www.youtube.com/watch?v=iwK7LyCYrGs
