### ISSUE TITLE
Timbermaw Ally - Quest is repeatable, 

### ISSUE THREAD

**Issue by chaossonic** [chromiecraft/chromiecraft#2506]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Quest is repeatable even past Honored.

### Expected Blizzlike Behaviour

https://wowwiki-archive.fandom.com/wiki/Quest:Timbermaw_Ally

Finding no data that this quest suppose to be repeatable.

### Steps to reproduce the problem

Took the quest at level 50ish
Completed the quest at level 59
Noticed the quest item was given and the quest became repeatable without the item
Turned in 1 more time, went to northern Felwood to farm rep
Returned to turn 2 more times to see it the quest would stop after Honored

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. There are two quests called "Timbermaw Ally." One is ID 8640, which is a once-only quest giving 1400 rep. That then leads on to the next quest, [ID 6131](https://wowpedia.fandom.com/wiki/Timbermaw_Ally_(RRQ)?oldid=1786990), which Wowpedia claims is supposed to be repeatable up until Neutral. However, in the past I've found these claims of when rep rewards should stop working vary widely from site to site, so I don't trust it very much. Other sources seem to indicate that the repeatable quest (ID 6131) shouldn't even exist. This is all complicated by the fact that these quests were reworked and rep changed a couple of times. So far I haven't found any unambiguous sources clear enough to decide how these should work. Wil, put this down as needing more research for now.

Starter quest: https://tbc.wowhead.com/quest=8460/timbermaw-ally and https://wowwiki-archive.fandom.com/wiki/Quest:Timbermaw_Ally?oldid=2226365
Repeatable quest: https://tbc.wowhead.com/quest=6131/timbermaw-ally and https://wowwiki-archive.fandom.com/wiki/Quest:Timbermaw_Ally_(RRQ)

https://wowwiki-archive.fandom.com/wiki/Timbermaw_Hold?oldid=2395742
Previous AC report: https://github.com/azerothcore/azerothcore-wotlk/issues/6990

**Comment by Shineslippers** [comment]
This report have logic because of some other circumstances.

[Wowhead](https://www.wowhead.com/faction=576/timbermaw-hold#comments:id=705724) big comment about rep. You can not getting reputation by killing NPC from revered. Only [Overlord Ror](https://wowgaming.altervista.org/aowow/?npc=9464), [Ragepaw](https://wowgaming.altervista.org/aowow/?npc=14342), [Chieftain Bloodmaw](https://wowgaming.altervista.org/aowow/?npc=9462), [High Chief Winterfall](https://wowgaming.altervista.org/aowow/?npc=10738) and [Xandivious](https://wowgaming.altervista.org/aowow/?npc=15623) should give reputation on kill up to exalted. Which is not correct right now on AC. There is 15 creatures have `maxstanding1 = 7`

<details><summary>Spoiler</summary>

| creature_id | rewonkillrepfaction1 | maxstanding1 | 
| ---: | ---: | ---: | 
| 7153 | 576 | 5 | 
| 7154 | 576 | 5 | 
| 7155 | 576 | 5 | 
| 7438 | 576 | 5 | 
| 7439 | 576 | 5 | 
| 7440 | 576 | 5 | 
| 7441 | 576 | 5 | 
| 7442 | 576 | 5 | 
| 10916 | 576 | 5 | 
| 14372 | 576 | 5 | 
| 7156 | 576 | 6 | 
| 7157 | 576 | 6 | 
| 7158 | 576 | 6 | 
| 6184 | 576 | 7 | 
| 6185 | 576 | 7 | 
| 6188 | 576 | 7 | 
| 6189 | 576 | 7 | 
| 6651 | 576 | 7 | 
| 9462 | 576 | 7 | 
| 9464 | 576 | 7 | 
| 10199 | 576 | 7 | 
| 10738 | 576 | 7 | 
| 11516 | 576 | 7 | 
| 11552 | 576 | 7 | 
| 11553 | 576 | 7 | 
| 11555 | 576 | 7 | 
| 11557 | 576 | 7 | 
| 11558 | 576 | 7 | 
| 14342 | 576 | 7 | 
| 15623 | 576 | 7 | 

</details>

```sql
SELECT cor.creature_id, cor.rewonkillrepfaction1, cor.maxstanding1
FROM `creature_onkill_reputation` cor
WHERE rewonkillrepfaction1 = 576
```
Reputation guides doesn't saying anything about this quests. Everyone pointing to gathering quest item. Same reputation tab on wowwiki page have only 3 repetable quests

![Capture](https://user-images.githubusercontent.com/85256266/145252931-8dd69835-c9bf-48f2-b7fd-750b7382e839.PNG)

One more wowhead [comment](https://www.wowhead.com/faction=576/timbermaw-hold#comments:id=880681)
> By Tony1234567890 on 2009/12/02 (Patch 3.2.2)
@ 11,999/12,000 all rep per kill halts so save all feathers tell exalted. By the time you hit that you should have close to 300 feather or more if you had better luck then I did(if I even had any). This is the last faction I'm working on for my diplomat and its by far the lamest... farming underbog for hybiscus or whatever it was did suck to but definitely not as much as this.
SO SAVE ALL YOU'RE FEATHERS TELL REVERED!
oh and chieftain Bloodmaw still gives u 60 rep per a kill, ha

**Comment by cachocarne** [comment]
Wowhead comment seems to indicate the repeatable quest should exist:
(Patch 1.9.4)
"The quest as all repeat rep quests does give XP ---> the first and only the first time you complete it... After that you are doing it just for rep"

As pointed above, there is a "first" version of this quest, 8640 and then you can repeat the [6131](https://wotlk-twinhead.twinstar.cz/?quest=6131). Something else is that it might be ignored on guides, since it's not so optimal for effective grind, since the mobs in the north and Winterspring will work better.

Could have some more information on this page:
https://wowpedia.fandom.com/wiki/Timbermaw_Hold_(faction)

**Comment by cachocarne** [comment]
https://gitanswer.com/quest-timbermaw-ally-is-currently-repeatable-for-way-too-much-rep-gain-azerothcore-wotlk-c-946568564

**Comment by chaossonic** [comment]
I will start pouring through patch notes then.  Maybe an undocumented changed?

In my experience of WoW I've never encountered this with this quest.

Otherwise considering how the grind would play out, this would be the fastest way to Exalted.  Lower level mobs with a drop rate on feathers similar to northern counter-parts, then this quest turn in.

**Comment by godnesso** [comment]
To clarify: with Patch 1.9, there was a revamp of Timbermaw Hold quests.
https://wowwiki-archive.fandom.com/wiki/Patch_1.9.0#Quests_.26_Reputation

_Old quests have been revised, and several new quests involving the Timbermaw Furbolgs have been added._

Prior to Patch 1.9, there were three repeatable quests related to the Timbermaw Hold reputation, using the IDs 6131, 6221 and 6241.

With the quest revamp in Patch 1.9, these three quests were removed and replaced with today's quests where you kill the furbolgs once and get rewarded with a piece of gear and the ability to collect and repeatedly turn in reputation items (feathers in Felwood and beads in Winterspring).

The only issue here currently is that quest 6131 is incorrectly unlocked after completing 8640. You are not supposed to see the quest 6131 in the first place. Reputation guides do not mention this way of rep farming - because it was removed and no longer exists.

**Comment by Salehyn** [comment]
Can confirm what godnesso wrote above, the kill quest should be a once-off and the repeatable quests are for 5-5 quest items. Not sure how it worked on classic because I don't remember this quest 6131 existing even on vanilla servers, but they definitely shouldn't exist on wotlk.

**Comment by Cythisiax** [comment]
https://www.wowhead.com/wotlk/quests/name:Timbermaw+Ally exists for WOTLK, and is repeatable after initial kill quest. 6131 is repeat, 8460 is kill/end.
