### ISSUE TITLE
[Silithus - Rare] Krellack dropped no loot when killed

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#2603]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

![WoWScrnShot_121621_134824](https://user-images.githubusercontent.com/80590226/146375218-fd7a1b17-873f-4389-9266-0c362fa14aab.jpg)

Dropped literally nothing, should always drop any item.

### Expected Blizzlike Behaviour

https://wowgaming.altervista.org/aowow/?npc=14476#drops

### Steps to reproduce the problem

1. Find Krellack in Silithus
2. Kill
3. No loot

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by cachocarne** [comment]
There is absolutely no item with 100% drop. So the chance that it drops nothing exists.
https://wotlkdb.com/?npc=14476#drops

**Comment by Elexias** [comment]
Not sure about your wow experience, but on retail whenever you kill RARE it always drops green, absoluetly one of green item is guaranteed. Having 0 loot is suspicious.

**Comment by Stump876** [comment]
Did you find a source for this?

> Not sure about your wow experience, but on retail whenever you kill RARE it always drops green, absoluetly one of green item is guaranteed. Having 0 loot is suspicious.

**Comment by godnesso** [comment]
It is common knowledge that every rare type mob will at least drop a guaranteed uncommon item (green quality). There are exceptions for certain lower level mobs where there will be common but guaranteed drops. This issue extends to almost every rare mob in vanilla zones currently. Krellack for example will at least drop a green item appropriate for its level range when killed.

https://wowpedia.fandom.com/wiki/Rare_mob?oldid=2493075
(older version taken from 2010)

**Comment by Stump876** [comment]
Don't misunderstand, I agree 100%, and I've had this argument with the devs. See https://github.com/chromiecraft/chromiecraft/issues/583 and I have many screenshots of rare spawns dropping nothing.
But unless you have a source that states that the mob in question drops something 100% of the time, it will not be changed.

**Comment by godnesso** [comment]
How is it expected to find a source for most open-world rare mobs always dropping loot? One person claimed in that report linked that they will not always drop one in classic wow live, but failed to provide proof (something which would immediately make report like this invalid). Wowhead and other databases are using user-supplied data which is prone to errors, of course no item is a 100% drop rate when the rare in question would drop any random green in a level from from -5 to +0 of its level. The wowwiki pages and most other discussions all date to Cataclysm+ where raremobs were drastically changed in their mechanics. The intended game design is to get rewarded with good loot when you find a rare mob, a loading screen tip even suggests this and this is continued in TBC and WotLK. That's the whole point of rare mobs. Why else are they rare? The only way to continously prove or disprove a rare mob dropping loot not 100% of the time is going on live servers and killing them until you have no loot dropping, which is not feasible because a) this isn't going to happen b) rare spawntimers are multiple hours long and c) god knows how many attempts you need to make until you have satisfying amount of data. this argument is done in bad faith - unless you don't want to rework hundreds of rare mob loot tables, then i'd understand.

**Comment by Elexias** [comment]
Rare always drops something gear wise, sometimes 3 greens, sometimes 1 white 1 green sometimes 1 white but always has loot. You could just implement loottable from DB of other wotlk server and just make rare always drop atlast 1 of items. Not hard.

**Comment by Elexias** [comment]
@Stump876 Point is that we can't say what he drops for 100%, but that he drops SOMETHING 100% always.
