### ISSUE TITLE
Mining Nodes: Multiple Mining Veins Spawn in same locations - Searing Gorge

### ISSUE THREAD

**Issue by Buggyswires** [chromiecraft/chromiecraft#268]
##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Mining node with double spawns in Searing Gorge:
GUID 13216 + 13220 (Gold and Mithril)
GUID 34904 + 64839 (Mithril and Dark Iron)
GUID 29289 + 56790 (Small Thorium and Dark iron)
GUID 32285 + 64843 + 65291 (triple spawn: Truesilver, Dark Iron, Mithril)

Spawns in the stone:
GUID 154  (Small Thorium, near GUID 29289 + 56790)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only one spawn at a time

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Searing Gorge, 
2.  one is the node next to the Alliance Flightmaster
3. 
4.

##### EXTRA NOTES:

from .gobject near:

1) GUID 13216 + 13220 
2) GUID 34904 + 64839
3) GUID 29289 + 56790
4) GUID 154
5) GUID 32285 + 64843 + 65291

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gurveleg** [comment]
Hello, I found more bugs in Searing Gorge that werent listed here so I'm just writing them in the comment instead of opening new issue (since it is still open).

Additional Multiple Spawns in same location:
GUID 373, 10214 (Small Thorium, Dark Iron)
GUID 33606, 34816 (Gold, Mithril)
GUID 10004, 35299 (Mithril, Truesilver)
GUID 5850, 7234, 9535, 58117 (Gold, Mithril, Truesilver, Dark Iron)

Spawned in the ground beneath rocks:
GUID 154 (Small Thorium)

Nodes spawned too close to eachother (probably all possible spawn locations are spawned at the same time)
GUID 5942, 31959 (Gold, Mithril)
GUID 9380, 244 (Truesilver, Small Thorium)
GUID 9595, 9596 (Truesilver)
GUID 6143, 33139 (Iron)
