### ISSUE TITLE
Combat issue - Defias NPCs

### ISSUE THREAD

**Issue by claymore147** [chromiecraft/chromiecraft#27]
##### SMALL DESCRIPTION:
Defias Thug in Nortshire: When you start attack some of them, they will continue walking for a while. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
NPCS's should execute its default walking route immediately upon entering combat.

##### CURRENT BEHAVIOUR:
Defias thug after entering combat in some cases keeps walking on its default route. This phenomenon lasts for about 0.25-0,5s, NPC will finally attach to the player after this time.
![WoWScrnShot_013121_132926](https://user-images.githubusercontent.com/78303208/106384345-a227e800-63ca-11eb-9b3e-a7b6e27c2811.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Well, I dont know. 
2. Defias Thug
3. Based on my experience with other private servers, I recommend to check all Defias NPCs, here is the list: https://wotlk.evowow.com/?search=defias#npcs

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacaw** [comment]
I can't reproduce this, I engaged a couple of them, but they keep attacking me and not starting to walk.
Let's keep this open, until someone else can get this reproduced.

I found something weird as well, maybe it's still related because it's in the same-zone + same-type of npcs.
There are 2 weird npcs: 1 male and 1 female that after 1-2 min they start to rush to some points and back.

Male-NPC:
![image](https://user-images.githubusercontent.com/6963500/106513853-2b7b0f80-64dc-11eb-8357-4df539de9e2d.png)

Female-NPC:
![image](https://user-images.githubusercontent.com/6963500/106513938-4baace80-64dc-11eb-89a8-c3e0a3f913f4.png)

The exact-location:
![image](https://user-images.githubusercontent.com/6963500/106513964-549ba000-64dc-11eb-88a9-72f7e76e9bc3.png)

**Comment by claymore147** [comment]
Hello,
I can make a video, attack all Defias thugs in this zone and make
statitistic in excel if it is desired.
But before this, does NPCs with same name have amy identification factor
that specifies them from their copies? Like identification number, etc...
For example: Defias Thug #1, Defias Thug #2....

Dňa po 1. 2. 2021 o 21:25 Hacaw <notifications@github.com> napísala(a):

**Comment by Helias** [comment]
I will appreciate it a lot, but please, wait for the next update, it will affect the behavior of all NPCs

**Comment by Stifler82** [comment]
It seems fixed to me, this is the **Video** of my **Test**: [Defias NPCs](https://youtu.be/_e6Q6Wtkcwg)
