### ISSUE TITLE
Milly's harvest quest

### ISSUE THREAD

**Issue by claymore147** [chromiecraft/chromiecraft#28]
##### SMALL DESCRIPTION:

During progress of Milly's Harvest quest, I have noticed that distance required to gather objective is too long.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I am not sure, what required distance for gathering objective is required, but I assume it is half of the current distance. 

##### CURRENT BEHAVIOUR:

Gathering items from the ground is possible from too long distance.
Same applies for mining veins as I have investigated. 

This photo is for demonstration from what distance I am able to gather quest item.
![WoWScrnShot_013121_131423](https://user-images.githubusercontent.com/78303208/106394946-cc47cd00-63ff-11eb-9030-7b438e1e2493.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. I dont know wich commands to use, maybe you could make some tutorials on this topic, I would help you as possible.
2. Questline starts at NPC Deputy Willem, however there are more quests that needs to be completed before getting to this questline.
3. My recommendation is to cut in half distance required to gather items. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
confirmed even for other gameobject, it's not only for this gameobject.
we will see how improve this ;-)
![image](https://user-images.githubusercontent.com/519778/106399592-e68ea480-6419-11eb-8706-e08eb76ccbfd.png)

**Comment by Stifler82** [comment]
**Video "Fix" and Test:** **[Gameobject](https://youtu.be/v4VDOW92ys0)**

So, I have **"Fixed"** the problem **locally**, the problem is that this is not: **neither a CORE Fix**, **nor a DB Fix**.
Unfortunately **it is a Client Bug** that affects this game mechanic.

(I didn't show it in the video), but I also tried to import the Spell **[Opening](https://wotlk.evowow.com/?spell=3365)** into the **"spell_dbc"** table and also to import the **spell.dbc file (modified)** into the **"dbc" folder** of the emulator **"AzerothCore"**, but **it doesn't work**.
This means that **"The Game Client" FULLY IGNORES the indications of the CORE and DB**
