### ISSUE TITLE
Quest text: Sarkoth

### ISSUE THREAD

**Issue by Ruralor** [chromiecraft/chromiecraft#295]
![WoWScrnShot_032621_090925](https://user-images.githubusercontent.com/81405682/112590624-308d7880-8e14-11eb-8943-1359ec6ae218.jpg)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Type here.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@Ruralor 

`$n` it is a code that uses the DB to say the Name of the character, the quest is working, you have seen "Unknown", because you don't clear the Cache folder before logging into Game.

![aaa](https://user-images.githubusercontent.com/1884642/112605870-ac38f680-8e0f-11eb-9c8a-8e2de0166389.png)
![WoWScrnShot_032621_084337](https://user-images.githubusercontent.com/1884642/112605942-bce96c80-8e0f-11eb-810e-9fb237ce7899.jpg)
