### ISSUE TITLE
Quest [How Big a Threat?]

### ISSUE THREAD

**Issue by Plan414** [chromiecraft/chromiecraft#3188]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The Quest [[How Big a Threat](https://wowgaming.altervista.org/aowow/?quest=984)?] Part 1/2 is allowing me to accept the quest but not allowing me to turn it in when complete. 

![image](https://user-images.githubusercontent.com/62799885/157521756-6b7bd521-343f-4e7a-be82-4d156fa823f8.png)

### Expected Blizzlike Behaviour

This quest should be turned into Terenthis.  

https://wowgaming.altervista.org/aowow/?quest=984

### Source

https://wowgaming.altervista.org/aowow/?quest=984

### Steps to reproduce the problem

Accept the quest.
Complete the objective
Try to complete the quest. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0e35b681fb74045953b0babae5273f121dcaa05f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Rubadubscrub** [comment]
Happening for me too, including on a stock client
![image](https://user-images.githubusercontent.com/11332559/157523181-ac619900-3b11-4097-b150-5ec778f60698.png)

**Comment by Plan414** [comment]
After the NPC Grimclaw came and an RP event happened. I can now talk to the NPC and turn in my quest.

**Comment by Kosiak** [comment]
Now this quest is broken a bit. Before you complete this quest u will need to wait for Grimclaw to arrive and do RP event then u will be able to complete quest and take next one. I spoke with one of the dev guys and i hope they will sniff more data and we will be able to sort it out properly.

**Comment by Dejanos** [comment]
I just waited a little bit in the camp killing Corrupted Fulborgs and then came back and could complete the quest no problem, perhaps RP played out in my absence
![WoWScrnShot_040622_170032](https://user-images.githubusercontent.com/100415626/162007013-a74e7f91-d247-4e97-9dc4-ba584f6c2f06.jpg)

After that went on to kill the Bears and went back and handed that one in with no problems also

![WoWScrnShot_040622_170645](https://user-images.githubusercontent.com/100415626/162007087-07ab260c-6999-4848-bbae-f55690f96e73.jpg)

**Comment by Kosiak** [comment]
Short version: Grimclaw is broken at the moment. I wont go explaining in here again. U can check my comments in #3188 and #3216.

**Comment by Gultask** [comment]
I was able to replicate the issue once, but not twice, weirdly enough.
When I went to turn in How Big A Threat? (Part 2/2)(Quest ID: 985) The RP event had already started (I think Dejanos might've just turned the quest in). After waiting for the RP event, I turned in the quest and followed the Grimclaw that had just left after the event had ended, finding that their pathing is broken.
After reaching a certain point, a second Grimclaw had spawned and started their event. When the two met, they joined up together.
![WoWScrnShot_040622_124007](https://user-images.githubusercontent.com/100873791/162016600-f4ce434d-5d59-4887-b4aa-23d1fb01cba8.jpg)
![WoWScrnShot_040622_124011](https://user-images.githubusercontent.com/100873791/162016619-c99c2e07-a749-4569-9616-61b64f8f6d5c.jpg)

When both got to Terenthis, Grimclaw2 started and completed the RP event while Grimclaw1 went back immediately, despawning near the building.
Curiously, only the first line of the RP event had repeated.

Pictured: Grimclaw1, battered from aggroing mobs due to broken pathing, going away immediately and soon despawning
![WoWScrnShot_040622_124354](https://user-images.githubusercontent.com/100873791/162017080-e0d78f9d-a509-44e8-9249-6eb82f429458.jpg)

After that, I turned in the quest a THIRD time. However, this time, another Grimclaw did not spawn. The RP event was done entirely by Grimclaw2, that returned to the spawn location and turned around to complete it again. After Grimclaw2 reached Terenthis, the first line played and Grimclaw2 immediately left and despawned
Pictured: Grimclaw2 despawning, note the very faint image of a bear to the left of this character.
![WoWScrnShot_040622_125301](https://user-images.githubusercontent.com/100873791/162017860-5c4fc36b-7ebe-44f1-919f-7da60053fad2.jpg)

After this Terenthis, and the RP event, broke completely.
Only the first line of the event played, and Terenthis didn't become interactable again after this.
![WoWScrnShot_040622_130257](https://user-images.githubusercontent.com/100873791/162018124-61f6fbc0-0c3d-45eb-80de-063209c6242a.jpg)

Screenshot: Broken pathing of a Grimclaw returning to their original spawn after completing the RP event.
![WoWScrnShot_040622_124455](https://user-images.githubusercontent.com/100873791/162018315-c53ab980-e785-44cc-b415-15fdfb6687aa.jpg)

**Comment by Gultask** [comment]
This issue gets more confusing every day. I tried to go through it once to make sure how it should work normally, but instead I had up to 3 Grimclaws spawn during the time I tried to complete quests 984 and 985, sometimes going the correct path and sometimes going the opposite, and broken, way. Throughout the entire questline there were Grimclaws somewhere in the world, sometimes 2 at once.
I'm certain that the fault lies with Grimclaw somehow, but I can't find a way to reliably reproduce the bug in the PTR.
