### ISSUE TITLE
Transmog set bonus visual bug

### ISSUE THREAD

**Issue by manyberries** [chromiecraft/chromiecraft#3311]
![image](https://user-images.githubusercontent.com/89465352/162578494-40179a95-410a-4994-9007-95eb7d8d53ac.png)

As you can see, it says I have 7/8, while I obviously miss 2 items on me (legs and chest), however I have them transmoged on equipped items.

Set bonuses do not count, even though they are visually shown as counted, until I actually equip a number of set bonus required items.

This is on current live version.

**Comment by Gultask** [comment]
Thanks for your report, menyberries!
This is a known client-side **visual** bug that occurs because your client thinks that the transmog items are equipped, even though they are not. Unfortunately, there is no known way to fix this currently.

See https://github.com/chromiecraft/chromiecraft/issues/3301 and the other post linked there for more info.
