### ISSUE TITLE
Deterrence does not parry while casting scare beast

### ISSUE THREAD

**Issue by LisperH** [chromiecraft/chromiecraft#3331]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

While casting scare beast with deterrence aura up, hunters take damage from attacks.

### Expected Blizzlike Behaviour

Hunters are able to cast scare beast with deterrence up, without taking damage as normal.

### Steps to reproduce the problem

1. Use deterrence, and cast scare beast while being attacked by a hunter pet.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Linux

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Lisper, thanks for the report!

Can confirm that casting Scare Beast does indeed make you vulnerable to attacks **but not to ranged** spells even while Deterrence is up, meaning that you cannot parry, but can still deflect spells.
I'll try to look for more info and maybe a source before confirming the issue.

**Comment by slicplaya** [comment]
Sounds like a problem with not being able to "block" when casting. But in this case, it seems to be unable to parry when casting in deterrence. Also, which specific attacks were hitting the hunter? Cuz some attacks get through.

**Comment by bonfax4** [comment]
From what i gathered only attacks that deterrence shouldn't stop are abilities that specifically can't be parried like overpower and abilities that have the requirement for you to be behind the target (backstab, cheap shot , etc). Went through alot of mmo-champion posts and no one mentions attacks bypassing while casting even tho slicplaya is correct about casting nullifying all avoidances.

**Comment by Gultask** [comment]
> Also, which specific attacks were hitting the hunter? Cuz some attacks get through.

Oh yeah I should've mentioned what I was testing with. It was simple melee attacks from hyppogryphs in Azshara since they were the closest and thus the most convenient mob to test with. So yeah, any spellcasting currently makes the hunter vulnerable t**o melee attacks only** because they're not able to parry while blocked.

**Comment by slicplaya** [comment]
> > Also, which specific attacks were hitting the hunter? Cuz some attacks get through.
> 
> Oh yeah I should've mentioned what I was testing with. It was simple melee attacks from hyppogryphs in Azshara since they were the closest and thus the most convenient mob to test with. So yeah, any spellcasting currently makes the hunter vulnerable **to melee attacks only** because they're not able to parry while casting.
> 
> And I forgot to mention: I've been looking all over and found **nothing** not even PvP videos with a Deterrence + Scare Beast combo being used against druids or other hunters, which would be the most relevant cases since I don't know of any other hunter spell that has a cast time.
> 
> edit: Here's how Deterrence was implemented in Azerothcore: [azerothcore/azerothcore-wotlk#1694](https://github.com/azerothcore/azerothcore-wotlk/pull/1694)

That's because if you deterrence to scare beast they'll just shred spam you :D

**Comment by Gultask** [comment]
> That's because if you deterrence to scare beast they'll just shred spam you :D

Oh I didn't know that Shred bypasses Deterrence! That clarifies things a bit.

This [MMO-Champion thread](https://www.mmo-champion.com/threads/856886-so-no-more-shredding-thru-Deterrence) talks about one of the early Cata patches making shred not bypass Deterrence anymore because it was changed from 100% parry chance to 100% miss chance. 
But since Deterrence changed in Cata we can't take videos about it as proof, though.

**Comment by bonfax4** [comment]
https://web.archive.org/web/20110714230629/http://www.wowhead.com:80/spell=19263/deterrence
4.0.3 comments before parry being changed into miss : 

> Ah, looks like this has been changed yet again. Apparently, we can now use Tame Beast while using Deterrence. However, it reportedly will not parry anything when you're channeling Tame Beast, which is odd.

> You've never been able to Dodge, Block, or Parry anything while channeling a spell.

Patch [4.0.6](https://wowpedia.fandom.com/wiki/Patch_4.0.6) comment (Parry replace with Miss chance change was applied) :
> You can effectively swap out pets while under detterence now.
> Before it wouldn't work because you can't parry/dodge while casting.
> Great for BM in arena as if you stack spirit beasts you can pull out a 2nd and grab another free heal and CotW/rabid

There's no guarantee they didn't make any change to the spell before those cata patches since they sometimes hotfix without posting on changelogs but seeing how disarm and cheap shot also nullified deterrence parries during wotlk i'm more inclined to believe this behavior is intended. Tried to look for videos of this with no luck sadly.

Unrelated observations:
[Shred, pounce , ravage ](https://wotlkdb.com/?spells&filter=cr=60:45;crs=1:4;crv=0:0) from druids should bypass deterrence pretty much. 
Weird how shaman's stormstrike ( debuff maybe ?? ) and warrior's slam also have the "Cannot be dodged, parried or blocked" flag on wotlkdb site.

**Comment by Gultask** [comment]
Yep,
> [Slam cannot be dodged/parried/blocked. It has special attr - comes from Blizzard files. Not all spells have this mentioned in its descriptions/tooltips.](https://github.com/azerothcore/azerothcore-wotlk/issues/11289#issuecomment-1094298313)

I keep forgetting that Wowhead deletes comments from deleted accounts, it's my fault I missed that one.

Thanks, [bonfax4](https://github.com/bonfax4), you really helped me out I appreciate it. I think this is enough to rule as Blizz-like.
