### ISSUE TITLE
Talent - Rapture

### ISSUE THREAD

**Issue by Plan414** [chromiecraft/chromiecraft#3346]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

When the talent Rapture procs two things are happening which I believe are not correct.

1. The Priest is forced into combat. 
2. Threat is generated towards the Priest. 

This is a problem at lower levels when you shield a tank prior to a large pull.
If the tank face-pulls many mobs and then the shield breaks, the priest now has top threat. 

### Expected Blizzlike Behaviour

If Rapture procs the priest should not enter combat and should not generate any threat. 

### Source

I tried looking for this specific thing, but could not find anything.

### Steps to reproduce the problem

1. Be in a party with another player.
2. Shield player 2.
3. Have player 2 face-pull enough mobs to break the shield.
4. Wait for the shield to break and rapture to proc.
5. Observe the results.  

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4ac565699fcb7b88fcc15db97ec9f14a0894f331

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hello, Plan414, thanks for your report!

I haven't found any sources either, but I did, however, found out a couple of things about Rapture from testing.
Rapture generates threat when the target is energized (generates resources when PW:S is broken). I could confirm this because I also found that **the target isn't energized if your line of sight to them is blocked**, and if they're not energized, then no threat is generated.

Proof:
LoS unobstructed, generating rage and threat.
https://user-images.githubusercontent.com/100873791/163283612-d2d9c77d-00ef-47f6-8c21-c24ee72e2ae3.mp4

LoS obstructed, not generating threat or entering combat.
https://user-images.githubusercontent.com/100873791/163283696-da3cb7a6-49b4-401c-a555-60c02db61750.mp4

**Comment by Talthos** [comment]
Mana-restoring effects in general appear to be generating threat on this server (even mana potions are generating threat), and I'm not sure if that's accurate to retail.

Perhaps this can be another thing for me to test on TBC Classic, once I get around to re-activating my subscription there...

**Comment by bonfax4** [comment]
https://wowwiki-archive.fandom.com/wiki/Threat?oldid=2223120 It does seem to ne the case that mana gained generates threat. there could be exceptiosn tho but im not sure.

"Threat caused by beneficial effects is divided amongst all NPCs that are aware of the character. This global threat applies to heals, bonus threat from buffs (such as [Battle Shout](https://wowwiki-archive.fandom.com/wiki/Battle_Shout) or [Arcane Brilliance](https://wowwiki-archive.fandom.com/wiki/Arcane_Brilliance)), and power gains (such as a [Mana Potion](https://wowwiki-archive.fandom.com/wiki/Mana_Potion) or [Rage Potion](https://wowwiki-archive.fandom.com/wiki/Rage_Potion))."

**Comment by Gultask** [comment]
Now, this is all speculation on my part since I don't know how spells work in WoW, but I think the problem is that the Rapture proc is currently considered a spell cast, from the priest to 2 targets, themselves and their tank. And that could be why LoS breaks one half of the proc and why, if it's successful, it generates threat because the priest has technically cast a power gain spell on the tank that is in combat.
