### ISSUE TITLE
Improved Water Shield not proccing with critical hits, even with riptide

### ISSUE THREAD

**Issue by Awkakelen** [chromiecraft/chromiecraft#3471]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Row 3 talent in restoration shaman's tree says, that If I critical strike from my Riptide, I should have 100% guaranteed water totem consume. When I hit crit with it or any other healing spells (less likely but still there's a chance), nothing happens

### Expected Blizzlike Behaviour

My one globe should be taken off and I should be granted mana from its consumation, EVEN when I am full HP

### Source

![obraz](https://user-images.githubusercontent.com/12753422/167241361-787914d6-ff49-4f54-9d8b-40de8b1c427c.png)

### Steps to reproduce the problem

1. get yourself a resto shaman
2. ask him to put him water shield
3. wait him to heal himself 
4. ...
5. Nothing happens, globe from the water shield isn't wearing off giving him mana

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/283ce18bb7b961264eae983a401aaacb89725273

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Hello, Awkakelen.  I have just tested and research the talent, and tried doing some critical heals on the PTR, upon my tests, each critical indeed granted me mana (100% chance on Healing Wave or Riptide crit, 60% on Lesser Healing Wave and 30% on Chain Heal critical).
![improved water shield](https://user-images.githubusercontent.com/100415626/167251112-371a4529-5cab-457f-8619-bba22fa44054.png)

A numerous sources, I will link the one from WoWwiki Fandom point out that from the patch 3.2.0. Charges of Mana Shield are no longer consumed, but still give mana on criticals as if the orb was consumed, depending on the spell and proc chance.
![Charges not consumed](https://user-images.githubusercontent.com/100415626/167251176-aefa521d-9aa7-4eb5-ba6d-468eb895f688.png)


Here are my tests from the Healing Wave and Riptide:
![Riptide](https://user-images.githubusercontent.com/100415626/167251156-96ccbb6a-eb62-4f26-aa81-e86bce7b5138.png)

![Khalder water shield](https://user-images.githubusercontent.com/100415626/167251168-8d15503e-990c-43ab-99e8-9d7ef80b24e5.png)

So reading those WoWhead comments we can indeed confirm the charges proc on critical hits (but nowhere does it say they were consumed, since the comments are from the patch 3.2.2 and they should not be).

So I think we have this cleared out pretty much unless I misunderstood something you stated, if not, this issue can be closed.

**Comment by Awkakelen** [comment]
> 

Yeah, I see this now perfectly, thank you and sorry for giving you guys another problem!

**Comment by Dejanos** [comment]
> > 
> 
> Yeah, I see this now perfectly, thank you and sorry for giving you guys another problem!

No problem, if you encounter an issue don't hesitate to report.
