### ISSUE TITLE
Wailing Caverns - combat issue

### ISSUE THREAD

**Issue by claymore147** [chromiecraft/chromiecraft#35]
##### SMALL DESCRIPTION:

Right after killing [Verdan the Everliving](https://classic.wowhead.com/npc=5775/verdan-the-everliving#abilities;mode:normal) NPC, players left in permanent combat. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When there are not NPC's with aggro on any of the dungeon participants left, players should not be in combat.

##### CURRENT BEHAVIOUR:

After killing [Verdan the Everliving](https://classic.wowhead.com/npc=5775/verdan-the-everliving#abilities;mode:normal) NPC, players are in combat. This combat state can be broken only by death of all dungeon participants or by leaving dungeon thru its entrance by all participants and at the same time.
![combat](https://user-images.githubusercontent.com/78303208/106916436-7462dc00-6707-11eb-93a9-cf71a2c35640.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Location: [Wailing Caverns](https://wotlk.evowow.com/?achievement=630) (Barrens)
2. NPC: [Verdan the Everliving](https://wotlk.evowow.com/?npc=5775)
3. Bug may be related to NPC's AoE spell [Grasping Vines](https://wotlk.evowow.com/?spell=8142) or subsequent spell [Knockdown](https://wotlk.evowow.com/?spell=5164).

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
I have tried this Boss several times and neither the Boss or the MOBs near the Boss, don't leave the character in combact.
So the Bug is non-existent.

The Bug exists in another form that is not related to either the instance or the MOBs in it.

The fact of remaining "in a Combat Status" is due to a random error of the CORE related to the aggro system and the Pathfinder system of the Mobs based on random actions of the Players, so it is not due to the instance or to the MOBs residing in it, is something that occurs in a "random" way.
