### ISSUE TITLE
Terror Wing Path not unlocking for Explore Burning steppes

### ISSUE THREAD

**Issue by Rubadubscrub** [chromiecraft/chromiecraft#3555]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Despite being in Terror wing path, the location doesnt unlock for the explorer achievment 
![image](https://user-images.githubusercontent.com/11332559/170771511-afcbc374-7ed8-400b-a116-3b4569d6d1e3.png)
![image](https://user-images.githubusercontent.com/11332559/170771782-1dcc1552-b162-46a7-9482-47ed7aa1cf32.png)

### Expected Blizzlike Behaviour

Point should unlock and experience should be rewarded shortly after entering subzone

### Steps to reproduce the problem

enter Terror wing path from below near morgans vigil or above via Ruins of Thaurissan
Terror wing path subzone text should pop up
no xp and achievment wont progress

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Beefsteak, thanks for the report!

If you open the map, is the area 'discovered' for you or does it still have the fog of war? You'll need to disable any addons that remove the map fog.
This is the area:

![map](https://user-images.githubusercontent.com/100873791/170807838-4f116f0d-2c48-44a2-9d73-97add76b5d5c.jpg)

If it is already discovered, do you think you might've already discovered this area a few months ago? There was an issue that caused this, but it was fixed not too long ago, so it might've affected you.

If so, then your best bet would be to open a [#support-ticket](https://discord.com/channels/788063059926712341/888194705505017926) in the CC Discord and provide that info along with a screenshot of your Burning Steppes map without any addons enabled.
You can also provide this link to make things easier: https://wowgaming.altervista.org/aowow/?achievement=775

If this is the first time your character has reached that location, please tell us, because it could be a new bug.

**Comment by Rubadubscrub** [comment]
Its revealed on my stock client, ill submit a support ticket and see what they say
![image](https://user-images.githubusercontent.com/11332559/170824451-f8b3387a-4111-4f61-a65a-657c360842f0.png)

**Comment by r-o-b-o-t-o** [comment]
Hi there, fixed in-game with a `.achievement checkall`
