### ISSUE TITLE
Unexpected result, after failing mobs does not despawn

### ISSUE THREAD

**Issue by Jermuwolf** [chromiecraft/chromiecraft#3559]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When taking quest
Unexpected results, mobs spawn right and move right, but if somebody has failed this quest or abandoned. Mobs are there still. 

When taking quest you'll get another set of enemies spawned.

### Expected Blizzlike Behaviour

Despawn after fail.

### Steps to reproduce the problem

Take quest: Unxpected results
Fail.
Retake quest.

Old summon mobs are there, new ones will be summoned.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Hey, Jermuwolf. I just did the quest a couple of times, and was just wondering how can I fail it since I stand back the entire time and let Apprentice Mirveda fight alone, and she takes care of them no problem and it completes the quest. I am not sure if mobs should despawn once the quest is abandoned, as they have been summoned by the script on quest initiation already, probably the same thing if you die. 

However, I was able to die once I charged all of them before Apprentice Mirveda and rounded them up with Arcane Torrent aggro. The mobs should definitely stick around once they have killed both me and Mirveda, what's more, they join in the next wave once you re-take the quest.

Aggroing them again without re-taking the quest when you resurrect will render Mirveda useless as she will not join in in the attack, even if you pull all the mobs to her, she will also not be attacked by them.

I could not find a Blizzlike source anywhere stating they despawn upon failure, but I think it should be self-evident as it can lead to a possible exploit and gameplay disruption as a player can abandon and retake quest infinite amount of times to spawn as many Scourge minions as possible, (I ended up with around 20, as they are not despawning and all of them will attack you on re-taking the quest) [as I did in this video](https://streamable.com/wzrmum)

**Comment by Jermuwolf** [comment]
There was 2x boss and 4x other mobs already spawned when i took the quest. 
When i took the quest i did get 3x boss and 6x other mobs. 

Miverda died in under 10 seconds after i died. 
When it would be working. She should be able to solo it, but with that many spawns... She dies.
