### ISSUE TITLE
[Zone/Stormwind] Multiple overlapping bell sounds from hourly chime

### ISSUE THREAD

**Issue by Talthos** [chromiecraft/chromiecraft#3776]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The hourly bell chime in Stormwind has multiple overlapping instances of the bell audio being played (they aren't perfectly synced either, so it causes distortion), instead of just one audio instance for the entire zone.

### Expected Blizzlike Behaviour

There should only be one instance of the bell playing during an hourly chime in Stormwind, and it should be audible throughout the entire Stormwind zone.

### Source

(Unable to locate retail-era footage to fully verify my report. It may be necessary to record footage from WotLK Classic...)

### Steps to reproduce the problem

1. Sit in Stormwind until the next hour begins.
2. Listen to the bell chimes.
3. Notice that there are multiple overlapping instances of the bell chimes playing at the same time, instead of just one.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Hogofogo1** [comment]
Were you logged on multiple accounts while in Stormwind while listening?

**Comment by Talthos** [comment]
> Were you logged on multiple accounts while in Stormwind while listening?


No.

**Comment by anjachan** [comment]
Hello! I followed your steps and still couldn't reproduce the bug... Could you give me more info?
My reproduction: https://youtu.be/I9Y7B8KGxX0

**Comment by Talthos** [comment]
> Hello! I followed your steps and still couldn't reproduce the bug... Could you give me more info?

Did you test on the live server?

I will create a recording if I must.

**Comment by Talthos** [comment]
[Recording created.](https://www.youtube.com/watch?v=qYn1TW1u1to)

Also, for reference: The sound file used for the bell toll is "BellTollAlliance.wav"

Listen to it by itself, if you need a reference point on how it's supposed to sound.

**Comment by temperrr** [comment]
Thanks for the recording. The first and second chime sound the same to me.

**Comment by Talthos** [comment]
Would be nice if the devs could check the object emitters internally.

**Comment by The-GhostRider** [comment]
In this video I've increased the volume by 3x, and I haven't been able to find what you claim.

All audio we hear within the WoW Client comes from the WoW Client, not the Server.
All the Server does is trigger these Audios when they need to be output, and they are inside the Client's .MPQ Files.
So if you hear distortion, it's likely because you have a corrupt Client, I think a fresh install of WoW should fix it..
Or it might be a problem with your PC.

However, I can guarantee that: regardless of the reason that creates this problem for you, the reason is never Server side in this kind of thing.

https://github.com/chromiecraft/chromiecraft/assets/1884642/34b19242-c9e8-4f41-a040-90f9cd866905

**Comment by Foereaper** [comment]
> However, I can guarantee that: regardless of the reason that creates this problem for you, the reason is never Server side in this kind of thing.

This is inherently not correct at all, and a bad assumption to make. Sure, the client produces the audio, but in very many cases those audio queues are triggered by the server. In this specific case, with overlapping bell audio, it is specifically the go_bells game object script that triggers these sound effects.

Like mentioned above, chances are there's overlapping areas where players are within the sphere of two trigger objects.

**Comment by The-GhostRider** [comment]
@Foereaper 
You know, I value your critique of my work, and I understand that there may be some validity to your points **(Maybe)**. However, I would like to shed light on certain aspects that might not be evident in the 32-second video I shared.

Unseen in the video is the extensive effort I dedicated, investing over 3 and a half hours meticulously investigating the veracity of this 'Bug.' I painstakingly combed through every corner of Stormwind, with my headphones' volume amplified to 200% using the VoiceMeeter program, aiming to determine if the bug was indeed genuine.

Nevertheless, I maintain an open mind and a willingness to reevaluate my perspective if proven mistaken. Therefore, if you can provide concrete evidence substantiating the existence of this bug and showcasing the shortcomings of my assumptions, as you referred to them as 'bad assumptions,' I will gladly reconsider to reopen the report.
