### ISSUE TITLE
NPC's missing in Cenarion hold 

### ISSUE THREAD

**Issue by arthodin** [chromiecraft/chromiecraft#3867]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

Some npcs missing in Cenarion hold 
-Bor Wildmane
-Huum Wildmane
-Commander Mar'alith
and some more.

### Expected Blizzlike Behaviour

imposible to get necks and rings to kill dukes in silithus 

### Source

wowhead 

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d580ca4f316c66893ec76282c8dd3e0762d3f662

### Operating system

Ubuntu 20.04
windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by w32amir** [comment]
These NPCs are indeed missing on Chromie, however, they will spawn correctly in a local AzerothCore instance:

![WoWScrnShot_080222_230856](https://user-images.githubusercontent.com/81422240/182522309-943eed34-dfb0-48c3-bccd-c26c04c47193.jpg)

I don't think it's a progression issue since [Huum Wildmane](https://wowpedia.fandom.com/wiki/Huum_Wildmane#Patch_changes), [Commander Mar'alith](https://wowpedia.fandom.com/wiki/Commander_Mar%27alith#Patch_changes) and [Bor Wildmane](https://wowpedia.fandom.com/wiki/Bor_Wildmane#Patch_changes) were introduced in patch 1.8.0 (ZG, BWL, MC).

According to this past [issue](https://github.com/chromiecraft/chromiecraft/issues/2583), Huum Wildmane was missing at one point after a server restart and had to be manually respawned. Maybe that's the issue here as well?

**Comment by temperrr** [comment]
closed by https://github.com/azerothcore/mod-progression-system/pull/232
