### ISSUE TITLE
Buggy escort NPC and spawned mobs during Supplies to Auberdine quest

### ISSUE THREAD

**Issue by apav** [chromiecraft/chromiecraft#395]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

1. NPC [Feero Ironhand](https://wotlkdb.com/?npc=4484) is the NPC you escort during the [quest](https://wotlkdb.com/?quest=976), however he ignored all waves of mobs and just kept walking while I had to fight. I decided to kite the mobs to keep up with him and eventually the last mob leashed. I ran back to pull it and kill it quickly while walking back to the NPC before it leashed again and that was the one and only time he aggroed and fought them. 

2. The first wave of spawned mobs didn't attack unless you attack first. The other waves did not have this issue. 

3. About halfway through the escort, after the one time the NPC did aggro, he started started levitating and got frozen in this animation while moving. He did this for the remainder of the journey.

https://user-images.githubusercontent.com/8137930/114270887-c6143500-99dc-11eb-972b-92c4d43c3ab6.mp4

4. Just like the first issue, the last wave the mobs spawned and he kept walking past them. While I was still fighting he reached his destination, the quest completed, he said some dialogue and disappeared, leaving me to fight the mobs again.

https://user-images.githubusercontent.com/8137930/114270892-cca2ac80-99dc-11eb-82f0-e153bb16cf63.mp4

5. The last wave of mobs eventually despawned, before I could kill them all. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When each wave of mobs spawn they don't attack immediately (since they are ambushers and the NPC has dialogue about them), which is intended. However the escort NPC and ambushers should attack each other after he says his dialogue each time. Also the NPC shouldn't be levitating in this animation while walking. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept quest and escort NPC

##### EXTRA NOTES:

I've done a few other escort missions, even one that spawned enemies as part of the quest, and the other escort NPCs didn't behave like this. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mdawx** [comment]
If i understand it correctly you issued 5 things what was wrong, but in my opinion only 2 are relevant:
1. NPC do levitate during the quest.
2. NPC ignores fight on first and last wave of spawned mobs.

My reasoning: If he had helped you in fight event wouldn't ended as you described in (4) and (5).

Can you remove all irrelevant comments from the issue to make it **as short as possible**? It is very important, because everybody love to fix easy to understand issues :) TIA.

**Comment by FrancescoBorzi** [comment]
hello @apav and @mdawx . First of all, thanks for contributing.

A few notes from me:

- let's not remove the [Needs Triage] until the bug has actually been linked to AC, unless information is **missing** or the bug is not valid and should be closed
- about the short vs long description, the general rule is to try to add as many details as possible that can help the devs... yet trying to avoid including *unnecessary* information and make it longer than needed.

So @mdawx if you understood the issue, you can proceed validating it (i.e. checking on your local AC) and then open the report on the AC bugtracker. There you can strip any information that you believe is not necessary to reproduce the bug yourself, no need to wait for the original reporter to do this (in this case @apav ).

Things would be different if it was the opposite case: missing information. In that case we need to wait for the reporter to add whatever detail is missing in order to correctly reproduce and identify the problem.

I hope it's clear, let me know if you have questions ;)

**Comment by mdawx** [comment]
Hey @FrancescoBorzi. I will check it tomorrow, because it is late. I won't cut any information if author won't approve it. I assume reporters know the game better than me, so I don't want to take responsibility for cutting any relevant information.

**Comment by Stifler82** [comment]
I just checked the quest and it works, it no longer has the bug.
So I close.
