### ISSUE TITLE
ANUBISATH IN THE OSSIRIAM ROOM

### ISSUE THREAD

**Issue by Hajache** [chromiecraft/chromiecraft#4015]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

SOMETIMES, 2 MOBS CAN BE TOGETHER OR VERY CLOSE TO ONE OF THE OTHER, AND THEY GO WALKING TOGETHER... USING A ROGUE DISTRACT ON 1, IT LEAVE ONE PARALYZED AND THE OTHER KEEPS WALKING, AND THAT WAS THE WAY TO SEPARATE THEM, BUT IN THIS SERVER THE ANUBISATH ARE IMMUNE TO DISCTRACT, WHY? I DON'T KNOW

### Expected Blizzlike Behaviour

USING A ROGUE DISTRACT ON 1, IT LEAVE ONE PARALYZED AND THE OTHER KEEPS WALKING, AND THAT WAS THE WAY TO SEPARATE THEM

### Source

SOMETIMES, 2 MOBS CAN BE TOGETHER OR VERY CLOSE TO ONE OF THE OTHER, AND THEY GO WALKING TOGETHER... USING A ROGUE DISTRACT ON 1, IT LEAVE ONE PARALYZED AND THE OTHER KEEPS WALKING, AND THAT WAS THE WAY TO SEPARATE THEM, BUT IN THIS SERVER THE ANUBISATH ARE IMMUNE TO DISCTRACT, WHY? I DON'T KNOW

### Steps to reproduce the problem

.....

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519
1

### Operating system

Ubuntu 20.04
WINDOWS 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
can confirm they are immune, looking into a source to confirm 
![image](https://user-images.githubusercontent.com/11332559/194911880-84b93054-5fd7-4ef7-b846-57db5556321c.png)

**Comment by The-GhostRider** [comment]
Hello, based on my experience (since I started playing WoW from the "Reign of Chaos" expansion, if I recall correctly), some Elite creatures in Instances are immune to CC **"Crowd Control"** Spells, especially those found in level 60 Instances.


![1](https://github.com/chromiecraft/chromiecraft/assets/1884642/b5e0d6f6-f93c-4395-bba1-574faa13a8eb)

### LINK: **[Uncategorized creature](https://wowwiki-archive.fandom.com/wiki/Uncategorized_creature)**
![2](https://github.com/chromiecraft/chromiecraft/assets/1884642/cbc1026c-3ee5-41d1-ae98-eb84d95ca5c7)

### LINK: **[Crowd control](https://wowwiki-archive.fandom.com/wiki/Crowd_control)**
![3](https://github.com/chromiecraft/chromiecraft/assets/1884642/0baf8e88-c0d2-46c7-8604-4f3957a8bc07)


### **Video Test:** ⬇
[![Anteprima](https://user-images.githubusercontent.com/1884642/248410849-70a6bc57-99b9-433c-ba87-99260a2bd4dd.png)](https://www.youtube.com/embed/7Dpu3g2t1Fw)


For these reasons I close the Report.
