### ISSUE TITLE
[Scepter of the Shifting Sands QL] Doctor Weavil - Draconic for Dummies 

### ISSUE THREAD

**Issue by Elexias** [chromiecraft/chromiecraft#4031]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

![image](https://user-images.githubusercontent.com/80590226/188318846-46273635-126a-4c01-a363-4c8a8d3e1387.png)

Doctor Weavil should be mind controlling people and that is hardest part of fight, but now he is not using it at al..

### Expected Blizzlike Behaviour

He should be doing Mind controlls every 2 minutes, the first one being on 15 seconds after fight begins

### Source

https://www.youtube.com/watch?v=Nr3WHwpIMt0&ab_channel=Mathias
https://wotlk-twinhead.twinstar.cz/?npc=15552
https://classicdb.ch/?npc=15552
https://www.wowhead.com/npc=15552/doctor-weavil

### Steps to reproduce the problem

1. Get the raid group
2. Attack him
3. He does 0 mind controlls

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Hey, Elexias, thanks for the report!

Mind Control was being cast correctly for me, are there any other details that you could give us to help us reproduce the issue?

![image](https://user-images.githubusercontent.com/100873791/188328961-24d84b4a-b09a-4639-9b44-7efdf08724ce.png)

**Comment by Elexias** [comment]
Hello, we killed him three times, did 0 MC's.

**Comment by BeefSteaker** [comment]
fight was less than 2 minutes, but can confirm the first mind controll happened.

player in group was mind controlled and killed by friendlies
note damage from spells dr weavil doesnt cast
![image](https://user-images.githubusercontent.com/11332559/188645187-933303f7-75f7-492d-bc4e-de6bb7ae0752.png)

**Comment by The-GhostRider** [comment]
Hi @Elexias I have read both your report and all the comments,
I understand that your report refers to a problem with **"[Doctor Weavil](https://wowgaming.altervista.org/aowow/?npc=15552)"** not doing the "Mind Control", which is actually not "Mind Control" but "[Mental Domination](https://wowgaming.altervista.org/aowow/?spell=25772)" the correct Spell..
Up to here I got there.

What actually I didn't understand is the title and the correlation between "Doctor Weavil" and the Chain Quest: "[[Scepter of the Shifting Sands QL](https://wowgaming.altervista.org/aowow/?item=21175#objective-of-quest)] - [Draconic for Dummies](https://wowgaming.altervista.org/aowow/?quest=8597)".
Keep in mind that I've never had a chance to do this Chain Quest, so I may be ignoring some facts.
Said this..

I continued the Chain quest from: A [Pawn on the Eternal Board](https://wowgaming.altervista.org/aowow/?quest=8519), up to: [Draconic for Dummies](https://wowgaming.altervista.org/aowow/?quest=8597) and I have to say that:
1 - The quest is already autocompleted.
2 - I realized that a Player could never deliver it, because the Gameobejct where the quest is delivered is on an island that no player can reach.**(unless there's something I'm missing)**

I did a test, and I took off the "GM" TAG and tried to swim there, I died trying to do it.
![Screenshot_3](https://user-images.githubusercontent.com/1884642/250946566-1177e005-b1b4-46eb-a46c-f86ae378c7a0.png)

### Here is a VIDEO showing what I had to do to complete the quest:
[![Anteprima](https://user-images.githubusercontent.com/1884642/250948137-e42a539d-bc61-41c5-82b5-543368a8cf8b.png)](https://www.youtube.com/embed/Rjf4Lr-nJk8)

So, because of what has been explained, my question arises spontaneously: **"How did you get to the quest: [The Only Prescription](https://wowgaming.altervista.org/aowow/?quest=8620), if the quest that gives access "[Draconic for Dummies](https://wowgaming.altervista.org/aowow/?quest=8597)" can not be completed?"**

I want to clarify that I'm not accusing you of anything, I'm just trying to understand, because as mentioned earlier, I've never had the opportunity to do this Chain quest, so there may be something I'm not aware of.

**Comment by Gultask** [comment]
@The-GhostRider at the time those quests were available in ChromieCraft as part of the Scepter of Shifting Sands event shortly before the release of AQ40

**Comment by The-GhostRider** [comment]
> @The-GhostRider at the time those quests were available in ChromieCraft as part of the Scepter of Shifting Sands event shortly before the release of AQ40

Thanks for the clarification.

**Comment by The-GhostRider** [comment]
@Gultask 
But there is still something I don't understand..
What you explained to me is fine, but now how should the quest be done?
because as both my Screenshot and my Video show, you can't get to the GameObject that makes you complete the quest because it's on an island inaccessible for a player..
(For more details watch the video).

**Comment by Gultask** [comment]
Doctor Weavil's island? It's accessible I was there some times when I still played often. I think we just swam from Dustwallow Marsh with no problems
