### ISSUE TITLE
Warrior Recklessness

### ISSUE THREAD

**Issue by K1PCKhor** [chromiecraft/chromiecraft#4056]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

60

### Current Behaviour

All 3 Recklessness stacks will be used up if you cast and AOE spell. (Whirlwind, Cleave)

### Expected Blizzlike Behaviour

One stack should be used up with each special attack/ability!

### Source

https://www.wowhead.com/wotlk/spell=1719/recklessness

### Steps to reproduce the problem

1. Cast Recklessness
2. Cast Cleave (with glyph to strike 3 targets) or Whirlwind when fighting 3 or more mobs
3. All 3 stacks of Recklessness are gone!

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/97ec08dc36394b2bc23f26f484ef0a60f81f6c7e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
https://wowwiki-archive.fandom.com/wiki/Recklessness?oldid=2297223
Under the notes section : _"Affects [Whirlwind], but removes 1 charge for each target you hit. While wielding 2 weapons it still will only remove 1 charge per target."_

I assume you think 1 charge of recklessness should be used to crit multiple mobs, because it's bound to the spell, and not mobs hit. However this is not true. If the special attack hits multiple mobs, it will consume that many charges (if crit is not rolled). The only case where it may not consume multiple charges, is if the roll for that attack was already a crit, since recklessness only consumes if the spell wasn't rolled a crit, and a charge is still available to convert it into a crit. 

![image](https://user-images.githubusercontent.com/62584589/190018039-57fbab4a-390b-4ec6-93db-4135a891f005.png)

Here I am in the middle of 4 target dummies. As you can see, when I activate recklessness, and then cast bladestorm (more or less same spell as WW), the 1st 3 hits of my BS are crits, which consume the 3 charges of recklessness, and the buff is removed before the 4th hit registers. The same applies to any special spell that it affects. This is working as intended from what I can see.

**Comment by gettheboom** [comment]
As Cooties said, the charge gets removed per target. Not sure if this is how it's intended to be, however, I think having it released on a spell would be overpowered, so I definitely would leave it as it is imo

**Comment by K1PCKhor** [comment]
I checked at WOTLK pre patch footage, and it seems that the spell works just like blizzard!
(Altho I think the spell description is very misleading!)
