### ISSUE TITLE
Quest: The Chill of Death, wrong mobs marked for item drop

### ISSUE THREAD

**Issue by 99dsimonp** [chromiecraft/chromiecraft#429]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Quest The Chill of Death: https://wotlkdb.com/?quest=375 prompts you to find Duskbat Pelts. These are dropped by Greater Duskbat only (https://wotlkdb.com/?item=2876), but ingame the mob Vampiric Duskbat also has the quest tooltip suggesting they may drop it. After killing them a while I can confirm they do not drop it, which is correct https://wotlkdb.com/?npc=1554. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Remove the quest item drop from Vampiric Duskbat.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept quest 375.
2.  Find a Vampiric Duskbat.
3. See for yourself that it tells you Duskbat Pelts are dropped from it.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@99dsimonp 

I honestly can't tell you if your report is valid or not.
**The reasons are as follows:**
- **WOTLKDB:** [Vampiric Duskbat](https://wotlkdb.com/?npc=1554#drops)
- **WOTLKEVOWOW:** [Vampiric Duskbat](https://wotlk.evowow.com/?npc=1554#drops)

They cannot be considered as **100% "Trusted" sites.**
But with what I just said, I don't mean to say that: **"these sites are wrong"**.
I'm just saying that these sites report a different data than Wowhead.

**As you can see also yourself from the Screenshots below:**
<details>
<summary>ScreenShots WOTLKDB & WOTLKEVOWOW</summary>

![image](https://user-images.githubusercontent.com/1884642/115106790-9033fb00-9f5e-11eb-964e-958980e7f912.png)
![image](https://user-images.githubusercontent.com/1884642/115106944-bdcd7400-9f5f-11eb-83f3-8c3a1f0acc81.png)
</details>
=============================================================================
</br>
</br>

**Instead Wowhead Classic and TBC report this kind of data from the drop of these 2 NPCs:**
  - **Wowhead Classic:** [Duskbat Pelt](https://classic.wowhead.com/item=2876/duskbat-pelt)
  - **Wowhead Classic:** [Greater Duskbat](https://classic.wowhead.com/npc=1553/greater-duskbat#drops;q=Duskbat%20Pelt)
  - **Wowhead Classic:** [Vampiric Duskbat](https://classic.wowhead.com/npc=1554/vampiric-duskbat#drops;q=Duskbat%20Pelt)
- **Wowhead TBC:** [Duskbat Pelt](https://tbc.wowhead.com/item=2876/duskbat-pelt)
- **Wowhead TBC:** [Greater Duskbat](https://tbc.wowhead.com/npc=1553/greater-duskbat#drops;q=Duskbat%20Pelt)
- **Wowhead TBC:** [Vampiric Duskbat](https://tbc.wowhead.com/npc=1554/vampiric-duskbat#drops;q=Duskbat%20Pelt)

**As you can see also yourself from the Screenshots below:**

<details>
<summary>ScreenShots Wowhead Classic & TBC</summary>

![image](https://user-images.githubusercontent.com/1884642/115106709-36cbcc00-9f5e-11eb-9a49-f6cffb723505.png)
![image](https://user-images.githubusercontent.com/1884642/115106611-b60cd000-9f5d-11eb-9e53-e5da0609f0f8.png)
![image](https://user-images.githubusercontent.com/1884642/115107001-1866d000-9f60-11eb-90b0-c85ff17801c2.png)
</details>


**Then, there are 2 other further considerations to make.**

- From TBC to WOTLK, the loots may have changed, and that's why those 2 (unofficial) sites report a different data than Wowhead. **(or maybe not)**

**Then, there is another kind of more "Analytical" reflection to do..**
- The item in question is called: **"Duskbat Pelt"** which literally means: **"Dusk" "Bat" "Pelt"**.
Now, both NPCs are **"Bats"**, and both are **"Dusk-Bats"**, and both are assumed to have a **"Pelt"**

So, for **"Logical" reasons** (as we currently have no **"Tangible Evidence"** of the actual loot of these NPCs).
I would rely on Wowhead's judgment on the TBC version **(since it is the closest expansion to WOTLK).**

Regarding the **"Tooltip"**.
The Tooltip **(if we are talking about the same thing)** is a **"Reflection"** of your **old WoW games**, in fact I'm pretty sure, that if you rename the **"WTF" folder** to **"WTF_OLD"** and delete the **"Cache" folder** when you will return into the game **(after resetting all settings)**, since that npc does not have that item in the loot, you will no longer be able to see the same things in the **"Tooltip"** as you did before.

**And here, there is evidence of what I am saying, because in fact the NPC does not have that loot..**
<details>
<summary>ScreenShot ChromieCraft DB Loot NPC Vampiric Duskbat</summary>

![image](https://user-images.githubusercontent.com/1884642/115109250-8a451680-9f6c-11eb-82ff-23c6b16c5854.png)
</details>

**So I believe that the Bug exists, but not for what you have reported, quite the opposite, since Wowhead Classic and TBC claims the opposite..**

**Comment by 99dsimonp** [comment]
Hi @Stifler82, thanks for your reply! 

> They cannot be considered as 100% "Trusted" sites.
Is there any such site? I expected that a WOTLK DB site would be more trustworthy than Wowhead TBC, given that Wowhead caters to a different expansion altogether. This discussion leads to a deeper question of who to trust and what to believe is right, but we should probably save that for another time.

> Regarding the "Tooltip".
I understand why you're saying this, but I'm running wow from a fresh WOTLK install. I would be very surprised if this issue has something to do with my installation. I have not tested on my own, and I have already finished the quest, so I'm afraid somebody else will have to verify this.

**Comment by Stifler82** [comment]
> Is there any such site? I expected that a WOTLK DB site would be more trustworthy than Wowhead TBC, given that Wowhead caters to a different expansion altogether. This discussion leads to a deeper question of who to trust and what to believe is right, but we should probably save that for another time.

Unfortunately no, we consider these sites as **"Circumstantial Guidelines"**, this means that these sites can give us a **"Clue"** or a suggestion about the truth, but then go find out what the **"real truth"** is..
Because the real puzzle / dilemma / drama for us (Dev) is:
- The Player reports a problem and provides us as proof, **(a link from Wowhead "Classic")**, because the problem is related to the **"Classic" area of the game.**
- But the problem is: **that "Classic" area of the game is in the "WOTLK" expansion (which is not the classic)** and where many things are different from the classic.

And the same concept is applied for the links / zones by the TBC.
So, until when the WOTLK version of wowhead won't be released, we'll be like a blind man looking for a coin in a landfill.

So in this specific case I can only rely on **my common sense and on my memories of WOTLK (at the time of WOTLK).**
For example, my common sense tells me 1 thing:
- The item in question is called: **"Duskbat Pelt"** which literally means: **"Dusk" "Bat" "Pelt"**.
Now, both NPCs are **"Bats"**, and both are **"Dusk-Bats"**, and both are assumed to have a **"Pelt"**
- So if the quest says: **"Go Collect Duskbat's Pelt"**, theoretically both bats should be able to drop that item quest.

On the other hand, I remember that when the WOTLK expansion came out, **the "Start Area" loots had changed** by inserting these bags for low-level characters into some NPCs.

There is also to consider that this **"Item"** is not part of the **"Generic loot"**, but it is an item that is dropped only if you have the quest.
So, I think it's fair that these NPCs drop those bags **(and in addition)** the item quest as well.

> I understand why you're saying this, but I'm running wow from a fresh WOTLK install. I would be very surprised if this issue has something to do with my installation. I have not tested on my own server, and I have already finished the quest, so I'm afraid somebody else will have to verify this.

Ok, maybe you have a fresh client, but **there are some "Addons" that have their own internal database**, and can suggest outdated or misplaced information to the game client, or even right instead.

**(for example)**
Carbonite: it is an addon that has its own DB, so **(IF) there is a quest in the server that has an incorrect POI**, (and instead carbonite has the correct POI), you will not notice the error because carbonite **( in spite of the server)** suggests the correct information.
