### ISSUE TITLE
Boar meat in "Stocking Jetsteam" quest not recognized as quest item

### ISSUE THREAD

**Issue by bigbird78** [chromiecraft/chromiecraft#449]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS I believe? Not sure.
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

In the "Stocking Jetsteam" quest in Dun Morogh, the boar meat did not show up as a quest item (have the yellow around it). I could (and accidentally) sell it to a vendor.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The boar meat should be a quest item in "Stocking Jetsteam".

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anglerf1sh** [comment]
The drop is not quest specific since you can also use it as a cooking ingredient for https://wowgaming.altervista.org/aowow/?spell=2540 

There are several quests like this in the old world where you have to gather normal drops from mobs for a quest. Since they aren't quest specific the game will not flag them as quest items which means you can sell them. This is normal blizzlike behavior. Other examples like this quest:

https://classic.wowhead.com/quest=38/westfall-stew

https://classic.wowhead.com/quest=150/murloc-poachers

**Comment by Helias** [comment]
totally agree with @anglerf1sh , be sure about the source and the blizzlike behavior when you report something @bigbird78 , anyways, thanks for the tentative report, I know your intention is to improve the quality of the game content, just look more to blizzard/wowhead sources :wink:

**Comment by bigbird78** [comment]
Right you two are. Apologies for the false flag, it's been a while since I've played, I'll double-check next time. Thanks @anglerf1sh and @Helias !
