### ISSUE TITLE
Unique items can be rolled on by players who have them equipped. If won, the item then becomes unlootable.

### ISSUE THREAD

**Issue by Zelfie** [chromiecraft/chromiecraft#4523]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Example, ZG's Bag of Whammies, can be rolled on by a character who already has one equipped.
If that person wins, the item is then stuck on the boss, and cannot be looted in any way by anyone.
If this bug didn't exist on chromiecraft, I'd have a Bag of Whammies.

### Expected Blizzlike Behaviour

Unique items cannot be rolled on if you already own them.
Thus, this problem should not exist and loot should never be stuck on a boss due to this error.

### Source

https://wowpedia.fandom.com/wiki/Unique
"If you have an opportunity to acquire another of the same item then you will be unable to. For example, if a mob drops the same item that you already possess, you won't be able to loot the item. If the mob is skinnable this will also prevent you from skinning the mob."

Can't find a bluepost saying the same. But unique is unique. You shouldn't be able to roll on it.

### Steps to reproduce the problem

1: Create 2 characters, equip one with item=19891 Jin'do's Bag of Whammies
2: Enter ZG with group loot on, killing Jin'do so he drops a Bag of Whammies
3: Whammie character should be able to roll on the dropped item, despite it being unique. If that character wins the roll, item is now stuck in an unlootable window due to the misroll.

### Extra Notes

Whammie character should never have been able to roll on the item, thus the item should never enter this unlootable state due to this bug.
Send Bag of Whammies to Zelfi.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11530ecb95a35f66a2c220781172c57e0749ac48

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
its a weird interaction, not sure how it should work "if a mob drops the same item that you already possess, you won't be able to loot the item" just suggets you cant loot it from the corpse.

**Comment by Cooties-cc** [comment]
There's also 2 types of unique, which the 2nd being _unique-equipped_. If unique items are being rolled on by players that already have them on the account, then that's probably going to be a longstanding issue, since _unique will prevent looting_ of the item, whereas unique-equip just _prevents you from equipping 2_ of the same item (you can still loot it). 

If possible, could unique items get the same treatment as say nef/ony heads? In which if a player has already obtained that item, they would simply not show up as loot on the creature? This of course is just for _unique_ items in which a player has already looted, and still has in a bag somewhere on the account?

**Comment by Samsequel** [comment]
@neifion-00000000 do you know an easy item we can check this on on the ptr?

**Comment by Salehyn** [comment]
The whammies mentioned in the report are purely Unique: https://www.wowhead.com/classic/item=19891/jindos-bag-of-whammies
IIRC this should work in a way that if you roll on a unique item you already have, after your roll fails the group should be able to loot the item with FFA/ML if they change loot system.

I don't think there should be any sort of system automatically blocking you from seeing the item in the roll.
Let me show a quick example why: https://www.wowhead.com/classic/item=11118/archaedic-stone this item was a purely unique item back on vanilla wow. It rolls a random enchantment every time it drops, so what you would do is take the first drop with any stats that are remotely useful to you (i.e. stam/str for a rogue), and the next time if it drops with more optimal stat (i.e.stam/agi), you would simply delete the previous ring you owned before rolling on the item.
Granted, the ring was later changed to unique-equipped instead (because this was stupid as shit), but i don't think any changes were made to unique-visibility between vanilla and 3.3.5a.

For unique-equipped there isn't even an argument: there is no system check in place to see if you have one equipped or not, period. You can have as many of the same item with different enchants/gems for different gear sets as you want, you just can't equip them all together.

The problem here is clearly that the item remains stuck on the corpse after the failed roll. It should be possible to pick up by changing to FFA or ML, just like you can usually pick up items that way when the roll winner has their bags full.
