### ISSUE TITLE
The Stones That Bind Us [Interaction Failure w Possible solution]

### ISSUE THREAD

**Issue by KuristZero** [chromiecraft/chromiecraft#4744]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

50-59

### Current Behaviour

When on the quest [The Stones That Bind Us](https://www.wowhead.com/tbc/quest=2681/the-stones-that-bind-us), targeted NPC's do not activate their associated binding stones for interaction regularly as they spawn too far away from the stone. 

During the quest, you attack an enemy and bring its HP to below 5% health, which stuns the NPC and should trigger a stone of binding nearby to be clickable.

Currently, it's a 50% chance that the stone will activate as several of the NPC's spawn on what appears to be the cusp of the range of triggering the stone.

This quest has previously had an issue as seen in [this previous bug fix](https://github.com/chromiecraft/chromiecraft/issues/1105) where the stun phase was not activating.

### Expected Blizzlike Behaviour

All servant NPC's from the quest [The Stones That Bind Us](https://www.wowhead.com/tbc/quest=2681/the-stones-that-bind-us) should trigger their related [Stone of binding](https://tbc.wowhead.com/object=141812/stone-of-binding), allowing for the quest to be completed without repeat killing the same enemy.

### Source

NA

### Steps to reproduce the problem

1. Accept quest: [The Stones That Bind Us](https://tbc.wowhead.com/quest=2681/the-stones-that-bind-us)

2. Engage in combat with [Servant of Sevine](https://tbc.wowhead.com/npc=7671/servant-of-sevine), [Servant of Allistarj](https://tbc.wowhead.com/npc=7670/servant-of-allistarj), [Servant of Grol](https://tbc.wowhead.com/npc=7669/servant-of-grol), [Servant of Razelikh](https://tbc.wowhead.com/npc=7668/servant-of-razelikh).

3. Upon reducing the NPC to under 5% HP, they will enter a stunned state and should activate one of the following associated stones for interacting with, which are located nearby the NPC: [Stone of binding](https://tbc.wowhead.com/object=141812/stone-of-binding)

4. In roughly 50% of cases these stones do not trigger for interaction, resulting in the NPC losing its stunned state and re-engaging in combat.

### Extra Notes

This was triggered on a level 59 Hunter character so unclear if the pet plays a role. 
Combat with and without a pet resulted in this failure to activate on all 4 variants of the servants and stones.

UPDATE: Further troubleshooting suggests the distance between the enemy and the binding stones is the issue, with some spawning outside of the stone's interaction range.

Unsure if it's the debuff [Spirit Shock](https://www.wowhead.com/tbc/spell=10794/spirit-shock) or the stone itself that has a range interaction event, but increasing the range by 20% to accommodate for creature wander would likely solve this issue,

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/c05c45c51d3d...3ad652d8ab96

### Operating system

Windows 10 Pro - Build 19044

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Pyromanihack** [comment]
I think that this is Blizzlike: as written in the quest log, the servant must remain close to the stone for it to be targetable. Many [comments](https://www.wowhead.com/tbc/quest=2681/the-stones-that-bind-us) point out this behavior
`To finish this quest, you must first locate the [Stone of Binding](https://www.wowhead.com/tbc/object=141812/stone-of-binding), which will be nearby any servant, but will not be interactable right away, which means that there will be neither mouseover prompt nor highlighting. Given this and overall color resemblance of these objects and [Blasted Lands](https://www.wowhead.com/tbc/zone=4/blasted-lands)' landscape, this could be proven difficult, but it is crucial to this quest.
After the stone located, you must attack a servant while keeping them around the stone, but you won't be able to kill it yourself: their health will stop draining after around 10% and they will be stunned for about 30 seconds. At this moment Stone of Binding will become interactable, and you'll need to smash it via pressing RMB as hard as possible, this will help you as it helped me.
If you fail to do this in time after engaging and stunning a servant, you'll make yourself an invincible enemy since the stun is off but the inv is still on. Also, cleaning but not looting other mobs that are usually party loitering around can help a lot, too.`
