### ISSUE TITLE
[High King Maulgar] Krosh Firehand doesnt have spell dmg reduction buff on pull

### ISSUE THREAD

**Issue by IskrenPlashkov** [chromiecraft/chromiecraft#4811]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

https://wotlkdb.com/?npc=18832 doesnt have the 75% spell dmg reduction buff (https://wotlkdb.com/?spell=33054) on pull. He casts it few seconds after pull, usually after casting https://wotlkdb.com/?spell=33051 twice.

Also the https://wotlkdb.com/?spell=33054, once eventually spell stolen, only lasts for 20 seconds.

### Expected Blizzlike Behaviour

He should have the buff on pull, before starting to cast anything.
Once mage uses spellsteal buff should last 2 minutes.

### Source

https://www.icy-veins.com/tbc-classic/gruuls-lair-guide-strategy-abilities-loot

### Steps to reproduce the problem

Engage [HKM](https://wotlkdb.com/?npc=18831).
Attempt to spellsteall immediately after pull.

### Extra Notes

With this issue in place https://wotlkdb.com/?npc=18832 usually 1 shots 1-2 ppl before he can be properly tanked.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/592a26cb8c46a9db92a70c275f1d8625f8949c1d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
Seems to be incorrect.
Looking at this video, the spell is cast only after the pull
https://youtu.be/2bXzGm_Dvho?t=7
https://www.youtube.com/watch?v=DhaKamqqIjo

further, the ability has a duration of 30 seconds as stated here https://www.wowhead.com/tbc/spell=33054/spell-shield

and the guide you linked also emphasizes this https://www.icy-veins.com/tbc-classic/gruuls-lair-guide-strategy-abilities-loot
> The Mage will not have the Spell Shield buff on them 100% of the time, meaning there are windows where they must take a Greater Fireball at full damage value that can deal 8-9k damage.

**Comment by Paradigmxd** [comment]
I can confirm, Spellstealing the Shield doesnt last for so long. Mages take damage, hence why you need a 10k+ mage tank and a dedicate Mage healer

**Comment by Paradigmxd** [comment]
But Ishkren is correct, however, the Mage Shield should appear exactly after pull, which is why a Mage must start the pull

**Comment by balleny** [comment]
> 

it is currently scripted that first one fireball will happen (if in range) and 5 seconds after the pull, the first spellshield will occur.
Given the video sources i linked, we should be able to get the exact timing of the first shield (its def. not directly on pull). The relevant question is tho, if he will cast a fireball if the mage is too close, before the first shield, on retail. because currently, it is scripted that way. (obviously, you could just apply boss mechanics and outrange the boss for 5 seconds (aka positioning him) to delay the first fireball until after the first spellshield cast

**Comment by IskrenPlashkov** [comment]
Actually on the very video you linked it is stated at 0:25 that spell shield is cast on pull. You can also see in this video that Krosh gets the spell shield right before he starts casting his first fireball.

I have tanked this guy back in TBC as mage and the way I pulled was: Pyro ; spellsteal ; dps rotation.

**Comment by Paradigmxd** [comment]
I can confirm - from my guild's progress during TBC classic that when you pull the mage, he does an insta shield and starts casting fireball immediately. All of this happens in a bout 2 seconds.

I can also confirm that, spellsteal, while timer wise may last for long, it will never be a full duration as the shield's scripting is DAMAGE dependent.. So as I said, tank healer and 10k+ needed as the Mage tank will suffer heavy damage.

**Comment by balleny** [comment]
1) you can see that the npc doesnt cast spellshield directly on pull but with a brief delay of 2 seconds. He then also directly starts casting a fireball. Both happen in this case (https://www.youtube.com/watch?v=DhaKamqqIjo) after the npc positioned.
2) in the other video (https://www.youtube.com/watch?v=2bXzGm_Dvho&t=7s) you can see the same 2 second delay on the shield. But, you also see that the fireball is casted 4 seconds into the fight. This is, because the mage blinked away to increase the distance (frost mage here). In the other videos, you have a firemage with 41 yards range. Although the Greater Fireball used by the npc has a 100 yards range and ignores LoS https://www.wowhead.com/wotlk/spell=33051/greater-fireball , the boss wants to establish a maybe 25 or 30 yards range before actually casting - this can also be seen here https://www.youtube.com/watch?v=7V57oDPm1Gw
here, we can even see him going for a melee swing / potentially close enough for range to blast nova, his other ability https://www.youtube.com/watch?v=aMaSpGk6o34
this also seems to be in line with an original videos A) https://www.youtube.com/watch?v=7V57oDPm1Gw B) https://www.youtube.com/watch?v=ZcgMzrI70FE

concluding, it would make sense to schedule him casting the first shield 2 seconds into the fight, followed by his Greater Fireball ability. Before that, he should try to reach melee range and not use any ability

**Comment by Paradigmxd** [comment]
Balleny, all of this is indeed correct and a great job for digging the videos.

**Comment by IskrenPlashkov** [comment]
I for one can get behind the following: "schedule him casting the first shield 2 seconds into the fight, followed by his Greater Fireball ability. Before that, he should try to reach melee range and not use any ability"

For me the essence of the mechanic at hand is for him to never finish casting fireball without the mage having a chance to spellsteal the buff.

**Comment by elthehablo** [comment]
I think with timer adjustments this is fine now. Correct me if I'm wrong and I will re-open
