### ISSUE TITLE
Warlock's drain soul and curse of elements getting fully resisted on bosses.

### ISSUE THREAD

**Issue by immersionnn** [chromiecraft/chromiecraft#4815]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

Drain soul(https://wowgaming.altervista.org/aowow/?spell=11675) and curse of elements(https://wowgaming.altervista.org/aowow/?spell=11722) are both getting fully resisted on bosses despite being hit capped, which obviously shouldn't happen. 

### Expected Blizzlike Behaviour

These two spells shouldn't get fully resist if you hit capped and from my testing they're the only two warlock abilities with this behavior. You can also spam other abilities (shadow bolt, corruption, curse of agony) to see it for yourself that they won't get fully resisted.

### Source

No idea what to post here other than a wowpedia miss page where it says that the the 1% hard floor chance of spells to miss was removed in the patch 3.0. (search with ctrl + f hard floor)
https://wowpedia.fandom.com/wiki/Miss

### Steps to reproduce the problem

Get a hit capped warlock(14% with the supression talent, 17% without) and go to heroic training dummy.
Spam drain soul until you get a full resist. Repeat the process with curse of elements.

https://imgur.com/a/S4hLbpS

ps: when drain soul gets fully resisted it won't say it in the combat log like it does for curse of elements(like it does in the screenshot i posted) so you'll hate to enable your combat text target damage or get an addon like msbt(MiksScrollingBattleText)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/592a26cb8c46a9db92a70c275f1d8625f8949c1d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Tereneckla** [comment]
Resist and Spell-Miss are different combat log messages in wotlk, hit does not affect the resist chance
Still weird behaviour

**Comment by immersionnn** [comment]
> Resist and Spell-Miss are different combat log messages in wotlk, hit does not affect the resist chance Still weird behaviour

yea, if it was because of hit it should have been 'miss' instead of 'resist' but didn't know what else to blame the bug on because i don't think i've seen fully resisted spells on bosses on any pservers or classic, this is vanilla/tbc behavior afaik

**Comment by balleny** [comment]
Did you check your targets shadow resistance and your own spell penetration? Resists are different from misses and not affected by hit

**Comment by Tereneckla** [comment]
If it was a resist from shadow resistance there should have been full resists on corruption and curse of agony, too

**Comment by Salehyn** [comment]
I think this might be a problem of binary vs non binary resistance behavior. Bosses do have 15 resistance to all schools due to the level gap, which cannot be reduced in any way, so nearly every spell has partial resists (even holy it seems)
Thing is, drain soul should be a non binary spell, so it should definitely not see full resists (each tick gets checked for partial resist instead)
Curse of Elements however requires some digging... 
I'll make some tests and go through some logs.

**Comment by Salehyn** [comment]
Ok, tests and digging done.

1) COE is working as intended. It runs on Binary (yes or no) resistance mechanic, just like every other curse with no damage component (weakness, tongue too). The effect has a small chance to be resisted against bosses and that's working as intended. Source: https://www.mmo-champion.com/threads/727654-Curse-of-Elements-and-Spell-Pen this is from 3.3.5a and confirms COE can be fully resisted via spell resistance
2) Drain soul is bugged. It is currently running on binary mechanic instead of nonbinary like every other damage dot. So the initial cast can be resisted instead of part resists happening on ticks. This needs fixing. Source: logs such as https://classic.warcraftlogs.com/reports/ANtXrg6aQwpc897h#fight=8&type=damage-done&source=24
