### ISSUE TITLE
Night elf's Shadowmeld enables PvP in certain areas

### ISSUE THREAD

**Issue by NidaleeLiadrin** [chromiecraft/chromiecraft#483]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Using Night Elf's Shadowmeld racial spell [spell=58984] flags the player to PvP in certain areas, mostly cities/around npcs.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go anywhere inside a city
2. Use Shadowmeld
3. PvP flag should appear in the player's unit frame
4.

##### EXTRA NOTES:

Needs further testing as i suspect using near NPCs causes to be PvP flagged . Tested in Stormwind / booty bay

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by NidaleeLiadrin** [comment]
Behavior recorder while inside / outside Stormwind .
https://youtu.be/A-XKpimBUl4
https://youtu.be/Ab9Ndtl5jS4

**Comment by Tachtzehn** [comment]
Was actually experiencing this yesterday while leveling in Teldrassil before creating my GitHub account. Any player can quickly recreate this issue by:
1. creating a new Night Elf character
2. running forward until the minimap header text changes to "Aldrassil"
3. now use Shadowmeld and you will now be flagged for pvp
For some reason, there's a radius around the starting location where this bug will not occur, that's why running forward is necessary.

After testing with at least 30 attempts, mostly in zones Teldrassil and Darnassus, the bug occurs regardless of character class/gender, and doesn't seem to be affected by whether or not the player is targeting something. It does appear to trigger based on the player's location, but it's not necessarily related to the zone or minimap header, as there are areas in Teldrassil and Darnassus that will both trigger and not trigger the bug, and also sections of the map with the same header where the bug will trigger and not trigger ("Shadowglen" header at the player's starting location vs. "Shadowglen" header on the road leading to the starting area's exit south of Aldrassil).

**Comment by Tachtzehn** [comment]
In Darnassus, it's harder to find a place where Shadowmeld doesn't flag you for pvp, though I did find that standing between these 2 NPCs in the east Temple Gardens room before using Shadowmeld doesn't trigger the bug, while standing on the top step of the entryway will trigger it, as referenced by these screenshots.
![WoWScrnShot_042921_011855](https://user-images.githubusercontent.com/83389835/116520631-96987000-a898-11eb-9ed4-33d781895abe.jpg)
![WoWScrnShot_042921_020747](https://user-images.githubusercontent.com/83389835/116520664-a021d800-a898-11eb-99b4-8dda40432ddc.jpg)
