### ISSUE TITLE
The Attack! Lord gregor Lescovar is invisible sometimes.

### ISSUE THREAD

**Issue by Guub1** [chromiecraft/chromiecraft#511]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

During the quest The Attack! Lord Gregor Lescovar is sometimes invisible and you need to abandon the quest and wait another 10minutes for the alarmbot to return. its located in stormwind castle, you get the quest from tyrion. The fact that the lord was invisible happened to me 2 times.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
--

##### STEPS TO REPRODUCE THE PROBLEM:

1. if you die during the quest, or just randomly the lord is invisible, happened to me on my 1st try on the quest.

##### EXTRA NOTES:

i think if you die during the quest and restart it its bugged atleast it was for me. my ingame name is Gooby if you have any questions

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@chromiecraft/bug-triaging please have a look at this, second opinion needed here

**Comment by Stump876** [comment]
I think you may be starting the quest before he has a chance to respawn. Initially I was able to complete event with no issues.  
I retried, and as was suggested, I failed it at first. When the spybot respawned, the two guards and Lord Gregor had not respawned, but the "Priestess Tyriona" script continues as normal.

![image](https://user-images.githubusercontent.com/68164076/118382725-174faf80-b5ad-11eb-9a12-018d9dea0115.png)
![image](https://user-images.githubusercontent.com/68164076/118382793-a8268b00-b5ad-11eb-9919-ff59efb2f47e.png)

At that point the quest can't continue because there is no Lord Gregor for the game to run script on. I don't believe this is a bug as everything is working as intended. Though it would make sense, I can't find any evidence that his respawn is any faster than what it currently is. I would suggest making sure he is there before starting/restarting the quest.

On a side note. During my test the level 80 patrolling guard attacked and killed them both during the fighting. I looked it up and this is blizzlike.
