### ISSUE TITLE
Readiness freezes screen when used.

### ISSUE THREAD

**Issue by Mikel0ke** [chromiecraft/chromiecraft#5365]
It only freezes when it actually resets cds. it freezes without addons, with addons, and even on fresh clients.
Using the same client on warmane, it doesnt freeze the screen.

**Comment by Mikel0ke** [comment]
Readiness resetting cds : https://www.youtube.com/watch?v=f3GHrkpgZvM
Readiness without resetting cds : https://www.youtube.com/watch?v=B2rFyZDfFDg

**Comment by hofik19** [comment]
I have the same problem on Windows 10, noticed it even before TBC content. No matter if I use clean client or modified. Disabling add-ons also don't fix it.

**Comment by heyitsbench** [comment]
Cannot reproduce. Tried with random talent allocations with Aimed Shot and Chimera Shot against a training dummy with no addons. Please find consistent steps on the PTR from a newly made character to reproduce the issue. Once these steps are provided (and assuming I can reproduce the issue), I'll reopen the issue.

**Comment by Never6** [comment]
> Cannot reproduce. Tried with random talent allocations with Aimed Shot and Chimera Shot against a training dummy with no addons. Please find consistent steps on the PTR from a newly made character to reproduce the issue. Once these steps are provided (and assuming I can reproduce the issue), I'll reopen the issue.

The issue is, When you readiness your FPS drops, The more abilties you reset, The bigger the drop is.
I created a fresh character and couldn't reproduce on the PTR (no addons)
but when i went to live build and did the exact same steps my FPS did drop
it seems to me that live build and test realm are different
In fact for a while on the test server if you did the " .cooldown" command your FPS would also drop
that doesn't happen anymore

**Comment by heyitsbench** [comment]
Even people on the CC Discord who copied their character from live could reproduce the issue fine on live but not on the PTR. Given that the issue also does not seem to happen at all on other pservers, I don't believe it's intrinsically tied to the amount of spells getting their cooldowns reset.
