### ISSUE TITLE
Witherbark Broodlings in the Hinterlands drop Solid Stone, Golden Sensam and Goldthorn

### ISSUE THREAD

**Issue by irekjer** [chromiecraft/chromiecraft#538]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB

##### FACTION

- [ ] Alliance

##### CONTENT PHASE:

- [ ] 40-49

##### CURRENT BEHAVIOUR:

Currently Witherbark Broodlings, which spawn when you kill Witherbark Broodguards in the Hinterlands, drop the Items mentioned in the title, but mostly Golden Sensam and Solid stone.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They shoudn't drop any items.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill the Witherguard Broodguard
2. Kill the Spawned Broodling
3. Loot

##### EXTRA NOTES:

Type here.

https://ibb.co/TY2TQjX is a picture of me looting it (The droprate is pretty consistent on these items from the smöll spiders)

 https://classic.wowhead.com/npc=7768/witherbark-bloodling#comments No drop in classic
Websites that say they don't drop
https://wotlkdb.com/?npc=7768 
https://wotlk.evowow.com/?npc=7768
https://wotlk.cavernoftime.com/?search=Witherbark+Bloodling
These below say that these items drop
 https://wowgaming.altervista.org/aowow/?npc=7768#drops 
 https://wotlk-twinhead.twinstar.cz/?npc=7768

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report, I especially liked the number of sources you found. 

I did want to mention that if you are using an enGB client, you might want to download the enUS version instead. This is because, unfortunately, the enGB client has proven to be defective. Using that client you'll experience more bugs than there actually are. To check if you are running the enGB client, look up the contents of your Data subdirectory. If you see a directory named enGB this indicates you're using the enGB client.

You can download ChromieCraft's clean enUS client with ChromieCraft's realmlist pre-set from https://www.chromiecraft.com/downloads/.
