### ISSUE TITLE
[Missing ICD] Zanga Trinkets

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5423]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

following items have no ICD and hence proc way too often:

https://wowgaming.altervista.org/aowow/?items&filter=na=mark%20of;sl=12;minle=91;maxle=91
https://www.wowhead.com/wotlk/items/name:mark+of/min-level:91/max-level:91#0+1+19

### Expected Blizzlike Behaviour

Mark of Defiance: 17 seconds ICD, 15% proc chance
Mark of Vindication: 25 seconds ICD, 15% proc chance
Mark of Conquest: 25 seconds ICD, 15% proc chance

### Source

https://www.wowhead.com/wotlk/spell=33511/mana-restore
https://www.wowhead.com/wotlk/spell=33522/mana-restore-2
https://www.wowhead.com/wotlk/item=27920/mark-of-conquest#comments

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UndoUreche** [comment]
Regarding mark of conquest, the sources listed are wowhead comments. Among these comments there are many claims of there being no internal cooldown, and in fact the trinket procing multiple times out of abilities like swipe.
![image](https://github.com/chromiecraft/chromiecraft/assets/50205200/b4733cd1-27c6-46a4-8f3f-1e4e5e5d34b2)
![image](https://github.com/chromiecraft/chromiecraft/assets/50205200/a88403c7-0fdb-4361-bc46-0fd627dd8cb1)

These claims are from patch 2.0.5 when the item was added, and while there are instances of such claims being outdated, the wowwiki does not list any patch changes to this item since it was added.
![image](https://github.com/chromiecraft/chromiecraft/assets/50205200/900f5a55-b864-4f7d-9766-523cb3eeee64)

With the provided sources, taken from both the wiki and the original issue's cited sources, I believe we can make a solid case for the healing effect of the item, if not the whole whole item not having an internal cooldown. In light of this, the changes made by this issue should be reverted.

Sources:
https://www.wowhead.com/wotlk/item=27920/mark-of-conquest#comments
https://wowpedia.fandom.com/wiki/Mark_of_Conquest

**Comment by balleny** [comment]
two out of the three links i posted from wowhead directly display in the spell itself (not in the comments) the exact proc chance and cooldown it has in wotlk classic.
I am not sure how you come to the idea of having a case for ALL of them potentially not having an ICD

![image](https://github.com/chromiecraft/chromiecraft/assets/12682004/2ab9bb99-a2b5-43a1-a6fa-1b7509b123ef)

![image](https://github.com/chromiecraft/chromiecraft/assets/12682004/95048d28-2074-49af-b1db-3531ab88f90d)

**Comment by UndoUreche** [comment]
No, I am specifically talking about (and have specifically named and singled out) the third trinket you mentioned, The mark of conquest.

**Comment by balleny** [comment]
ye, nvm. i misread whole whole as the whole set of items from this ticket, not the other part / variant of the effect.

it may be in a similar matter as the Deathfrost enchant (for which i also opened a ticket).
there, one part (casts) has an ICD with a higher proc rate, and the other part (physical) has no ICD, but a small proc rate) apparently.
https://github.com/chromiecraft/chromiecraft/issues/5424
