### ISSUE TITLE
Murloc Coastrunner mobs are not supposed to be in Dustwallow Marsh

### ISSUE THREAD

**Issue by Johny-faillab** [chromiecraft/chromiecraft#553]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

[Murloc Coastrunner](https://classic.wowhead.com/npc=126/murloc-coastrunner#abilities) are not supposed to be in Dreadmurk Shore area in Dustwallow Marsh.  

##### EXPECTED BLIZZLIKE BEHAVIOUR:

[Mirefin Puddlejumper](https://classic.wowhead.com/npc=4358/mirefin-puddlejumper
) are supposed to be there instead. [Murloc Coastrunner](https://classic.wowhead.com/npc=126/murloc-coastrunner#abilities) are also using Ancient Fire spell which they are not supposed to have as well.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
I don't know how but everything in this report is invalid.. :s

1) There are no Murloc Coastrunner in Dustwallow Marsh. I have teleported to the 25 NPCs and they are all in Westfall
2) Mirefin Puddlejumper was removed from the game in TBC xpac, source https://www.wowhead.com/npc=4358/mirefin-puddlejumper#comments
3) Murloc Coastrunner uses Poisonous Stab as the only spell

**Comment by Johny-faillab** [comment]
You might actually check the location I mention in the report before saying its invalid. Also checking their spell list might also not be a bad idea.  

So again...

This is the [location](url) where **Murloc Coastrunner** are in **Dustwallow Marsh:**

**PrtScr proofs:**

 [Location PrtScr](https://imgur.com/a/UoD8fD9)
 [Combat Log](https://imgur.com/a/K50dK0e)

**Comment by Azcobu** [comment]
The confusion here is between Mirefin Coastrunners and Murloc Coastrunners.

Mirefin Coastrunner - https://tbc.wowhead.com/npc=4362/mirefin-coastrunner - lives in Dustwallow Marsh.
Murloc Coastrunner - https://classic.wowhead.com/npc=126/murloc-coastrunner - lives in Westfall.

There are definitely Mirefin Coastrunners in Dustwallow:
![WoWScrnShot_050821_205510](https://user-images.githubusercontent.com/81782124/117537549-da316d80-b040-11eb-8190-e2f8136497c2.jpg)

...but no Murloc Coastrunners.

However, the Mirefin Coastrunners are definitely spamming Ancient Fire:
![ancient-fire](https://user-images.githubusercontent.com/81782124/117537685-ca665900-b041-11eb-9ce1-25bfab1346fa.jpg)

So that would appear to be a valid issue. 

WOTLKDB lists them as casting Piercing Strike (https://wotlkdb.com/?spell=37998) and Ancient Fire is https://wotlkdb.com/?spell=37986, so perhaps it's down to a typo. However, TBC Wowhead has them using Mirefin Fungus (https://wotlkdb.com/?spell=9462) which sounds a lot more plausible than Piercing Strike or Ancient Fire.

**Comment by Azcobu** [comment]
Reopening for the secondary issue as per above.
