### ISSUE TITLE
Quest completion mark not appearing on mini-map or over NPC

### ISSUE THREAD

**Issue by 7Katta** [chromiecraft/chromiecraft#5549]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Zone:  Blood Elf starting zone on Sunstrider Isle
NPC questgiver:  Lanthan Perilon
Quest Title:  Aggression

After competing requirements for the quest, the yellow question mark does not appear on the mini-map (can see it on the main map), nor does it appear over the NPC's head. Have used low level quest tracking, this does not change anything.

The follow-up quest from same NPC - Felendren the Banished - displays everything normally upon quest completion.

Have run several characters through this zone; this happens every time.

I do not have any mods enabled at this time (other than any that came bundled with the client download)

### Expected Blizzlike Behaviour

Not an ex-WoW player, but I assume the quest completion (question) mark would appear on the mini map.

### Source

N/A

### Steps to reproduce the problem

Start a blood elf character and complete quests to progress to the "Aggression" quest.

### AC rev. hash/commit

? I don't know what to put here - however, the last occurrence was on April 30, 2023 - and happened several times before.

### Operating system

Windows 10

### Customizations

None

### Server

ChromieCraft

**Comment by Guddler** [comment]
Came to report the same bug. No mods installed, playing through Wine on linux and VMware on Mac. Chromiecraft server "Development" realm and also recall seeing it on "Test" realm too.

**Comment by Rorschach91** [comment]
Inside AC rev. hash/commit was a link that should not be removed.
Removing that link you made your report unable to be linked on AC.
I am sorry, but I must close this issue.
In any case, these types of bugs are already known. Probably will be fixed in the future, but actually Devs are working on other aspects of the game.

Thank you for your report anyway. If you find other problems feel free to report them, without touching AC rev. hash/commit section XD.
