### ISSUE TITLE
[Quest] Attunement to the Core (7848) - Several issues

### ISSUE THREAD

**Issue by cachocarne** [chromiecraft/chromiecraft#5719]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

50-59

### Current Behaviour

This happened on a Horde character, I don't know if it's the same for all players.

- At the moment, it's possible to take quest from Lothos Riftwalker while dead. It shouldn't be possible.
- It is possible to share quest with other players. It shouldn't be possible.
- It's possible to turn in quest even while dead. It shouldn't be possible.

![ 2023-06-05 a las 16 43 23](https://github.com/chromiecraft/chromiecraft/assets/77953030/a71efe6f-fc30-4bb9-95a4-ee62b2aedf66)
![ 2023-06-05 a las 16 43 26](https://github.com/chromiecraft/chromiecraft/assets/77953030/c5a737d1-2bb4-4f98-a5dc-e4a061fbda2f)

### Expected Blizzlike Behaviour

It shouldn't be possible to share the quest or take it or turn it in while dead.

### Source

https://www.wowhead.com/wotlk/quest=7848/attunement-to-the-core
Specified: not shareable.

### Steps to reproduce the problem

Walk with your dead character to Lothos Riftwalker and take the quest.
While in party, share the quest with other players.
Once you have the [Core Fragment](https://www.wowhead.com/wotlk/item=18412/core-fragment), turn the quest in while being dead

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by gchekenny** [comment]
taking/completing the quest while you're dead is correct behaviour.
![image](https://github.com/chromiecraft/chromiecraft/assets/65800273/a74e84c9-ccf5-4060-85cb-0fde33773624)
![image](https://github.com/chromiecraft/chromiecraft/assets/65800273/156e437a-a71f-4dba-9c11-152c6e9124c0)
![image](https://github.com/chromiecraft/chromiecraft/assets/65800273/bd333c18-ff6d-4f90-a0d7-b3d81f0813f8)

Being Sharable, however, I'm not really sure because there are 2 identical quests with different IDs
Sharable and Both factions https://www.wowhead.com/wotlk/quest=7487/attunement-to-the-core
Not Sharable, Both factions https://www.wowhead.com/wotlk/quest=7848/attunement-to-the-core

I performed a test on PTR, It's currently sharable for horde and non sharable for alliance, Which one is wrong? I don't know.
![WoWScrnShot_061523_202913](https://github.com/chromiecraft/chromiecraft/assets/65800273/c0c9b0d9-a771-4a81-9252-8f3627403ea7)
![WoWScrnShot_061523_203125](https://github.com/chromiecraft/chromiecraft/assets/65800273/8c1b9bc4-804c-470b-8fa0-07585daf5539)

**Comment by cachocarne** [comment]
Thank you so much for taking the time to test this. Next time I will also check the other site you used for checking comments.
