### ISSUE TITLE
Dungeon mobs [not mechanical] immune to bleed effects

### ISSUE THREAD

**Issue by Rentasek** [chromiecraft/chromiecraft#579]
#### WHAT CLIENT DO YOU PLAY ON?

- [x] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Some low lvl dungeon mobs are immune to bleed effect - Feral Cat - [Rip](https://wowgaming.altervista.org/aowow/?spell=1079). Probably other bleeds too.

NPCs :
- [Deviate Shambler](https://wowgaming.altervista.org/aowow/?npc=5761) // Wailing Caverns
- [Twilight Elementalist](https://classic.wowhead.com/npc=4814/twilight-elementalist) // Blackfathom Deeps

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Listed mobs shouldn't have immune for bleed effect, probably only mobs with immune should be mechanicals i.ex. mobs from Gnomeregan.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Come as Feral Cat to Wailing Caverns
2. Stack Combo Points and use Rip
3. Notice that Deviate Shambler is immune to Rip

///

1. Come as Feral Cat to Blackfathom Deeps
2. Stack Combo Points and use Rip
3. Notice that Twilight Elementalist is immune to Rip

##### EXTRA NOTES:

I will probably update list of NPCs immune to bleed effects.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Some notes on this:
The original report was that Deviate Shamblers in WC and Twilight Elementalists in BFD are immune to bleeds. This is correct. Keira shows Twilight Elementalists in particular are immune to almost everything:
![twilight-ele-bleed-immunity](https://user-images.githubusercontent.com/81782124/117562287-f2ef6100-b0dc-11eb-8bf9-c739021499ae.png)

However, did some checking and it led down bit of a rabbit hole. Deviate Shamblers are classed as Type 4, Elementals. The bleed immunity bitmask is 16384 - note this is only picking bleed-immune mobs and so missing other mobs like the Twilight Elementalist that are immune to bleed plus other effects. Doing an SQL search in Keira for bleed-immune elementals returns 199 mob types. (SELECT name FROM `creature_template` WHERE (mechanic_immune_mask = 16384 and type = 4)) Many seem to be correctly bleed-immune - Stone Keepers, Gelkis Rumblers, War Golems, etc. But many of the others are various plant/tree/swamp based elementals.

There seems to be a lot of inconsistency in what is bleed-immune and what isn't. For example, Greater Rock Elementals, Heavy/Solid/Dense Statues and Stone Wardens are affected by bleeds. But Fen Creepers, various Shadethickets, Withervines, Thistleshrubs and Deviate Shamblers, which are plant elementals, are all immune. 

The problem is assigning immunity to mobs in an accurate and Blizz-like way. I'd be quite happy to make the various plant elementals affected by bleed, as that seems like common sense, but we don't have any proof that I can think of to actually verify it.

**Comment by Salehyn** [comment]
As of today's testing on CC PTR, Deviate Shamblers are not immune to bleeds and neither are twilight elementalists. 
I see the report about inconsistencies is still open on AC but the mobs in question here seem to be fixed?
