### ISSUE TITLE
[Black Morass HC] Portal Issues

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5811]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

1. Final bosses portal keeps spawning at least one rotation (3) of mobs. most often it seems that is summons 5-6 adds.
2. when you fight a boss (boss portal 6 and 12), it can happen that the subsequent portal 7 / 13 also opens (further, portal 8 / 14 are then again delayed by 2m30s based from point in time the boss (portal 6 / 12) died)
3. portals after second boss should have a shorter timer
4. break time after boss portal is too long (same as normal mode)

### Expected Blizzlike Behaviour

1. no adds on final bosses portal
2.  when a boss is spawned, no further portals should open (please double check this)
3. e.g. portal 15 -> 16 should be approx 1m30s; 16 -> 17 in 1m20s and 17 -> 18 in 1m25s
4. 122s instead of 150s

### Source

1. https://github.com/chromiecraft/chromiecraft/issues/5584

3. see e.g. https://youtu.be/3GksjINzs8E?t=1682
4. https://github.com/chromiecraft/chromiecraft/issues/5206

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a10c183e99a7c4880420886777e6b3e1c3308965

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by B4nanaboi** [comment]
Are the above issues with Black Morass ever gonna be resolved? black morass still has these issues.

- New portals should not trigger when fighting a boss. When you don't kill a boss fast enough, a new portal opens, and after that, another portal, resulting in a situation where there's never any break.  
- Adds should not spawn when fighting bosses.
- Several portals open at the same time when you can't finish a portal fast enough for whatever reason.
- The break time after killing a boss (IF no other portal opens while fighting the boss), is like 3 minutes+. You just sit there doing nothing. 30-60 seconds should be reasonable to drink.
- If you fail at any point, the instance is mercyless. The shield breaks and that's it. You've just wasted your time.

 If I had to choose, I'd rather do Arcatraz HC at this point, because at least there, you can continue after a wipe. Here's a picture of two portals being up at the same time... Can you guys at least get these portals fixed? It's quite a major mechanic.

![image](https://github.com/chromiecraft/chromiecraft/assets/121559482/43f3f419-395a-4ec4-ab1e-73ac1f4af61c)

**Comment by AcetylGer** [comment]
Bump.

This issue is still unresolved.

**Comment by Cythisiax** [comment]
I am able to replicate this as well.
* Chrono Lord Deja, Temporus, Aeonus spawns the same adds as Rift Keepers. This shouldn't happen as stated with boss portals.
https://streamable.com/t5t33u

**Comment by TheSCREWEDSoftware** [comment]
Linked to AC: https://github.com/azerothcore/azerothcore-wotlk/issues/20705 by @Cythisiax
