### ISSUE TITLE
Rare mob Old Vicejaw not dropping loot

### ISSUE THREAD

**Issue by Stump876** [chromiecraft/chromiecraft#583]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Old Vicejaw Did not drop loot, just some meat.

![image](https://user-images.githubusercontent.com/68164076/117560805-c76d6780-b045-11eb-95c1-3b1f150b64e9.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As with all rare mobs, they should all drop a common (white) quality or higher item. 
[https://wowwiki-archive.fandom.com/wiki/Rare_mob](https://wowwiki-archive.fandom.com/wiki/Rare_mob)
Loot table for Old Vicejaw
[https://classic.wowhead.com/npc=12432/old-vicejaw](https://classic.wowhead.com/npc=12432/old-vicejaw)
While I can't argue that bear meat _is_ a common quality item, I believe it's referring to something you can equip.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .npc add 12432
2. Kill and see if there is loot.
3. Make sure to .npc delete any spawns or it will respawn in that spot
4.

##### EXTRA NOTES:

Testing on a local server, sometimes loot was dropped, sometimes it wasn't.
5/10 dropped loot that was not standard bear loot. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Ragundah** [comment]
Rare mobs are not a guaranteed item drop. Even on (live) classic wow you can sometimes kill rares and have them drop nothing. Rares usually have a higher chance to drop rarer items (IE: https://www.wowhead.com/npc=12431 4-7% drop rates for multiple greens) This however does not guarantee a drop will occur.

**Comment by Azcobu** [comment]
I find the stipulation of a unique item impossible to reconcile with the actual data we have from Blizzard via Wowhead. TBC Wowhead shows Old Vicejaw's drop table (https://tbc.wowhead.com/npc=12432/old-vicejaw), and it doesn't show a 100% dropped green, much less a unique one. If he should be guaranteed to drop a unique item, what is it, and why don't the data tables show any trace of it?

Now I agree that TBC Wowhead is not an ideal source - but it's as close as we can come to definitive data on this NPCs drop table. WOTLKDB would be better, but AFAIK it pulls data from the same source as AC/CC, so it doesn't help here.

As for the quotations, most of the quotes from the first link are of people talking about rare mobs in Cata-era Wow in the present tense, not Wrath in the past tense. So they are not useful, as we know that Cata's rare mob system was different to Wrath's. The first link also specifically says that the system you mention changed in WOTLK ("In WOTLK and Cata, there is a completely different system"). It then claims silver mobs dropped blue items, which makes me wonder if they're referring to rares added during Wrath in places like Northrend. So again, probably not relevant to a Vanilla-era mob in the Old World.

I think for the tables in your second link, he's not counting all kill drops, but analysing all uncommon items that did drop - he's trying to break down the Kalimdor vs Eastern Kingdoms sets drop frequencies. There's no mention of greys or whites in there at all, so that shows he's not looking at their whole drop tables, just the uncommon drops. So unfortunately it's not useful, which is a pity because the level of sheer autism on display there would solve our problem here in seconds.

**Comment by Helias** [comment]
Hello, I also checked tbc wowhead and considering this source I have to agree with Azcobu, but I checked vMaNGOS and TBCmangos and,this rare npc and Gorefang have at least 1-2 loot at 100% or 80%.

I usually use vMangos as a good source for classic, the CMaNGOS team is also a good quality source I think so I would discuss more this topic and taking a chance to add the same reference loot of vmangos and cmangos (tbc).

I think that logically a rare NPC should loot at least one quality item.

**Comment by Knindzagxg** [comment]
Some loot should be always drop.
Poor or common items should always have high % to drop.
Uncommon should have 30% lower then common and as always, rare 60% bellow common.

Some of those Rare mobs have 100% drop chance on specific item and have to be checked carefully to enable it.

**Comment by neifion-00000000** [comment]
![image](https://user-images.githubusercontent.com/91289495/189564591-d20cb8c3-b60a-42d3-a10b-3b9439283bea.png)
First kill, gonna leave a char camped here since this seems like as good of any  mobs to start proving how the drops work
