### ISSUE TITLE
Sha'naar Relics quest

### ISSUE THREAD

**Issue by S3rafym** [chromiecraft/chromiecraft#5899]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

One of the lootable quest items for the Sha'naar Relics (called Sha'naar Relic) is underground. Behind the hut where Aylaan the Waterwaker resides. 

### Expected Blizzlike Behaviour

Quest item shouldn't be underground. 

### Source

Quest item shouldn't be underground. 

### Steps to reproduce the problem

Grab the quest 'Sha'naar Relics'. 
Go right behind the hut where Aylaan the Waterwalker resides.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a779cca9e3a3d673761d6bbe6d1c5d1f51c2f6f3

### Operating system

Win10

### Customizations

None

### Server

ChromieCraft

**Comment by wowquester** [comment]
Tested, confirmed.
![WoWScrnShot_071023_085741](https://github.com/chromiecraft/chromiecraft/assets/138876396/cf9cbdf0-a6c4-4baf-a86e-8a66b853c931)

**Comment by cachocarne** [comment]
This issue seems to still be present in the game. I noticed with two different characters.
![ 2023-06-07 a las 11 17 42](https://github.com/chromiecraft/chromiecraft/assets/77953030/0fbe7db6-1ab6-43de-8f07-5db8d4cc2f6e)
![ 2023-06-09 a las 18 47 04](https://github.com/chromiecraft/chromiecraft/assets/77953030/aac5dce9-6d77-4487-9f63-ceb485a9df5e)

**Comment by koyashi** [comment]
Confirmed the issue is still there.
<img width="1286" alt="image" src="https://github.com/chromiecraft/chromiecraft/assets/7952227/fc6f385f-cb9e-4e20-bd3d-8e6545670b1f">
