### ISSUE TITLE
[SPELL] Lacerate does not generate threat over time

### ISSUE THREAD

**Issue by UndoUreche** [chromiecraft/chromiecraft#5934]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

As of this writing, lacerate only generates threat on cast.

This is the threat generated by lacerate, over a period of time where I stacked it to 5 then let all the stacks drop (X axis is time, Y axis is threatvalue, as provided by the UnitDetailedThreatSituation function).
![chart(1)](https://github.com/chromiecraft/chromiecraft/assets/50205200/43cde798-2f30-4f14-a3b7-92130627fc37)

As can be seen in the graph, lacerate only spiked in threat generation 5 times, corresponding to applications of stacks.

### Expected Blizzlike Behaviour

Lacerate should generate threat both on each application as well as over time, on bleed ticks.

### Source

https://www.wowhead.com/wotlk/spell=33745/lacerate#comments
http://web.archive.org/web/20210416202607/https://wowwiki-archive.fandom.com/wiki/Threat

Lastly, the raw data for the chart, formatted as: *time since start (s)*  ->  *output of UnitDetailedThreatSituation("player", "target")*
[LacerateThreatOutput.txt](https://github.com/chromiecraft/chromiecraft/files/12060836/LacerateThreatOutput.txt)

### Steps to reproduce the problem

Measurement tools used:
-macro that casts lacerate and stops auto attacks
-weakaura tracking CLEU and prints time and threat information on every event caused by lacerate

Apply lacerate
Refresh lacerate as it is about to expire
Notice that the threat only increases when the ability is cast, not when its dot ticks

### Extra Notes

Among the sources there is an archived page of the wowwiki. This is the page furthest in time that was available.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/a8964a6ed1dc9295a85a816e5d11740e90a1fb79

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UndoUreche** [comment]
There is a possibility that lacerate also does not have its threat modifier applied properly, given its current state, however I cannot speak to that as I do not know how much threat it should be doing (all the information I could find in that regard is shoddy at best)

**Comment by Never6** [comment]
> There is a possibility that lacerate also does not have its threat modifier applied properly, given its current state, however I cannot speak to that as I do not know how much threat it should be doing (all the information I could find in that regard is shoddy at best)

The dot does 1 threat for every 2 damage dealt

**Comment by Never6** [comment]
> There is a possibility that lacerate also does not have its threat modifier applied properly, given its current state, however I cannot speak to that as I do not know how much threat it should be doing (all the information I could find in that regard is shoddy at best)

https://youtu.be/HciHmfncLc0
Tankspots bear guide from back in the day

**Comment by Salehyn** [comment]
I cannot reproduce this issue. There might be some error with the Weakauras you used.

https://github.com/chromiecraft/chromiecraft/assets/134880284/a762ccd9-b293-4e9b-ac1e-45574d96e8d3 (no white damage involved, naked druid no talents)

As you can see on this video the initial application does 200+ threat which is largely from the bonus threat applied to the spell since it only does about 30 dmg. There is a steady increase in threat every time the ability ticks, matching the calculations suggested by known formulas (each tick generates half threat per damage, multiplied by the 200%ish bear form modifier, which ends up roughly doing the same threat as damage)
Granted, it doesn't tick for a whole load of damage, but it does generate threat, and it's fairly decent at 5 stacks.

The actually questionable part of the math is the bonus threat on initial application. Most sources are for lvl 80 wotlk and as such speak of a +500ish bonus threat that the rank3 of the spell would give, while the rank1 (lvl 70) value is not mentioned anywhere, and since it's a flat value, it should probably scale with the spellrank. 
Testing with the rank3 spell shows that it generates about 600 threat on application, so the +500 is probably added, but here is the catch: most sources suggest that +500 should be affected by the Bear form modifier, which should double it. 
Based on that, Lacerate might be generating significantly less threat from the initial application than intended. It's a difference between a formula of (base damage + 500~) * 2, or (base damage*2) + 500~, and assuming the rank scaling is correct, this would translate the same way to the rank1 spell but with a smaller bonus number (190ish i'd wager, but as I said, i don't have an exact value for this)

**Comment by UndoUreche** [comment]
This was made back in july and I have not checked since. 

I'll rerun the tests, and I'll check multiple mobs. I tested it against the dummy, but I'll be more thorough. Should the ability generate threat on ticks I'll close the issue (it's only right) but I don't want your findings regarding the formula to be lost. Perhaps it would be a good idea to make another, separate, issue for the threat formula.

**Comment by UndoUreche** [comment]
Indeed I can no longer reproduce my previous findings. Whether it was poor measurement tools or it got fixed in the meantime I do not know, but I will close this issue regardless.

Thank you for taking your time to check it out, @Salehyn. Apologies for the false alarm :)
