### ISSUE TITLE
[Mechanar] Nethermancer Sepethrea drops aggro randomly

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#5950]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Nethermancer Sepethrea drops tank aggro randomly

### Expected Blizzlike Behaviour

aggro shouldnt be dropped. but targets affected by Dragons Breath shouldnt be attacked and the next highest target in the threat list should be attacked, while the higher targets in the threat list are desoriented from the debuff.

if all targets in the threat list are affected by the desorientation, the highest target in the threat list should be attacked (which should also break the desorientation effect)

### Source

https://www.icy-veins.com/tbc-classic/the-mechanar-dungeon-guide

### Steps to reproduce the problem

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp

fight her with more than 1 char

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30197f40d687eae97a07d6730b6933c63f1a3983

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Salehyn** [comment]
This boss has a knockback ability with a threat cut which could lead to aggro drops if your tank wasn't far ahead. In addition, if the tank gets thrown out of melee range he is placed on the ranged threat list which can further contribute to aggro loss.
Are you experiencing these drops when your tank is knocked or does it happen at other times too?

**Comment by Salehyn** [comment]
PTR tests show that tank threat is properly halved when Sepethrea uses her Arcane Blast. She doesn't reset aggro otherwise.

It's kind of strange why none of the guides mention this mechanic, even though it was well known back in the day and documented on wowhead:

By Dennerman [on 2007/03/06](https://www.wowhead.com/wotlk/npc=19221/nethermancer-sepethrea#comments:id=2819185) (Patch 2.0.10)
"The boss will dump aggro from the tank with her knockback and go after other party members. Be ready and don't run away, run the boss right back at your tank so they can get aggro again."

By Tremi [on 2007/07/02](https://www.wowhead.com/wotlk/npc=19221/nethermancer-sepethrea#comments:id=2819428) (Patch 2.1.2)
"When she does the AoE knock back she will target a random member. When this is done just taunt. She can be taunted unlike her elemental buddies."

By Gentaro [on 2007/04/11](https://www.wowhead.com/wotlk/npc=19221/nethermancer-sepethrea#comments:id=2819239) (Patch 2.0.12)
"there are 2 things you must pay attention when facing this boss, 1 are the elemental, just run around. the other is temporary aggro reset against the tank when he throw you away."

Note, these comments are from TBC, but there was no documented change I could find to this mechanic, only her reset range which was set to a closer point on 2.2. to prevent people kiting through the bridge. Until someone can prove that the spell was changed between TBC and wotlk, this is working as intended.
