### ISSUE TITLE
[Arena] Remove team names and MMR from the announcer and remove the /who in arena

### ISSUE THREAD

**Issue by eragonx78** [chromiecraft/chromiecraft#6040]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Hello,

Can you hide the team names in queue and being able to see teams with the /who.
Basically some players wait their team mates to enter then they see the oppenents and then swap spec: as an example arms one game prot another game...
This behavior favor a lot sniping and dodging and something should be done for it.

### Expected Blizzlike Behaviour

You are not supposed to see the enemy teams with /who
You are not supposed to see the players who are in queue at least not the team names

### Source

It always have been like that in wow arena history

### Steps to reproduce the problem

1. Create two team arena team
2. The annoucer gives current the team names and their MMR and your are able to see the players inside the arena with /who, friendlist

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30782ecca84ba5f13539cc58fa13f5ce12da92bb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
> ### Source
> It always have been like that in wow arena history

Please provide a valid source. I cannot find anything on the Internet regarding opponent visibility in /who list whatsoever.

**Comment by Never6** [comment]
> > ### Source
> > It always have been like that in wow arena history
> 
> Please provide a valid source. I cannot find anything on the Internet regarding opponent visibility in /who list whatsoever.
This could be possibly talking about the arena announcer queue that goes on in chat idk 
Which that is custom and was added whoever implemented it and I agree it should be removed 
Even if arena is already dead it stood no chance when it is that easy to snipe and dodge teams

**Comment by heyitsbench** [comment]
> Which that is custom and was added whoever implemented it and I agree it should be removed

That point should probably be left to a [suggestion](https://github.com/chromiecraft/chromiecraft/discussions/new?category=suggestions) rather than an issue report.

**Comment by balleny** [comment]
mostly overlapping with https://github.com/chromiecraft/chromiecraft/discussions/4161

Issue is that on a retail server you can only (and that at best partially) predict whom you gonna play against if you are playing at exceptional high ratings. On small scale servers with a lot less pvp competition (given we dont have xrealm etc either), scouting and predicting enemy teams is a easy way to take advantage of small server size (or to dodge certain teams).

Common approach, as also mentioned in https://github.com/chromiecraft/chromiecraft/discussions/4161 are certain steps
- hide players location if they are in arena (either displaying their latest location before joining) or returning no results for the arena zones

additionally, the arena announcer introduces further issues because
- it includes the arena teams name and hence allows predicting your enemy team
- displays when a team fully joined a game, allowing again to predict the enemy team even better

recommended adjustments are hence
- announcer should only display that a team joined queue and the approximate rating range (e.g. below 1200, 1200 to 1800, above 1800), no names or exiting the queue should be displayed.
- players position status in /who **AND** friendlist should not update / be hidden when inside an arena zone (the hidden option would still allow some kind of "sniping", best would be displaying the latest zone info before joining arena

**Comment by Annamaria-CC** [comment]
As said before, seems to be a suggestion rather than a bug
