### ISSUE TITLE
Mobs casting daze when fighting face to face

### ISSUE THREAD

**Issue by Riphook** [chromiecraft/chromiecraft#61]
##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

When fighting a mob, specifically I was in tirisfal glades and anything I fought was doing it, I am getting dazed cast on me.
https://ibb.co/Rg1gXT5 combat log of it happening

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Dazed shouldn't be cast during a fight face to face...should be cast when running away with your back exposed

##### CURRENT BEHAVIOUR:

I cast a spell on a mob to make it run to me while I stand still. It gets within melee range and combat begins face to face with the mob. Within 5 seconds the mob will cast daze on me https://bit.ly/3oXdRXv (dazed spell) and I am still just face to face with the mob, not moving, and yet it will cast daze on me which is used when running away from a mob and having your back exposed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Engage a mob in Tirisfal Glades (this bug could be server wide but I'm new and don't know)
2. Have the mob come to you so you know nothing else is happening (cast a spell on it to make it approach you)
3. Don't move at all and just fight the mob, it will cast daze on you for no reason.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
[Tirisfal Farmer - Abilities](https://classic.wowhead.com/npc=1934/tirisfal-farmer#abilities)
[Dazed - Used by NPC (3611)](https://classic.wowhead.com/spell=13496/dazed#used-by-npc)

It is not a bug, it is an ability of this NPC, as soon as he is between 20-80% Health he casts the Daze Spell.

**Comment by 55Honey** [comment]
```
SELECT * FROM `acore_world`.`creature_template` WHERE `entry`=1934 LIMIT 1000;
SHOW TABLE STATUS LIKE 'creature_template';
```
![image](https://user-images.githubusercontent.com/71938210/107292781-b2932f00-6a6a-11eb-975f-603d007bfc81.png)
I'm not sure if that applies to 3.3.5 as well. Wowhead refers to classic/retail.

**Comment by illfated** [comment]
If the NPC is a SAI creature, try looking up if it uses a SAI-based script line to cast the spell in combat.

**Comment by Stifler82** [comment]
@55Honey 
The **Daze Spell** was introduced in **Patch 1.13.0 (Patch PRE-TBC)**
The **Dirt Toss Spell** was introduced in **Patch 4.0.3 (Cataclysm)**

In the middle of these 2 Expansions is **TBC** and **WTLK**, so it is reasonable to think that the **Spell Daze** remained in the **Tirisfal Farmer** NPC until **patch 4.0.1a (Cataclysm)** and later in **patch 4.0.3 (Cataclysm)** was replaced with **Dirt Toss**.

In addition, you checked the wrong DB table, you had to check the **smart_scripts
![Tirisfal Farmer00](https://user-images.githubusercontent.com/1884642/107299971-7e227180-6a70-11eb-859f-6f4923ed4d69.png)
![Tirisfal Farmer01](https://user-images.githubusercontent.com/1884642/107299975-811d6200-6a70-11eb-86b0-243a81f56767.png)

https://user-images.githubusercontent.com/1884642/107299991-867aac80-6a70-11eb-999e-ad8f1cfc3130.mp4



** table

**Comment by 55Honey** [comment]
> The **Daze Spell** was introduced in **Patch 1.13.0 (Patch PRE-TBC)**
> The **Dirt Toss Spell** was introduced in **Patch 4.0.3 (Cataclysm)**
Thx for clarifying this!

**Comment by necropola** [comment]
Are there actually 3611 NPCs in game that can cast Daze randomly in combat as opposed to just when you run away from them (which I thought)? The amount of Daze going on in Tririsfal Glades is insane. Every Plaguehound uses this "ability" pretty much as an "opener" when you engage in melee and are directly facing it. This is clearly not how I remember the game.

**Comment by 55Honey** [comment]
![image](https://user-images.githubusercontent.com/71938210/107851023-ed002180-6e06-11eb-9a0d-fd1d599e392a.png)
![image](https://user-images.githubusercontent.com/71938210/107851047-259ffb00-6e07-11eb-9b4b-fc3071a3586f.png)
Since i could not find any Plaguehounds in Tirisfal, i assume u mean https://wotlkdb.com/?npc=1549 and https://wotlkdb.com/?npc=1547
No matter what i do, they do not daze me from the front. If you are still convinced this is an issue, please provide exact reproduction steps. Race, class, level, screenshot of the character stats, the mobs exact name, link and location. 
Ideally make a video with your combat log laaaaaarge and visible.

**Comment by necropola** [comment]
Yeah, I meant Darkhound. Sorry, but lots of melee NPCs will show this behaviour. I noticed that you **need to be attacking in order to get dazed**. Just standing there does not trigger it.
Steps to reproduce.
1. Target a Melee NPC in Tirisfal Glades, e. g. Darkhound
2. Activate Attack
3. Approach the NPC until it runs towards you (to your face)
4. As soon as you swing you get dazed

**Comment by Stifler82** [comment]
> Yeah, I meant Darkhound. Sorry, but lots of melee NPCs will show this behaviour. I noticed that you **need to be attacking in order to get dazed**. Just standing there does not trigger it.
> Steps to reproduce.
> 
> 1. Target a Melee NPC in Tirisfal Glades, e. g. Darkhound
> 2. Activate Attack
> 3. Approach the NPC until it runs towards you (to your face)
> 4. As soon as you swing you get dazed
> 
> I was able to reproduce this on a Level 7 Undead Rogue dual wiedling daggers and a level 16 Blood Elf Paladin wielding a 2h Axe. Haven't tried other melee classes yet.

What WoW Client Version have you? (enUS or enGB)?

**Comment by necropola** [comment]
enGB

**Comment by Stifler82** [comment]
> enGB

Good, Delete it and Download enUS.
enGB is the most buggy version of WOW in WOW history.
That version of WoW shows Bugs that DO NOT EXIST.

**Comment by 55Honey** [comment]
![image](https://user-images.githubusercontent.com/71938210/107855165-10d06100-6e21-11eb-98a6-6d1359c439e1.png)
Confirmed as a level 7 rogue. Hits only from the front.

**Comment by necropola** [comment]
Good.
Still downloading the enUS client. Don't wanna run a buggy client ...

**Comment by Stifler82** [comment]
> Good.
> Still downloading the enUS client. Don't wanna run a buggy client ...

Ok, I confirm the bug exist also with enUS, the problem is the A.I. because who did it put a Simple cast and not "Behind target"

**Comment by Stifler82** [comment]
In any case the problem with enGB it's still valid..

**Comment by necropola** [comment]
Getting there ... 3.0/16.6 GB ... Anything, if it helps to improve the server ...

**Comment by Stifler82** [comment]
> Getting there ... 3.0/16.6 GB ... Anything, if it helps to improve the server

@necropola 
It doesn't help the server to have a good game Client, it helps your gaming experience, I started playing WoW in 2007, and I can confirm with extreme confidence that many times it happened that those who had the enGB Client saw and were affected by Bugs that those who had the enUS Client didn't have..

**Comment by necropola** [comment]
Assuming that I continue to file bug reports it also helps to improve the server, because we can eliminate one possible (invalid) cause right away. The buggy enGB client. :-)

**Comment by FrancescoBorzi** [comment]
@necropola thanks Necropola!

**Comment by Riphook** [comment]
I'm disappointed with the lack of professionalism in the handling of this matter. I reported a valid bug and have had nothing but a flooded inbox and a ridiculous response to an obvious bug. My faith in this server is obviously lost sadly. I highly recommend that further bugs are discussed as a team (staff/volunteers) and not out in the open like this as it has shown nothing but incompetence with handling issues. Obvious bug, obvious cause, horrible staffing response.

**Comment by 55Honey** [comment]
> I'm disappointed with the lack of professionalism in the handling of this matter. I reported a valid bug and have had nothing but a flooded inbox and a ridiculous response to an obvious bug. My faith in this server is obviously lost sadly. I highly recommend that further bugs are discussed as a team (staff/volunteers) and not out in the open like this as it has shown nothing but incompetence with handling issues. Obvious bug, obvious cause, horrible staffing response.

You did not even provide which mob was affected initially. Others being unable  to confirm incomplete reports is not about incompetent or horrible staff at all, but about an incomplete report with lots of questions asked to be able to reproduce it.
We're not clearvoyants here.

**Comment by Stifler82** [comment]
> I'm disappointed with the lack of professionalism in the handling of this matter. I reported a valid bug and have had nothing but a flooded inbox and a ridiculous response to an obvious bug. My faith in this server is obviously lost sadly. I highly recommend that further bugs are discussed as a team (staff/volunteers) and not out in the open like this as it has shown nothing but incompetence with handling issues. Obvious bug, obvious cause, horrible staffing response.

@Riphook 
Aside from the fact that an oversight happens to anyone, we are human after all, but leaving that aside.
As I said at the beginning, this type of NPC (HAS) the Daze as a spell. what I misunderstood was the fact that the NPC does the "Front" Daze instead of "Back".

Can I get a blunder from time to time too?
Like all the rest of the human race, if I cut myself I bleed too, and this makes me a "Fallacious" human being, as indeed you are, who spits sentences, without knowing people, just because (as a child throwing tantrums) you didn't get the lollipop from Dad right away when you asked for it.
But you are forgiven, you are a human being too.

**Comment by Riphook** [comment]
Lol good luck with your server guys...you'll need it

**Comment by necropola** [comment]
Not only many NBCs in Tririsfal Glades and Silverpine Forest are affected. [Young Black Bear](https://wotlkdb.com/?npc=1128) daze from the front, too. I hope you can run some sort of DB query to find all cases, since the problem seems tio be rather widely spread.

**Comment by Stifler82** [comment]
@necropola

Fixed all Mobs with this issue!
-
- **Video Test:** [Mobs casting daze](https://youtu.be/feU1B9hq_-o)

**Comment by illfated** [comment]
Nice. Just remember: "No good deed goes unpunished..." 😉

**Comment by Stifler82** [comment]
> Nice. Just remember: "No good deed goes unpunished..." 😉

@illfated 
I apologize, but I don't understand what you mean.

however I want to clarify:
That **this "Daze"** isn't the **"Daze - Global - Game Mechanics"**, this Daze that some Mobs had and used it in front of the Player, **was a "Spell"**, therefore a **different "Daze"**, in fact the **Daze (Of global mechanics )** has a **duration of 5sec**, while **the Daze of these mobs has a duration of 9sec**.

**Comment by illfated** [comment]
OK, sorry. Just trying to be ironic, but I guess the joke failed. I felt good seeing your previous post, but I also felt like smiling, cheering and at the same time saying to both you and myself: "Don't be too happy, there is always something else to worry about." Never mind. Not important at all. Better suited for a discussion page. Thank you.

**Comment by Stifler82** [comment]
> OK, sorry. Just trying to be ironic, but I guess the joke failed. I felt good seeing your previous post, but I also felt like smiling, cheering and at the same time saying to both you and myself: "Don't be too happy, there is always something else to worry about." Never mind. Not important at all. Better suited for a discussion page. Thank you.

@illfated 
Forgive me, but English is not my language.
So sometimes it can happen that I fail to grasp some saying, or metaphor.

**Comment by necropola** [comment]
> however I want to clarify:
> That **this "Daze"** isn't the **"Daze - Global - Game Mechanics"**, this Daze that some Mobs had and used it in front of the Player, **was a "Spell"**, therefore a **different "Daze"**, in fact the **Daze (Of global mechanics )** has a **duration of 5sec**, while **the Daze of these mobs has a duration of 9sec**.

Any idea, why and when this weird **9 second daze from the front** was added?

**Comment by Stifler82** [comment]
@necropola 

> > however I want to clarify:
> > That **this "Daze"** isn't the **"Daze - Global - Game Mechanics"**, this Daze that some Mobs had and used it in front of the Player, **was a "Spell"**, therefore a **different "Daze"**, in fact the **Daze (Of global mechanics )** has a **duration of 5sec**, while **the Daze of these mobs has a duration of 9sec**.
> 
> Any idea, why and when this weird **9 second daze from the front** was added?


back then, the story "from the front" was a Bug, no one added anything ..
Simply these mobs, instead of giving them any spell that could be, what do I know .. an intercept, or fireballs, they put the "Daze" on them, when, how and why it happened, I don't know. to say..

What I know for sure is that this spell was present in these mobs, both in vanilla and in TBC and that later in Cataclysm it was replaced, what happened in WTLK, is a mystery.
I checked the WTLK patch notes and found no references to this change, if you want to post the link and check it too.

[WTLK - Patch Notes](https://www.toxicgaming.us/wow/wrath-patch-notes/)

**Comment by necropola** [comment]
After doing some further investigation in https://github.com/chromiecraft/chromiecraft/issues/223#issuecomment-802645816 I'd say that spell=13496 (10s daze from anywhere) should be removed from creature SAI entirely. They already have access to spell=1604 (3s daze from behind) via core functionality.

**Comment by 55Honey** [comment]
> After doing some further investigation in [#223 (comment)](https://github.com/chromiecraft/chromiecraft/issues/223#issuecomment-802645816) I'd say that spell=13496 (10s daze from anywhere) should be removed from creature SAI entirely. They already have access to spell=1604 (3s daze from behind) via core functionality.

Check #4641 in the azerothcore master repo. Its also linked above ;-)

**Comment by Stifler82** [comment]
> After doing some further investigation in [#223 (comment)](https://github.com/chromiecraft/chromiecraft/issues/223#issuecomment-802645816) I'd say that spell=13496 (10s daze from anywhere) should be removed from creature SAI entirely. They already have access to spell=1604 (3s daze from behind) via core functionality.

@necropola 
I would say instead, that it would be better if you looked at issues that are not related to spells, and that this dilemma that you raised, we will take it up again (later) when Blizzard puts more precise information on Wowhead about the TBC and WOTLK expansions, because in based on the information we have now, we are unable to verify if this NPC has this spell or not..

**Comment by necropola** [comment]
**Doubly dazed by a level 5 [Decrepit Darkhound](https://wotlkdb.com/?npc=1547)**
Still 4 of 10 seconds from SAI spell=13496 and 2 of 3 seconds from core spell=1604 to go.
![image](https://user-images.githubusercontent.com/7461137/111839307-e6c7fe00-88fa-11eb-8c1d-e42ceb3f5409.png)
Reopening ...

**Comment by 55Honey** [comment]
what would you want to change? we don't know how to make it better in terms of -more blizzlike-, do we?

**Comment by necropola** [comment]
Simply remove the SAI spell/daze entirely, because
- it does not make any sense for these creatures to have an additional and completely OP daze
- we know that the core daze is working as intended
- we know that the core daze is meant to be noob friendly
- we have no reliable source telling us that they should have this OP daze (**in addition**)
- we have no idea how/why this was added to AC world DB
- the spell id used for this daze belongs to the Mug O' Hurt proc

The only argument against removing it is the mere fact that it's currently there.

**Comment by Stifler82** [comment]
So, [The case is closed!](https://youtu.be/wMlGnZmGVlE)

**Comment by necropola** [comment]
Since it looks liek you are not actaully interesetd in fixing busg, I will no longer waste my time trying.
Bye!

**Comment by Stifler82** [comment]
> Since it looks liek you are not actaully interesetd in fixing busg, I will no longer waste my time trying.
> Bye!

@necropola 
But see dear Necropola, I did not say I will not remove this spell;
**I just said that:** _(since we do not have enough data to know if it is right that these NPCs have this spell or not)_,
**I just said:** _"Let's wait for the Blizzard put on Wowhead at least the TBC, because that data will surely be much more accurate .. "_

**Simply, I'm saying that:** _(Since spell does not provide any bugs, and since it does not create any bugs by definition (NOT A PROBLEM)_, **I am simply postponing something until we have more data.**

**Comment by Stifler82** [comment]
Look! I also created the LABEL WFMD **(Waiting For More Data)**
Per dimostrarti che non sto scherzando!

**Comment by FrancescoBorzi** [comment]
if someone thinks this is still an issue, please open a new bug report. Enough drama here.
