### ISSUE TITLE
Eastern Plague Zone - Chest timer inaccurate or missing

### ISSUE THREAD

**Issue by Jinmcx** [chromiecraft/chromiecraft#610]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

##### CURRENT BEHAVIOUR:

Chest missing in area according to: https://wotlkdb.com/?object=153453
- 35.5, 69.2

The follow chests doesn't respawn in 2 hours or during restart. Sometimes they appear.
- 56.1, 62.4 | 54.3, 64.7

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Chest Respawn in 2 hours.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Open chest and wait 2 hours no respawns, or chest is missing in the area.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. However, all three of these chests do exist and are on 2 hour timers:

![WoWScrnShot_051221_000342](https://user-images.githubusercontent.com/81782124/117833828-d2c6ca00-b2b5-11eb-911d-f3494803ee25.jpg)

The reason you are not seeing them reappear as often as 2 hours is that many or all of these chests are now 'pooled'. This means they are part of a larger group of chest spawns, so that when a chest in the pool is looted, it might not necessarily reappear after 2 hours. Another chest elsewhere in the zone might spawn instead. This system is how Blizzard handles chests, and was done to stop people parking alts there and farming them 24/7. The first chest you mention, which originally had a 3 minute timer and no pooling, was especially vulnerable to such abuse.

**Comment by Azcobu** [comment]
Winterspring chests respawn timers have been adjusted in this AC issue: https://github.com/azerothcore/azerothcore-wotlk/pull/5695, although it looks as if pooling all of them is still yet to be done, hence your findings. It does look like they're on the list to be done however, so a new ticket shouldn't be necessary, thanks all the same.

**Comment by Jinmcx** [comment]
Following up on the original ticket, Chest: 72.5, 69.8 | 77.5, 72.6 | 75.1, 78.3 | 77.6, 78.0 | has a respawn consistency similar to winterspring (individually and 2 hour timer) I believe they should be pooled.

**Comment by Azcobu** [comment]
For future reports, I suggest standing near the chest and typing '.gobject near' (with full stop, no quotes.) That outputs a GUID (a database reference to that unique object) and some type and location data. It's much easier to run around checking chests with a GUID than with map coordinates.

72.5, 69.8 = 45938
77.5, 72.6 = 45933
75.1, 78.3 = 85797
77.6, 78.0 = 100086

All 4 chests are referenced in https://github.com/azerothcore/azerothcore-wotlk/pull/4947 as being added to the EPL pool (see https://github.com/azerothcore/azerothcore-wotlk/pull/4947/files for the actual list) - though that original PR mentions a 900 sec/15 min respawn as opposed to 2 hours - not sure how the pool and individual timers interact, though.

**Comment by Jinmcx** [comment]
Thank you for the tip!
