### ISSUE TITLE
Stuned people that jump or are on mount do not land on proper position

### ISSUE THREAD

**Issue by JureVeraja** [chromiecraft/chromiecraft#657]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [ X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When you stun someone with rogue let's say, and that person is on mount or jumping, when you stun him in mid air and he lands stunned, his position is not properly accumulated. For example when you go to attack him after stun, he is not there you can't attack him. He is actually in the position where his jump started.. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you stun someone he should be there where he is showing up, not in some imaginary position.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8dd58ebb5bea6a8aada54c830d06974d3ecd1353

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Tried testing this and might have captured what you're reporting here:

https://user-images.githubusercontent.com/81782124/118479753-903b3c80-b750-11eb-8169-ceafc62b771e.mp4

That stutter forward after the stun ends looks suspicious. But I didn't have any problems attacking the stunned target because the distance was never all that great, even if the target was riding a very fast mount, as in this case. (I can't test attacks against a jumping target because I only have two hands, so attacking on one screen and timing a jump on the other isn't going to work.) Was this the sort of scenario you were encountering?

**Comment by Korghan905** [comment]
what's up about that bug ?
what feedback is needed ? It's very easy to reproduce it, just play a BG as a warrior or a rogue and you'll notice it very fast. 

It is very impacting on PVP and as you're trying to balance it atm with resilience I don't understand why this bug isn't more documented or discussed...

**Comment by Azcobu** [comment]
I had wanted to check that the video showed what you were talking about, as it wasn't while the target was in mid-air, and it didn't stop me attacking them. But it seems that was the right issue, so posting it anyway.

As for lack of documentation, we don't test in BGs on live servers for obvious reasons, and we've had no other reports of this that I know of, which is odd.

**Comment by Korghan905** [comment]
it wasn't me posting it but I reported the same bug on another issue. I don't know GitHub very well but other similar issues should be closed but kept as reference on the main issue maybe ?

Anyway it's not so easy to post here and that would explain the low discussion of this bug here. 

It does indeed stop from attacking if the distance is long enough. And as a warrior in pvp i often have to intercept after charge to start engaging.

**Comment by Never6** [comment]
dis still broken :(
