### ISSUE TITLE
Bugging final doors in "The Deadmines" using Pick Lock.

### ISSUE THREAD

**Issue by Istox** [chromiecraft/chromiecraft#69]
##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
It is possible to permanently bug the doors shut that lead to the final chamber in The Deadmines. With a rogue in party using Pick Lock on the doors while somebody else uses the cannon.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Firing the cannon to explode the doors should result in the rogues Pick Lock cast either being interrupted or never successfully completing.

##### CURRENT BEHAVIOUR:
The Pick Lock cast completes even though somebody has fired the cannon, which results in the doors bugging shut permanently.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 With a rogue, Start cast Pick Lock
Step 2 While the rogue is casting Pick Lock, have somebody use the Defias Cannon
Step 3 Pick Lock cast will finish and bug the doors.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Istox** [comment]
@Stifler82 There is absolutely adequate information in this ticket to replicate the issue.

**Comment by Istox** [comment]
You need two different accounts to replicate this as per description. I presume ghostrider was multiboxing to test this?

**Comment by Stifler82** [comment]
> You need two different accounts to replicate this as per description. I presume ghostrider was multiboxing to test this?

I figured out it..

**Comment by Stifler82** [comment]
Ok, having finally figured out what the problem was, **I then did my Test**, and **I confirm** that the Spell [Pick Lock](https://wowgaming.altervista.org/aowow/?spell=1804) **is not interrupted by the Cannon**, this is because **the Cannon doesn't open the door through a spell** that interrupts the Pick Lock, but **it opens by changing the Status of the Game Object by SmartAI**, so there is no interruption.

Honestly, I wouldn't consider it a real Bug, but a **Game Mechanics paradox.**

**Comment by Stifler82** [comment]
The Bug cannot be fixed, also because it is not a real Bug, it is a paradox of game mechanics (as I explained in the previous comment).

And I don't see why if you have a Rogue in Party you have to use the cannon, just as I don't see why if you have the item for activate the Cannon, the Rogue should open it manually.
The point is: if you already have one way to open the door, don't use the other way.

**Comment by illfated** [comment]
I have heard about "shooting 2 birds with 1 stone", but this issue looks more like trying to shoot 1 bird with 2 stones... 😄 🤣
