### ISSUE TITLE
[Hyjal] First wave should not grant reputation

### ISSUE THREAD

**Issue by balleny** [chromiecraft/chromiecraft#6923]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

not checked yet, this is more a fyi type of report

### Expected Blizzlike Behaviour

first wave in hyjal raid should not grant any reputation (loot isnt affected)

### Source

1st wave
https://youtu.be/qvQmLlN2Rzs?t=61

2nd wave
https://youtu.be/qvQmLlN2Rzs?t=118

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/482f4c94ffdb9cd859482d977aa31a18a60ef8d9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cooties-cc** [comment]
Seems to be patch 2.4 that added more rep to mobs. 
Comment from Ghoul NPC on WH
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/ef59116c-96a8-48d5-b7f9-85d9e3b4ccfe)
Checking patch notes, no direct mobs said, but more than likely were added under this part
![image](https://github.com/chromiecraft/chromiecraft/assets/62584589/b37506ff-9ef5-4991-ac97-7b415f51bd04)

More than likely a _non-issue_ to nerf rep. Full clears post 2.4 take around 5-6 full clears to hit exalted. Removed basic mobs, it's probably around 2 months or so. Each patch cycle thus far is around 3 months avg. This as also assuming no intentional trash resets to just farm rep day 1. 
However again, up to prog mod to remove, or keep as is for "wotlk client" ver.

**Comment by balleny** [comment]
may end up being more a progression topic then, but maybe, someone is also able to verify on a retail ptr

**Comment by Gultask** [comment]
Just speculation on my part but I think it's more tied to loot than reputation. As either are tied to npc entry and all entries are the same as any other for the first wave. For example, in Black Morass trash *sometimes* grant reputation when killed, because there's 2 variations for each mob, and only a few grant experience.

On Retail, there's a mechanic that prevents the first wave from dropping loot, which I think it's a damage threshold. If not enough damage is dealt by players in the wave, they won't be liable for loot or rep. But scaling could have messed with it so there's not enough damage one can deal to the first wave to allow for loot and rep.

**Comment by amed80** [comment]
i think this may help with this report:
https://www.bluetracker.gg/wow/topic/us-en/1778585486-rep-loot-in-hyjal/
