### ISSUE TITLE
Mobs casting while fleeing

### ISSUE THREAD

**Issue by Toniculus** [chromiecraft/chromiecraft#699]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If a mobs is about to cast while you hit him to the hp to start fleeing , he will cast while fleeing 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

mobs should not cast while fleeing and if the dmg had been done to the point of the mob to flee , he will stop casting and start toflee

##### STEPS TO REPRODUCE THE PROBLEM:

1.  when a mob is about to cast dmg it to the point of feeling
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Which mobs in particular are doing this? 

I ask because there's an open ticket for this behaviour already here - https://github.com/azerothcore/azerothcore-wotlk/issues/5515 and https://github.com/chromiecraft/chromiecraft/issues/658 - but that's just dealing with Hillsbrad Miners in Azurelode Mine and some mobs in Ulda. If other mobs are doing this as well, please let us know which ones they are. If you type '.npc info' (with the full stop and without quotes) and take a screenshot of the mob and the output, that should help identify if other mobs are also behaving incorrectly.

**Comment by Toniculus** [comment]
> Which mobs in particular are doing this?
> 
> I ask because there's an open ticket for this behaviour already here - [azerothcore/azerothcore-wotlk#5515](https://github.com/azerothcore/azerothcore-wotlk/issues/5515) and #658 - but that's just dealing with Hillsbrad Miners in Azurelode Mine and some mobs in Ulda. If other mobs are doing this as well, please let us know which ones they are. If you type '.npc info' (with the full stop and without quotes) and take a screenshot of the mob and the output, that should help identify if other mobs are also behaving incorrectly.

Yea the mobs in uldaman Stonevaults oracle and those in hillsbrad .

**Comment by Azcobu** [comment]
Ah right, well if it's just those two I'll put this down as a duplicate, as we already have tickets for them. If you run into any other NPCs doing it though, feel free to let us know.

**Comment by formiclol** [comment]
@Azcobu Ran into a Thistlefur Totemic in Ashenvale (https://wotlkdb.com/?npc=3922) doing this in the cave.  Got down to a sliver then it ran off and started casting its Healing Ward skill:

https://user-images.githubusercontent.com/84552520/120742154-428e3600-c4ab-11eb-8c82-289745f808f3.mp4

**Comment by Azcobu** [comment]
@formiclol Thanks for the report and the video, I'll check the Thistlefurs out. Interesting it's Healing Wave again, one of the other reports in https://github.com/chromiecraft/chromiecraft/issues/658 was of fleeing Stonevault Oracles casting that.

**Comment by Azcobu** [comment]
Oops, Healing Ward not Healing Wave. Had another go at this in the Thistlefur cave, but couldn't get any of them to behave like this. However, looking at one of the related issues, a PR to fix it is due to be merged soon. (https://github.com/azerothcore/azerothcore-wotlk/pull/6030). This one addresses mobs animating when fleeing, so probably worth waiting until that's live and checing to see if that resolves it.
