### ISSUE TITLE
Pattern: White Leather Jerkin drop

### ISSUE THREAD

**Issue by SniperGiova** [chromiecraft/chromiecraft#7065]
Recently have found this pattern on mobs from 50+ in area like WPL EPL and Burning Steppes.
It shouldn't drop at all at that lvl/area and that often (like 10 times between yesterday and today). There must be a bug in the loot list or whatever.
Anyone can check this out?
![WoWScrnShot_052324_181859](https://github.com/chromiecraft/chromiecraft/assets/161776468/b987b7cb-aed3-4a90-bcef-785456a838a6)

**Comment by heyitsbench** [comment]
CC: @Gultask

**Comment by Gultask** [comment]
Found the issue. I took a lot from Mangos and it seems I've mistaken a placeholder for a full table and ported it over when I was porting several at once and it slipped my eye. This is my bad, I've already made a quick fix for it.

I don't believe any recipes were lost and are now inacessible from the rework because I've only deleted those that are covered by one table or another.

Thanks @heyitsbench and @SniperGiova
