### ISSUE TITLE
Food Buff's Stacking

### ISSUE THREAD

**Issue by zwillan** [chromiecraft/chromiecraft#731]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Food buff's from https://wowgaming.altervista.org/aowow/?item=33004 and https://wowgaming.altervista.org/aowow/?item=13931 and possibly many others are currently stacking with one another.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Food buff's should not stack with each other. I was able to find some evidence from comments here during retail WOTLK: https://www.wowhead.com/forums/topic/i-need-a-buff-stacking-guide-69716. Although it is not from 3.3.5a patch specifically, I could not find any information about food buff's ever being able to stack. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. eat https://wowgaming.altervista.org/aowow/?item=33004 for buff
2. eat https://wowgaming.altervista.org/aowow/?item=13931 for buff
3. Observe both buffs stacking

##### EXTRA NOTES:

https://wowgaming.altervista.org/aowow/?item=33004
https://wowgaming.altervista.org/aowow/?item=13931
https://www.wowhead.com/forums/topic/i-need-a-buff-stacking-guide-69716

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Can't confirm that:

![WoWScrnShot_053021_053434](https://user-images.githubusercontent.com/82579073/120090144-d6a57980-c108-11eb-8e02-cd682f6eb455.jpg)

Also, Nightfin Soup doesnt seem to have any buff. 

Thanks for the report likewise.

**Comment by Azcobu** [comment]
Nightfin Soup gives a buff, it's showing in your screenshot:

![WoWScrnShot_053021_213423](https://user-images.githubusercontent.com/81782124/120103588-7ad20380-c18f-11eb-9ca5-53382c260682.jpg)

I think this is a real issue. There is a TBC-era comment on WH that the soup 'does not give you the "Well Fed" buff, but it also does not stack with "Well Fed"' (https://tbc.wowhead.com/item=13931/nightfin-soup#comments:id=161753:reply=17067) which it is currently doing on CC. 

As I understand it, the rule was that only one food buff and one drink buff can be active at any given time, including but not limited to, ones that state Well Fed. (And soup, despite being liquid, counts as a food rather than a drink.) So it seems these two buffs should not be stacking.

**Comment by anguaive** [comment]
Nightfin Soup also applies the buff immediately, whereas with other foods you have to eat for 10? seconds for the buff to take effect. This worked the same way in TBC according to Korasoff's comment: https://tbc.wowhead.com/spell=18243/nightfin-soup#comments

Poached Sunscale Salmon is another one I've found - it stacks with both the Nightfin mana regen buff and the Well Fed buff.

**Comment by Azcobu** [comment]
Just guessing here, but the instant buff from Nightfin/Poached Salmon is possibly why they stack. 

> There are also items, such as the  [Deviate Fish], that can be 'used' (presumably ingested) that are not food in any other way, acting more like a potion. These do not require the sitting and remain seated process and any buffs they confer are not 'well fed' buffs (and thus can be applied in addition to a well fed buff). (https://wowpedia.fandom.com/wiki/Food)

Perhaps the other instant effect foods like Nightfin/Poached Salmon are incorrectly exempted from the shared cooldown because of that, even though they do give actual food buffs.

**Comment by Eldarix** [comment]
So you are refering to the mana regeneration as buff ^^ I with my friends have always considered buff only something that gives you a temporal bonus xD

**Comment by Eldarix** [comment]
It seems that it was not just me and my friends thing:

'Buff: An empowering effect, applied to allies.'

Extracted from:

https://classic.wowhead.com/guides/classic-wow-glossary-terminology

So i hope that answer your doubts, applies immediately because like i said before, it has no buff effect, what you are talking about is just the tooltip for the regeneration to be visible.

Have a nice week pals :)

**Comment by anguaive** [comment]
Similar mp5 consumables (Smoked Sagefish, Sagefish Delight) are not instant, and they're treated as regular food, i.e. they grant the Well Fed bonus. The tooltip on food items clearly states that you need to remain seated for a while. There's nothing that suggests that Nightfin Soup should be treated differently here. This *is* a bug if you ask me, and it's a bug that Blizzard chose not to fix for the 2.3.0 patch, and they might've kept it in during WoTLK too for all I know.

About the terminology: I've always considered 'buff' and 'temporary bonus to something' synonymous. So for me the mp5 from the Nightfin Soup qualifies as a buff - it's a temporary bonus to your mana regeneration stat.

**Comment by Eldarix** [comment]
awesome ;)

do whatever you consider best ^^

**Comment by Stump876** [comment]
I think it was something intentionally left. It was said this is not actually a "well fed" buff so it probably should stack. Also, they had patched out the stacking buffs from rumsy rum and other drinks that provide stamina in 2.1. This could have easily have been added to the list. 
![image](https://user-images.githubusercontent.com/68164076/120157824-4585df80-c1a8-11eb-9252-0b4f612658d6.png)

**Comment by Azcobu** [comment]
Well, the one piece of actual evidence we have from Wowhead says it should not stack: [Nightfin Soup] 'does not give you the "Well Fed" buff, but it also does not stack with "Well Fed"' (https://tbc.wowhead.com/item=13931/nightfin-soup#comments:id=161753:reply=17067)

I'm with @anguaive on the meaning of buff, Wowpedia has it as "a temporary beneficial spell or effect placed on a player" which the mana replenishment is. Never came across a different useage until now.

**Comment by Eldarix** [comment]
Nice, always exists a first time :)

With the amount of people who have made the same reference to the meaning to me for so many years, it's also the first time that I have met such stubbornness for something that is not that important.

Take care and enjoy !!

**Comment by Eldarix** [comment]
Now I understand perfectly what has happened, when I read the Nightfin Soup tooltip I thought I saw that it said the typical thing that it restores you mana for 15 seconds while you drink, so I kept that in mind, so much so that when I saw your screenshot it also seemed the same to me and didn't realize, from there I could not understand why so much insistence on something that I always saw clearly xD

We were talking about the same. My bad.

**Comment by Nefertumm** [comment]
Closed by https://github.com/azerothcore/azerothcore-wotlk/commit/4765f8d5daf4c24704fcb6cbcbb42a0972441b4b
