### ISSUE TITLE
drop rate of wrathguards, fel handlers and doom whsiperers at the wrath gates my be to high

### ISSUE THREAD

**Issue by gryer7421** [chromiecraft/chromiecraft#7435]
### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

i am grinding off a few levels and seeing much higher than then expected green and blue drops from the mobs at the wrath gates in hellfire peninsula. in the last few days i have seen up to 18 blue drops from these mobs  

### Expected Blizzlike Behaviour

the blue drop rate seems much higher than blizlike,  the green drop rate is high as well but is not as out of spec as the blue drops

### Source

.

### Steps to reproduce the problem

i ran a time for 60 minutes.  stopping the timer for player deaths and stopped the timer for going to thralamar to sell grays and send off cloth.

in 60 minutes kills as many wrathguards, fel handlers and doom whispers as possible. calculate the drops by dividing the number of green drops by mob killed count for the green drop rate and then the number of blue drops by the number of mobs killed.

each result is the % rate of the drops 

### Extra Notes

toon this was run on was fayel,  60 lvl troll warrior in revenge build mode,  no buffs

attached log of units killed and math screencap and inventory screencap after 60 minute run

![items all](https://github.com/user-attachments/assets/112d9b39-b757-4b82-888c-64ea78914669)
![maths drops](https://github.com/user-attachments/assets/c78ff7b1-1038-49d1-a3d3-02d4626a969a)

[units.killed.names.list.csv](https://github.com/user-attachments/files/17466949/units.killed.names.list.csv)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/572be7d69f8b9a0100d95ecaa045247e574c38a4

### Operating system

win10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Unfortunally I don't know if the drop rate on AC is perfectly configurated like the official servers.
Anyway I also had the impression that the drop rate from standard npcs is too high.

I need a second opinion about this issue.

**Comment by TheSCREWEDSoftware** [comment]
@gryer7421 first of all thanks putting the time into making the CSV file with your testing in the world related to the drops.

ChromieCraft tends to follow AzeorthCore Data. And the changes that CC has from AC tends to be restricting content or balancing existing creatures or bosses (1 of many things but simplified).

I was checking the module responsable for the "progressive" of the server. And in there's no changes to the loot of the creatures mentioned above. So it means the data we are currently using (the spawns, their loot %, money drop, etc...) comes all from the same Information AzerothCore, so you're getting 3.3.5 loot drop rates, assumed. Because gathering official data for this things isn't like gathering what spells a creatured used, or how they path. It's something that has be counted and averaged upon X amount of times.

Quoting from a AC post that i answered related to money drop being too low in some mobs.

> Sadly this issue isn't an easy one to tackle. There's no way to get accurate data of the money amount they should or not  drop. And without killing the same mobs over X amount of times (more than 1'000 kills to get at least an average of how much they should be dropping).
> 
> If you dont have that type of data, of X amount of average money over 1'000+ of the mob, I would recommend you opening an PR with your suggested changes. But with no source (not just a video of someone farming gold) may be enough to get the PR accepted. 

So the mobs currently probably are dropping more than expected TBC and assumed it matches WOTLK drop rates.

I hope I was able to give you some insight related how the solution this issue is. To add to all the above, I will be closing this issue but don't feel discourge in the future to report more situations you encounter in ChromieCraft!

Once again thanks for the report :)
