### ISSUE TITLE
Way too much Ores in RedRidge Mountains

### ISSUE THREAD

**Issue by madexr12** [chromiecraft/chromiecraft#763]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ x] enUS
- [ ] other (specify)

##### FACTION

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

You will find too many ores around each other, I managed to find about 40 ores in a small area in RedRidge with very low respawning times. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Fewer Ores, less respawn times.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. What you're seeing here is the lack of ore node pooling, so all the mining nodes in RR are spawning all at once. In the long term it is intended that these nodes be added to pools of nodes instead, so that only a smaller percentage will be visible and mineable at once. However, this is a pretty enormous project, covering as it does the ores, herb and chests of every zone in the game, and so far RR has not had this done yet. When it is, it should solve this particular issue.
