### ISSUE TITLE
[Warsong Gulch] Incorrect faction flag on map

### ISSUE THREAD

**Issue by Avyxis17** [chromiecraft/chromiecraft#837]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When flag of both factions is carried it incorrectly shows on map two alliance flags or two horde flags.

![WoWScrnShot_060821_215712](https://user-images.githubusercontent.com/84775498/121660218-5f29ff80-caa3-11eb-85b5-59883275f493.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should be only one alliance and horde flag

##### STEPS TO REPRODUCE THE PROBLEM:

1. Join WSG
2. Pick up both flags
3. Check the map

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Thanks for the report. Can confirm this is happening on an AC server with the cross-faction BGs mod installed. Tried it a few times, with both 2 x Horde and 2 x Ally teams facing off (forcing one to be faction swapped each time) and the flag seemed to be the incorrect colour more often than not. In some cases, flags were actually changing colour in mid battle, which is rather disconcerting.

However, this appears to be an issue with the CFBG mod rather than AC. I was never able to get a vanilla AC server to do this, and checking the CFBG issues tracker, it is listed there under https://github.com/azerothcore/mod-cfbg/issues/14. I'm going to copy all this across to there, and close this accordingly.
