### ISSUE TITLE
Awkward pathing (by a Razorfen Defender) in Razorfen Kraul as he flees in fear

### ISSUE THREAD

**Issue by syssneck** [chromiecraft/chromiecraft#859]
https://user-images.githubusercontent.com/68868567/121824018-53a82580-cca9-11eb-8bd1-a99c90b0c813.mp4

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

As the Razorfen Defender gets low, he runs away in fear and runs up a slope, he shouldn't be able to run up (players can only get up there over the thick vine). After he ran up, he traces back to our tank that still had aggro and pulled a lot of other mobs on the way back down (see whole video for reference). It might have something to do with him running away in fear.

I'm not sure if it can be fixed or if my bug report is valid. I just wanted to leave it here. It might be helpful and could be related to other pathing issues, thank you!

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He shouldn't be able to go up that slope, not even if he is running away in fear.

##### STEPS TO REPRODUCE THE PROBLEM:

1. I don't know if and how it can be reproduced
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Ignore the above link, pasted in the wrong URL in the AC tracker, and now can't seem to get rid of it.

**Comment by Azcobu** [comment]
Had a go at trying to reproduce this in RFK, with no success. Not because I doubt that it happened, because your video is convincing enough there, but because if we can't reproduce it then we can't see if it's fixed or not.

The slope itself is certainly too steep for a mob to run up normally:
![WoWScrnShot_061421_145827](https://user-images.githubusercontent.com/81782124/121849456-7e868e00-cd2a-11eb-88c6-ff4379e1dfe7.jpg)

Tried spamming a warlock's Howl of Terror, and the mobs never approached the slope or looked like they were going to climb it. 
![WoWScrnShot_061421_154039](https://user-images.githubusercontent.com/81782124/121849475-87775f80-cd2a-11eb-9e6b-c0bb2cc1c364.jpg)

Next tried damaging them to make them flee, as that seems to produce slightly different behaviour, and after all, that's what the original video shows. However, was unable to get any of them to flee anywhere they shouldn't.


The issue does remind me of https://github.com/azerothcore/azerothcore-wotlk/issues/5980, where fleeing mobs were running through a closed door and bringing friends.

**Comment by syssneck** [comment]
Hi and thanks for trying to reproduce this! Yes, it's a rare bug and probably impossible to reproduce. 
When fleeing, mobs somehow seem to ignore the vertical walls/maps but only sometimes ... and it also seems to happen mostly in dungeons.
I have to say I'm overall pretty happy with the pathing here. I've heard of similar bugs in WoW Classic and I even watched some videos of Classic TBC, where players got feared through walls and out of bound.
