### ISSUE TITLE
Moonrage Worgen have invisible loot and cannot be skinned

### ISSUE THREAD

**Issue by necropola** [chromiecraft/chromiecraft#86]
##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
At roughly 75% chance after killing them, e. g. [Moonrage Whitescalp](https://wotlkdb.com/?npc=1769),  [Moonrage Bloodhowler](https://wotlkdb.com/?npc=1924), ... on a Skinner, e. g. my level 18 Orc Hunter, the cursor indicates that they can be skinned right away, but when you try you get the message **Creature must be looted first** which you can't.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
You should either be able to skin right away or loot and then skin.

##### CURRENT BEHAVIOUR:
See **Small Description**.
I cleared the Cache, but this changed nothing. I also made sure that I did enough damage on my hunter (I did not let my pet solo them). I even put my pet on passive and meleed some of them down. Bug still happens. I'd also like to note that these NPCs (and **many** more in Silverpine Forest)  are affected by the **Daze from the Front** bug (#61).

##### STEPS TO REPRODUCE THE PROBLEM:
* Go to Silverpine Forest on Skinner
* Kill some and try to loot/skin them

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
**I confirm, I have verified**, sometimes these mobs **(listed above)** are not lootable, I believe the reason depends on **if they give the first loot** or **not**.
In practice, **Skinning's "looting" mechanic** provides that (First) the "Classic Loot" of the NPC is taken, **if this does not happen**, the mechanic is blocked **due to lack of the previous Step**.

**I checked in DB the Template of the creatures in question**, and they have nothing that shouldn't be there, **no weird Flags** or **anything**.
So **I add the problem to the "Looting" mechanics** so it's some variable to fix in this mechanic via **C++**.

**Comment by aithdruid** [comment]
I think this might be a more generic issue of humanoid mobs that only drop money being unable to be looted. Its just only made apparent by the fact that these mobs would normally be skinnable.
