### ISSUE TITLE
Raene Wolfrunner has incorrect dialogue - cannot replace quest item

### ISSUE THREAD

**Issue by Miffslam** [chromiecraft/chromiecraft#872]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Raene Wolfrunner at Astraanar has a speech option to request a new "Dartol's Rod of Transformation", however when this option is selected I am presented with a window where she talks about the gates to the Searing Gorge. This is obviously an error.

These text boxes and speech options belong to Mountaineer Pebblebitty.

Links below in sources.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Can't find any information regarding what exactly is supposed to happen, but common sense tells me that requesting replacement rod should open up text window discussing the rod and a replacement at least.

##### SOURCE:

Raene Wolfunner:
https://wotlk.evowow.com/?npc=3691

The questline the item is related to:
https://wotlk.evowow.com/?quest=991

The item referred to:
https://wotlk.evowow.com/?item=5462

Mountaineer Pebblebitty:
https://wotlk.evowow.com/?npc=3836

##### STEPS TO REPRODUCE THE PROBLEM:

1. Start the quest
2. ???
3. I have no idea why this is happening, sorry.

##### EXTRA NOTES:

I tried to use those .commands but I could not find them. I can find no other mention of this bug anywhere.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Thanks for the report. I can confirm that she is giving some off dialog. I don't even think that should be a chat option without the quest line. But, we need the proper blizzlike behavior to get it fixed. 
In the meantime, I'm going to do some digging to see if I can find how she should be acting. I would encourage you to do the same. Two sets of eyes are better than one and might speed up the process. 🙂

**Comment by Stump876** [comment]
It looks like the dialog she currently has when you click that is for [Mountaineer Pebblebitty](https://wowpedia.fandom.com/wiki/Mountaineer_Pebblebitty)  
The rod is part of the quest chain "Raene's Cleansing" frustratingly all quests in the chain are titled "Raene's Cleansing"
I can't find for sure, but I do not think she has any dialog during that request, she should just give you the rod. However, the chat option for her to replace the rod should not be available at least until after you have the rod, which is quest 1030. But I don't think it would show up during this quest, because you can just abandon and reaccept the quest to get the rod back.  I believe this chat option should only be available for quest 1045 as there is no way to complete the quest if the rod is lost/destroyed during the quest. As of 3.1.0 quest 1046 only requires the skull to be turned in, allowing you to keep the rod for fun, but still complete the chain. So you don't even need to have it for that.

**Comment by Miffslam** [comment]
Ah, whoops. I'll check azerothcore as well in future before opening a bug. Thanks!
